# simple/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres
  annotations:
    netbird.io/expose: "true"
    netbird.io/groups: "app-access"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432