apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: juicefs-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "17"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ApexAlpha/k8s-cluster
    targetRevision: main
    path: homelab/juicefs
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
