apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: juicefs-csi-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: juicefs-csi-controller
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: juicefs-mount
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: juicefs-mount
  podMetricsEndpoints:
    - targetPort: 9567
      path: /metrics
      interval: 30s
