---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-user-password
  namespace: database
spec:
  encryptedData:
    password: AgAJlmHxqb4CSOLBzng3kG+G2ZH1oXv3m7OGZ1rhipunkIA6ewX5unM9g278fcT9yIc6Ap6gTR3zY8DF4rvZkw/rVKo5+7+dKZ2MXMauGkRTcG9eY8nY81hergXDKB67JrKbdM9LvX/tj+PeYMD7edocvfcMO9MFxak/vXPlIOyPL9YW2ETCOxgKsYWk8fSVYQ+vOpya4NCQM5dDX6hRB6EgYgdWACN16rgLEAPlSqHwS6otfSYDOmI2FWoZhEyeZ7QjU0WVD4xmFPHUDNnHI0CpPtdBMRZ/JIWoHh2NKAvLMgiIAQExOcF8cms0JquVT1LbcE5Y0uabAxDdNglGcKQt2yge1TRhKNnXsAEzTIH6zrk2FLIBfn2SuoiKgwS9VQedXPhznp7RRjMjOgddaCaBZfH/sXzHemNLxhVxmOKlq1Sco9tqgI1yNR/UTUgfug5qU3HkDZkpWMTXLiPOQvaUYcpDI7lkxmjixObb58pLqyr4wGiUwYD8BlVcXVBywshpxx/c4v7jGQ8i61Uy08BstF3JQ6Lw2ozNh1YDvFE+kivXtnhHzu/ZlTfPgQulcWoV4O60peKvZYgGo7oT8Gjr5B4hdpnSNx8gik9t30GkCp9ICtj2CkFc9+juQButzR8JKArxe0f9fvl54PzFEam+CplH1vXJd6HTJFzP4PtvBe3kJFWse5UN20PJN7Sv8b0EXxsl9geR93+dl0m00a/B754zYI0kH0WCuP2Oj9UhH2BcS39dc2djhe6RYQ==
    username: AgAPP3E7qRnuP4sVdewNyK5xVZLVL/TfYKzAoV0/SkVKQU57jXm9b2my02sBG3jhmalz7blVotjGgudNhPyaPNb/7xWfyVlnmDLgRbuSKBOa3wYBp5lTVHWEjYypW3jdtPavTpXmkeH285ndETv01uPYQ5c5vx3V/RPzBtGvILdWYMUtL2qZ8igX+WVlAB2HFFYN9IH7wyhH5c99to43jku1WXQ6M0MnwdPUiVKLY04VNHWu8vW0JYaFWb944ldf+c+/zyiqEEoSglxRpC+Vr+Dcih2wOkBsWwxgArWPR2ukcs5FXxHgPoMsK5flCVXVtRLZuRiE2IfdUh1UVdzU1Eo8BfJxsqdmQ39YY+HZ0TpfVPZ9CthQ3s1wVU15dpdmr4iraRpZzNPbt2V3RnwTgeHvT/ZbveUporIAwZ9PsP4+EbNVOMpv2ViXPknsT8iyvoOL/E3BzS5kl1IDHhexVc2K3TsJOiCWZgw/R9hRaLqx1Zx4QJon1YLJ6ozm7pGzQRNdAHCNOPSizIcFB5v2sBAxmdW9ApkC/FelSyiQpEcQ7JafuOaIcbZSwuGwW0NAFMDB6mqfVLkSKxEk8Ba8N30qX+B/vCdjv24cn18+80R3MCIkWdzQbx51Ygp41hqcyMlgBI6v2u+STNZgW5ELyWPK8l59RLAs5qOW15KNEGhdagcfRHZ7TATnZLgRRpenCKMJdFuBlEer7yxMuMk57g==
  template:
    metadata:
      name: authentik-user-password
      namespace: database
