---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-user-password
  namespace: database
spec:
  encryptedData:
    password: AgAJYXhSZszUL2wilXNF3NMT0bx6yIJLfWOsSE4Nb8bdDK4sNOSK1MtswGl0kpe6Azbvwuixw9HxX9VYHxpYqqRHj3k7Yqv5HSb8OSMg54ZS/XcxM/9PaBszTfDb3Q1limUCrXbWirsufBpepZR0lH5FjMG0sbKQcSyL6hJeGNGtseTT0nvG+V91EYtRwMO1h/4wNwW0ULKp5QWU0f3bzdldoPcoqwiGdc7gq/upfxeZg9gQkfXKYWqP1yZDB1RH6NDlR3qYkHaGKVqeKxsg5qQtbT7Q4wS9Q1g2LtPuY0t8tSZEvNazpKfHLXAajsj1YvHC8qYw7IG7Ad8FGG2t7YZnFceIFrnx5Rr/hARtRKhU0iD+S8xEDUS4NXRUuaxZKXE3QpczchvQtBc2f/RADF1b50bGmf3DWrnVtCcvftCZzVba9OyGhn4uzKW/EEmnUpOqEwlpN8SvG1eCS0AsFdcHL4yNWWWng93lOdw0V66QbBXL8KzvceAZ0tWnniwtQ5Gk0MVNSMvL+Y2wFNeg7DGzMxB9x6AhZdMJdz+qmj0/kOtWkpUmg76VQ2dhChybbz7Fx1BeI9jVxtEWpqt8mz2hGaVAOzXxykoJ6dFD3cYOJj15boWbowuh3pnFecLxBsYdDFt4jZbgMaAZNX11pR1Q8M3FjE6Q/M9Oo4mjfhHhhflIDMffXx+/1b71An5xOlQ+E8jRoxyl5D/CsyZaadh4vnpL+H6aEoiPjlr4yt8xIG4OeifEqb8HPzH3Hw==
  template:
    metadata:
      name: authentik-user-password
      namespace: database
