---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bazarr-user-password
  namespace: database
spec:
  encryptedData:
    password: AgCkrP1JSmd6laUqCNeh5jf7j+dggxgHxW/UJ+6pjsNRQC2+jY2Dh/91N1iOPTx1NnTqqkjQRFZLifAx3FTC4MyMP3hajwA5QfiQOCLZkeM5wKBVCHdpsmSklOmvwimtroRiMxsExMmoJiwDPGQcFIeBqFYxvyi2SY1o8e0d0HZywZ38AnudbZVUONbORDkjV2jlVBDFdGZqMuA2w80PRwhEbvxvVwHZBt6AwIP2lMBb/QKJnkjiHjeWFP3KS4SgesrETtpJBUylqRnAapbBIBBVJXVOa3xQW3iTM0dfefOOWU5TXNiaWE8JGTb2oAZV9uONNpRPCEtACbtFz8XbwIrjVJiW0gM1dTp/oQroqOSftP2z5AD39/W0Ln5BpLLeuQ5Yh2PfwiGBWpCAlohV6fqOWzF5sWqVESBPAlw/vB+AySHQzwfr8Oy3yDiJOR0X56J136nUnySYXul4bKyLQ8/QnKsLVw55h0efcaKNsOXuxzeqfj6E9Z/EnxqjnK88i6hV1kX7mRsaoTMe7spuWYyXUQL2WPC2WO0i081QL0Ja4v/Rv65KAGwuRu1rSAYmbPJamr6pIvDxTPHqstOwPn5NoODlWMPeWPNqWnbG2TmGwi5I9JRaC4umyln8Srys5u7TTlh9blTiOaAqzTLI44C6L2a1fHLiQRudJw1ngQlgVo3pentwPpd0llOe8PdgyB8+moO+6ufZAr1/bfE3tDl+sRvSQTzPl5HmEw/kG6ZOG21hYsou/srmNlMsoQ==
    username: AgB0hy7RZpxxuJJxvYyjariuWPNnblZVjz3BYSvZsclI6B25g3MX77Rp4ZU8TtGxkfcioY7sq9kqxU/Z2x1ATj2E57JQD/uDIS/qlgy7p3WXhIQ3hYeWOEHB59GkSnNn8WgFjisTGvyxtOR7VpJA1knhv1p7QdOopCXkThpUY9zbXB/jT1XtZEPPNgJaJM1v2osyb+sc0LMHfNv7EO/7cRxmbXkNlY7U65lV/6kTmv7vk3vH4E608y0fPGAtmos/GqOxLzVskhsnIf6yR/OPm6PmeIT3cB8wuf8d6BkPMlCxx2RwVULsAj3vXybZEvRvSrQNs0Yyv6r6yvt5ps0mviNifVXpIDJJ3/mHD2X4oS4T0wV/bTn80mk0dzCJ1vaNScnJBP9AWGVKxmOKs0dLvK9S+wH3y+OLHhQyKezw8C0T6LJl2ceWzCWjA1IB4TPnDC56cwb+M+H7ZgvsxPPmuWLZ192gBCsTj0I8PBgn8I7ekhrDQRlRzjV4f5XfcxH5Z5UaBbo/ZYDNq76XnS5rsN6OyK0hrcxNayQfHw39RPCvksI/VvEZMee/tgvBUPZv9i5mik9lf86gc7MOuM37kDfv40adkuE7qRS+24v83z82TEA74vNpByvM5BOYGDUEEg7pcoaRiNEdsLWvTDmrbOuIbFvrV4zxRvVuC0so9YDlmYDiTHf79EHQko5yo+NUK/URoMMHTRFT9RSjlQ==
  template:
    metadata:
      name: bazarr-user-password
      namespace: database
