---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bazarr-user-password
  namespace: database
spec:
  encryptedData:
    password: AgA1r0xmGh/Ez/KpltdFpg+64IFyGJkrpQwIWIdwl6JaZhM6jycZ2odTDwLiPzCtsFJXqhhFmvN0PumAN4sXRccdnrXrziUDnmdjQq2vQUMvh5Tge4fofPxZnb7y3zhaiAwwG3k9h2B9ZSQhoe/V84451Zd+GZ4qqN+Z7y0dcE17yQzmFwVsZCD2flJiG0dA+jKvxgp0sFSFpCiDAg/6Ysnu6ypZ4O8YuIN8RySxumKQrsc401fYeC4TR6OTKfBlVhjukd9w230n5ZTt+8PXxCM54QzRq9RrSjJN/pCUb1OfLM45I7F2Q945z6NK0dITHauO8dUDX6zRS3538RV8e9er69QHcjkznI668DWphsspVokAR8N5V/WJ7OY0+jkQgqXnGJ0wWZQzvPUh0iemK3Jqfrb8PzXNb+uyHqzgE/6vojXeTf3eUb0wMf2u7en3okulOaR6BB5u8OLMSbFRq2HnUWkPywUPnCH+l9kIxVMuIj1BE4ML4xcOZSqk4J3S3WS/uKDaOQAkvMZs4eOfEI0jB3xY3ubYBhE30zmlr/G21LzuLxROkyerLjbVyfyiv4LCqh/3O+uHlfm5h6hLPDg/17XWPEaO7rodQC92N/cBjrzV5Tx2MLmRTkLs1/1teiq+U8ojvlw61nRDalJWbIkWiheJ5IJki6M0uLNNg0aca0V1J0PUFEJZOlRa1VwzX1HZ87IpwQ/Bdc8XV8OE+JBgBYVmQdQqqhIHWkmL7d5mKcT//rOFpv9nuR1ZdQ==
  template:
    metadata:
      name: bazarr-user-password
      namespace: database
