---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firefly-user-password
  namespace: database
spec:
  encryptedData:
    password: AgA3eXcCxoxXhZEVNsyIPGqdPPmQFWhSN3P816walLOxF3KtLjAabMMJmnMGuCrxyX0kr+Do5Ut3yNSOUf0Vb72FDAenUglyP7urVyfbwWa9Ne4ctuiyzkpoCfmW0CpWmNgPrLeEoomU1iYOZjq2Sx6GHGb9urUSPCoXsQWq5QX6SCC1KTU3qJbmivV71x8eGK9fC7K7FIVN1SdDGPVwk9LvwXdAQnM6z87WJXDch9/XEDCcO/Fk8vfqzsIEwtH2OQIpR91DrskVkrANvHYpAJN8u7P3VqzUBMba4TPc5gLb2RQgnUtDqPeDNin42GeXZa/uqGf5zSMhJcG+soi5RtldO6z6QeOjz4Zq20CFy4TGhBDLcBVUlwFMUS2K2cgR7XWPUAfLUoeM7yFnlZjyQnh+iaKIUM5t+68sbc4FICLzxaN2xNTHvvL8CxX6e9NTxhK9FRXceFgG2vVsNJJRM0wNALxEL2BHd/Czc2WbP/oqs4r7ljtIZnhlrUh9u6GxtCVffivbogtcvHXh8u1u75N5LpMcliIK0+A2Z7exDxJ2javJhGzS4gbYtzJKgMMd0VC87n8zzSVVZBfA5Aq1QfenBKiIkVfA1tx0zB/Kz6B3td2VRNjRJWu7g7FMRNLkYESpcUU7drM/iF+92msokpEvM9QqWOuuXtih8XGUURhC/WCYLGIpTXs2UjqblEDoTnS5c5PtMMIEp2yARmihO7X79or+uorqwf2w8oKH/nj1iE1CjNVoON1BA2iToA==
    username: AgA5X8QQ/Tcdci10C/ATd445T+wruyjIjMWKcBZlM6vfr90EismLuLa10BL4pN2ncQda9X8wlUVIcMcg3P0B75+TcyDHtXhrEiuzT1b80FSJqZ8IgN3AS+1MkyYTTZAh7qVIbRG8pAftHCeQi3nGNHj7uE51JSCgRugIVt+zdmpouStPRLEU/QZwbRTfREbR8hGMrZdVqBrH6/6bLNequs52vNUJPqwtX749E4GBAlggZosCaLFiCxMp4tsCOUbTY9CT2QqzSUJUF7WhzxLWqQgKOATKC7g0S1GnJjlb/N49G0sO/M+gGUqtaicXR6+8tYXMCjO3X8zYQyznUAnwuuMzrJekwI8RVVqDAjcDplMtASIFJ8HTn74yExLgfdhdZomrfLQm4YoWi1wM0Yr/m/QEmb7zWUzqkLeaqKOZKKMsD6BRLZT2ZrELwkp9AWPzPrnFNqqRoPxa+l5bVOWCSMGSxpfkSa7ybNbcSi6PoGT6+wcrNVtqgXNV1my+Hs9b1TKN/JY4dGIvUSZX++XccTHq2tswNMmniIq5hPCjKZcJuxff62Ipm/6t9Te46jPg55QXZfqXHZ54ALYt1i8rfTHlbqDct9r9iT0IKAc2OlWQR7+HAjZkxD5avy53jUPEyGAtQz7atOrTPZOAzs9uAl3XQtIoQJpcWWLfF2i+sdDbrfyJBIQ8mdi5oxsaXwYUaZ9q1kx9TPY2+bZtuJo=
  template:
    metadata:
      name: firefly-user-password
      namespace: database
