---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firefly-user-password
  namespace: database
spec:
  encryptedData:
    password: AgClgMFaYWpODwrcwcwjEWrdY/X1N0ya9hBWkXqG/6Jd52AedhhZhK5yJ/wMn/uFybBYrXkOcnuK6iWkfhSIaBPgICnWB3M7PW4BXm4NoCfe5z72MhPwSwdIIwGcSz9CqJM3TumiP8VhKyKvXMuQ2vIwl+RTtgzua45Rdy1ivfvvNc/5qDRYu8lb417kMoN7pSqlOu943bnOlOPkHz2hynM62f8cnuGv75HKqyagJcRWjNusWfYL11oS27DblIVCKF5Yb3DmyA/jF6ED4spSHG7sddy+espSUnXKc2tdfUUPykuW9/6QCNOLg/4PkPaYnjg1GhvE5YWifSGlY8y7/dBkDFP9YDgsmbqsr7rdz0TMAZZ9VMRgW8DiJnD1W2GF3+dSWx4FzNvaNep+atZoMkBMvvBK3TboLgsLOuCBZe1ZTuBiM8XnjcSIadpZj6Uqi4FDYuJMjacXoLWf8FfJJTtgVV66OuYgqD34MY8Ta2e23MTrx3EEMkHNPxTY/h06uRckOcgyNQBpyC1meZtvdCHyTFr0Frjv2aL+ho7auwRGvCwBFsazeoCFn0T1cwMqgPc0h0s1WbsfE+mfluy7iajsZDA/+DcfVchmTUlEPOTQ4CNtXQFkKQjbgFAQbl+aHUg75467dKIRJV0TkKQmGAyiX/8q6afrcE9fjSUmuiXk546tu8Y6ugxB6o3mmUSyIhaI0uYGTYRCqGK9jGpIklNZ8dj2v2YgccY9UBsiWxTOulfKAmJl8mrfdakofA==
  template:
    metadata:
      name: firefly-user-password
      namespace: database
