---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-user-password
  namespace: database
spec:
  encryptedData:
    password: AgA7HpXN9uNZxh/lueezRJ7RZI3hd8r+SgQvSczjloRJH6bZRKEjHcYAB7QZfkRijHpdGKs7k9WWDoQwbPCTg45kdgLbojgJaUTMa1GGKjcTr5Gy4PIOmp7DzPaoPtVwH2fvdj8s/0xrrHInqxg4Wwon6Khl9JfCZYvJXK9GxxtGJ9PEgzlVD/Rpw4KHWn/F7RFgOQlF1P0kjO50pCEU7qHsnbNs3AlHZZeVjdR0am73hJ5pLr9zzv5nh7+TZiVhuTxN5rSpNVaBzkx/RLZOUTLRL9umxijout1DapcoDbTdCmm1Yxdu05UOHheDdJnaH1Vc6fFVHgCapVI0bRfekNZZ4Hld3CqOuXFeQxBnawoYCmnDHY3eArBN9dC467WvJGaMoHCNMgDaERlhAQ06rAVX4x1tSFdvTN4AnE3W5knwVUyebp9rdFVNkfjsopPMDUNa6LQ4q9xpv9Z0OAl6//UdAjfd2EWV/A6Z0D6YpNm6MmD1+s42YyiyIxSnTn/egs8Tt/W7GWJb5YvQNDw0oxEL4Qz3mECd2TtbmgbPKIG/E+/pKnx3SGjQGf1XJSliHifhU1lheOmQ7utdUDM2RXg/xpJjixmFvbrupBDzmOlBIh84J0uSb0hflGFaK5rBOEomxJuKBuOwetFvEn1Bf2/Ui4uO7DkIh4o0KXOBh5vFd3fHsmXm9cIMvM5sVJ6zav775upCOu1B8+fy8R7MoLYjKDQwYAzyZMHbYF1fQvqpJn8N78P+vSiH6VNdhw==
  template:
    metadata:
      name: grafana-user-password
      namespace: database
