---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-user-password
  namespace: database
spec:
  encryptedData:
    password: AgA6HuBEFCBTGitzNuk2s06/gy1FbfxoUIVS5M1D5i0RkbnqNgf4xYE5IcgVzn6XQgXFDLOsPKTKwmqQ+4gjR1Kzlvcr1mKm2clFF3CQbK5coVgwdyVFivb0twgEADBON0gvwDC8WLFry7o4xfROb5Y+JQBvSVoLf2bspXS5y9RnHIsfJ9sXWq3NV9wBVa2lfUITZRR4ykihEabgN//JPKsDnMbnJA24CWppvBjCFSgTwWyA3vRt/pmxgYSIwhYbinFOYxzzVwxGB/UUq61SNwxsZwtQlnQ+1kUuRZnX0JvD+Ev5bcExKxevWBI3XzNfzQnQ9BfW4VmZFX4kdrTD98a/3UupawPMz0mgp+8ZoLBUmXe9wa8XSpMpR4rM69NrtW1xND+Vg+yOVbtZjnjm6UuajOCbe2zFnNpWKH5k8yYsnQj4406R/h8i9NsWmpulQYFt53HTph+byCHOkqgiPOdOSiTbb/HkmFBTnWF7P9Ag6Zxe9U+zLcXoRaSXjxW0TwhT5gTmkEwQsGOs2MKV2gOpX3q6ozuPoXRAzNZ8y7l7ovgZjfBI+JAFiHS3IyouzuXmuHiUIavRTuAOw0sPC1faotXHLHh/W4vgDvah8QCiEVNGx8ybJIaXO1q5duLUHk42bzSwIEJPSpCpPjJ3fbbNPw1kDoIQUhnNynaXWliPAV63LA8x5xrEFV5rDMUmkvSRDHxhDzdRA3D5ApkBQW3IQgHvvwUX1jSKmq161ddWQR5mboDdMZIKC9fNOg==
    username: AgAXlgHeT8X61iT4svx92+t+B5hr1Bm8rR6gLFM5CkGW+gQMXZm8pvo40wtl7RW9MaPC8KbenmwYVclMBAy0TDzwKsoIqxta9egKQ/B45TRWQvo9GaURwwD9wGXc5352iY4rlEfBAOTDBqmdedJphfq8p7ipdWDpCbizcO6whKOR6IjUE/gUKaOU+AWzzgYJfkV8UT8a/pbmESuONoPWSLTDKQ/LchXIkP237jrBBg6Xw/CXd7vFBx3f2rYARAuygl/V7d8nojofrw0FXy2CCFIGpa4FPBl8ZL0O9/DIQpw6xLGGZQcjD+lXzPbDLj5sMuMQ58P9H/ug/XU641QUz5Nx41YQTXveAgLaqGtHYzFqmAVAmDXuS0+TvFMfq/cBGnwxGxBs5JzMkeFvrnTT4+nPqqLtruztAmHMQz6Ka05RRkjRYJ1vtNkiJfInao2jj88mihSRjB7hgwN76UQM1S5pmsmgFRTBnuXcsCypJFCl/b0S8rHvCTVBmtecYKg+4ik21H5r4ElAIVigmGyQJCOOYvyeargNjCXg1tMiv3nFPOi1eiGyGLNS0Bm89Hr4CVrZJdXQQ03QGOpVskyDOaw5L54SorIfRUA9befE9mJPMH2HT/bEJN5eDeDWtUzvD4dUn4PeBs1TM97+ZtBiCXU/Olf8lXgFAgXaMuO5hxy626z56XcQQGwIaUpTRduDuQYdwCD3b4B/i4EZVrA=
  template:
    metadata:
      name: grafana-user-password
      namespace: database
