---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-user-password
  namespace: database
spec:
  encryptedData:
    password: AgAnAPY17DXEmCBOOHFZMkEGWM0zZsyIDrrqchGaxsws3/lIsfzVQXTvfttWy7B92hMRy0goCypFfm7Z3saqSINsL0AFc/K7ybl8o2UlulPhJVhVEm5IbzQ51G3yQ/N+OY6j6uyHlrlCiNcCY7nrwHEfbwVnto557XZIZ9CVU65HuNvKUn0Z5BAhA9BIzkev1m+D8h/62jnHmB7Xd8rgnCjiBPiSmdHMfoiiH1SU7gmxNHBW1TKq9YGpkoCsfUzz05CR49MUc3PvazssrVQeGyIefU2Dxlf9vz+xF11mr3VoBxmg3/MiGATFGGL5zBsCZBtrGgOt9rcLGsYGyONQF4P+120v9alc8r7755oda79gj9NaTMQP71mDWgdRbG3S82k+dZHGoyEbtGREBozoRqU+BmAApksebG8TRGUpAI7CCTz9zw8GdAWFSGOFLdLLuu2JvjJx1FYzlbvWVDMv3Q0XnirfnFNfpsTeu4A/qrJ9qPKY/LYN5xs7nrmm1xzlAvlA9nG3JtjeIjEyRPkw4BLmdCksdi5zv4T7XHFS0QIapOeErFDrVUBXvs0owx1lHbnM1ta8d58lucl8vDGVsGldnIoRZiV/NujFduQ6QyyKNDLDuNZLNdqvwoe9/vvE7/ys3nuGsMnP/zT97lvlO9wsCucTXo+9ANbb6bbCJwZ5xr+bu2H46/8AoOhpCA8+yVZeQUq2SBloRbT5ygOMKydXiKfKJhQBIbbDOP9ScGya0PRb6SzfhE0wtCvSa2r6jrpKeHCx/jtnlM/Gn9G2W7qd
    username: AgAOuKvcLhWARfwFZ7veUJgPIXgFgrCh24McK2mN8leZEnawTiNR8l+4pMwOEsehDEEJBx9xqQhkf+AZd2dT6E6KRFlsePuwYo3xezNB6g2RDgbpzR/I8sEOd5WQ4N7WvkSkP30o31AqUbWuzroyF58hTT1Euy3wwNclc9ry/WyBR05Dsmt9wnBKY0Nb84EKrsbH69qiopzzkuiYxW8MehOaAs2riHBlGR+KLCPeecFMH4rYatBINl7Xi+GduaDbsMczMpnXiFBBy4NtimAvHyu2EsrbNnCrc7K5kCr/uO1nWvupXE0rWNTv/kLWY1uF1f7IMUi9CtbIpAbpgTzDzZDZ6BxBzyHye6VpRQgiyO8Vjbxv220I8XgjgIW5cdTDlAVCxZuopVqyrcm0abZoAI3V5sss5krWGNf2IFR4rA31OhZpgI3DMCC9MqUZSJ7VY//qzhi3aOmj3fBIOL0IlQEZtx0t9G4Ljs6eO53c1HsLRRie2SrAe2E6oqeLBL1lAvR1nSY3S5DfOMxxXeLWJaZOi+H5gQpkZ7Bqi84DhESr+mzhpDUslS2aFlfYs6pdWVwmVKUWPN9w06bGni8nq7UYRIm0aH5YZlUFxsDqk8U24SqCnDcSsh6cpaSjDCVcXlmlR4nqhgxGvVjdQAKll8BbyFVbaL9xAlsVrAasl6SPnm2ESmz+eU7R9TKIZOweuQRMllqOD87cWFXrnQ==
  template:
    metadata:
      name: immich-user-password
      namespace: database
    type: Opaque
