---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-user-password
  namespace: database
spec:
  encryptedData:
    password: AgC/3exmfEdoj9K3LGvblOFVgdfyNGZUoHMyeKqsFIKbS+zWOSZXI8qVFjgipd9rRvcGIhqfWkrosd7919x9PvyNdU1SP+KCgwzOmd27EriYnhXeb31OuoDLooXbLp9rBURm8oJuPZ/KcY2XxUFOrEe0ZIN/enntSO+A9wxf2nVOVZRykNbk7urG94prZtR0NlQKLa+XJ/d0K9ptQ0M/UunlbDrorHvEPRIDYZ5j70R0irqSycbkP508lK3A22UpeZo4j8g1kQ36dyY0wp2TUN2eu9S3KvNQtT4YLo2aSOtrG0NVZQPoF0WlzQ+quNIiEmzNew8CRfCVyIPFBd7vfwlwAYQ+w30QdWS68aC0KjbBUEKC+bncJDKzcidZ2PT9lpY6zSyTD/jRuYv9hCpJutYY076BFFPblvsaQwltPEADXsyXI98pgpA1L3dWceyfxYxKdWhG5R+knMdZkEdHch/tkUxf1opvAJ3hmDWybFIfCNjaDO7Xru6RyU5kz6mzjX9TXP+mNy99R6vyHAIa55nRXgIHrYPXZjdo8K2UcOlvsG8OuH39luGCKIVDNmo+PMjy/rPmGIBc3hwCWX5jFAZk33/QZZ/o4OlVxB1aSmxvTEzOhjBYKa+9iUCA+aKyf99RdRBN4kV68Rqi+TjV7FTtWlpzGdRBgQOe46lcM6DhM0FlsWwrxaHBEWC8fF6y1DR4Z0De5WVXw9mwqC9NcoOs5phEh1PWYCkV8nWgGm1gtP9nIvIlCilsVKIHxQ==
  template:
    metadata:
      name: immich-user-password
      namespace: database
