---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-user-password
  namespace: database
spec:
  encryptedData:
    password: AgATWzl51n1PUM4cfyWzSETmDjG8yGXnDhr05jB1nTrUCt7Y0V97Ay4pdYu02527hI1WfbDeLoExand+eQL7jAzMr4pPNfFxdrypAlLtQXZRhnTsrMSNPVo51Ks+THbscrtcmFj+8JHLROqVXzyGkhjFjd8B2CH7rLaQ/Toy7rDh0HRG+5jEfWHcSEJMZk/+EIHEP5sxnXD0BiZs32T4zFVbSJNWDC15VUtl5xKQO8GxYx2v7eoZQwARCrnpvMqj0S4nCgttkWPUgidl/gGIxbsvQuV3mM9IAjUpcuAhEqC3T1jBSr3+XQXoWTeuEG0ep542tzcgqzRCZ87ZIjGCZxdH1ijCMYNRkU5ZvVbiSel1S+vbyqKLDhl4vJd9xoIAJEu3z0puvBm4Tm+dGpDOUnkOfIXy4g0V7tbZwFZhLqKGNaJIo5gtp3HxTCZ98OteDsKGlMDOpuUIdCfFzt3s0AxUlmvDQBekKVw/a040hFrp59ghO8yWI+TJAeA23XINN05QR+B7VOiwCRVU7RAkVRtCkcSub0jjQoilZHVBfXBOI99xv7uV1v6EaUv1Et32AX53qnK3T7jwHdH01X8KJ66VuH/eT/uKGIsrEfSMAtrGU6ZoCYXMGTXFy8ERQSkMy2pRJ2j2ukGmpOOPXlQvkBOzJcPbGd4EwgwZELjs7O17T7rgqDu924x/b31XDDiWxYw25bKD1zWOVqzblnZt68Ha04+M+L31nmrqDLnUZuHPJjlCXXJeTjLnrtVb4w==
    username: AgCNdmhI7634FZX69eOUE7C96Wl5DhZra36I9QbDoCy9QwqDIgI2TuNOaAprx4Kfeb3ATLS/z0SOZfFePKU0ZtA6hD3fGi40KHrsQYSqvi2a0f0zmP0N3NQ+zla3b9tchp45UY0F400KuzWMh4BiuaWgEk9Bcyr/ibM8FLpS4IzHRtLuCEFW1hqg7azEe6M9Fy66CwKJwLKcXq9EU8vPMNla6MDuebSUPuMxyEouiHHzFGbB3bQMcU/9Z2zyOMjAgASsZ/eeA954fXMqBhLaoL7X4xJU2ZJhTxKN7Bbugk5SMK4DSowF4Voh5lZFyxhmhY12h/9yQsRwj3wXhSX3FxrXHRDxHmxyYQjOr4fKak4YouzB80rSO1r9KZ4ixRkFhhXLjru1EwyCOmLUc5suTVQx6PVDsYKucsZG8hu9EVA8tKST3tXKEtHyRTu7e6yHmo9WBxwTRf4sjhHuBbPAGDG9AUsh7wq1mPEuAtvG9+6XJ4mImKyZX1djykHtvvIeZfiCMirPcp4T4PThJRQNIFif+UDPI0PgoXD1eVhgW69LJD5trJa+Rsp4dApCP3ZHwFLRHV02JlBN7wkCImNXANDtg3FWs1mFU6C2LdJsCRE0tvhgpBebXR9GA6kdQZttIumWAf8pJaRMqaOK0PqYN0C6CcieE1gmcVphi4fLxSKEH4fmuQ5F/M4JLLZZdWEOii+e4oPgo1BajnEsaQ==
  template:
    metadata:
      name: immich-user-password
      namespace: database
