---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-user-password
  namespace: database
spec:
  encryptedData:
    password: AgCBo7fDE5v4Ui4hLwrnDUynPBwlGlX223Edglo51c3tjQfkqHiXkHuCsOYYiu1pnaX68eGIjUZBn6uUC7ew7mKU4PZxwl/J9+Zr8751G/F12l7vdOA9xG+ACbN8w+1unrac8TFnQrM72bS0cqIKz7dbeiqi8ga7VfOB3OKOwyZ/VMnjOUbPzEf1M90+FvnMHcR5Juu0071cYC4Gn4sOgD8+jL0N8q21el2/bnQSRHU+/qtq2QrrkjfH3AoYqdAQP0fDYbo1j8Sy9qXtpRLY6XomEpKxrG1qTHJ2X5B4/biZswGN0kB1aaHAT5EAnT2N8IZS+XY4myYG3qIePpwfOUykp660rbMoPWSO6ETBu+Kce5eHEnpMmKhSrGPLOBsJ20B556fm1a52gL24bh7STVsD8hcoyyEG8aTSFToQNT8so7q5gtsAeErruaLQs/nK5kis3UI0IwG7XpzIg4BCS5OzrEhNmgvx7p5bOPFBRyDRiH0adTeCDEiSSi0YC8o7qI7qGtVZinHUSp0lAdAqaprDYlKJn6Atdc3PVRtf4CeViwsgTs4Q38015H19ZGBTpSkyyrJn7qeXc9h23tpmjXmQU7Y1Mv1jv/s6IDyLblc1B/9Pgs5gCDfJdZUCeRftLsBGGwAAOTAKz2LD2G5CiXHlRL4EwgABZzPUeugUvnsmXTBSFN9Hhssy6CDvHazQrCOx92OBvVyssRt6FYkOhL/d2a+yhHA3nwR6hNYuw7y25A==
    username: AgCZdzSVEL6HgKElbh36VI99sA6hj42CwL2ubEDi4LzEGx2mjAnabZhNlvXJ2W56ddY3dIMZWMaZWcwJrlzMfxCIqU4vrA30GO4N8YnZ2G29r7EaOdsUYqvhSS5291V++S1vX77q5S2p2nZU5EOsWxiJITsENE8mY4ewHXqVyqQB1MQWrtYfkJv2dfGOQ+dJxfVZhFWpqiZbR0gHocYUr29qDU0YVG6qjZMOQz4pN9T8N6DqciDQdmlQoj2i8kgeXkG/mDHBxowOaJSyPC4B1I91tA1M1TzR0E/h8fZdpNBwg87UMiO1jiozAC5XYF6i33aJk374RsvsY7fxXhKKV+IrpFY1w6cbn8FB1OWrUGQiCDouTOY+1TGHja5MUKruHwxsSKsJEMn3+00d08duPxWhrH0T9hnrLMxDY5mVq7XjYnXsIlf/AEKK81/IXybzeXVqsQgX1kLSbS2pO6lQ7mO0chE6WDrAUpizSr2unl3A6Tu+mx6fbywQmdXiUCfAD/iZtBnRRs6TxOeKIQUzl0avdD/7Xyj8DHd0oG05uhNmPueKjrG2h7Polczj1iGQi0i9u3SW9jvAUTpa4NqHwvd2iw5fybVQuz4glINiDrjRj9SPxoVq5d3upabkEDQLhIbagcuvF/yVxg6mU3jAOP1XwGMDYPrDx6X2NXzdTipUNwx+/99b9d8pmgyHWcNFPwOSmacXj9KHuzypTQ==
  template:
    metadata:
      name: mealie-user-password
      namespace: database
