---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-user-password
  namespace: database
spec:
  encryptedData:
    password: AgABEDAskEjc/FfgsYSuVvWbq9KkGTwXLEM2kHs31SFpPb2zFfkBptJWylrWthSS0iCGUDLWoPeSPUf+dJqMELiWX7zbPkMF8rd//UFTl8dN7IaAW5HffoIJqIVLYkNmkMgGlaS0W6dEPvGdFBm/Gkv6H1u4GukY68/suEiPMls9cUDRPibHSLx4iQCD+DovUsD4BuXt393BlowqzmZatdFECd7LFhjRevA8ZEW46wbJUv+ksNjK+8mE3fmjJ0QJZAU6LboI9R3NAALb3cPPHWLIMBbHIE44XT0OAtW3rsErpbieHNbRSxzkprINuPVEimCxqhFTQwmM2ZOI93lVChgI61JCK2lMK5optpqYVo9G5QSAQizCb0OxCwauj5fTMfAitIIQ1z7+6RR4LDqlSg8lDjJDSWWLnitYH1HDNv0eXapMdR1gAdNQAJ+s80IDBUuJ52DQLgsCoVfEbfYD7NxxgjxfOZxpOtk531ZhACWSBkFpFYi166XsAxca9/hpTy4mJTOqAiwK3DWOTVL+M8TQzq1LP1RvKltdiQC9dK6+P5B1zuB/zFX4C01pRdVByQdGrNtM+z5cDW0JFvzGwZFpcPZLYL6UxvFxVi/hQeL0pJw/1FGX+jIXfuCZOwqrr9TD0sJT4mLItj3eQuSwvzDWcXlx51z+fEUXYT+EPxkH74gmSrPQvKWyhyRhnzvtVxIZPSt1ICRT0WcYd4+Fs+1PpH3csXzgr168xKHF3g6zgaXUq3dCJ5BdLCGm6A==
    username: AgAVfZHNr8IjJHfVlLoHHkh+pgbUAIYrjTI+QwQeTUZxiC7yPmXXx/bmg53VIxwfKiJM+VG0leZj+gzjoYwKa6e4KDAP3k5EF5CEnVeOqVcptwKf64DZK6tnoyjn3ZPmTfFW2Lloun5MIhR/FlORtEZgEo+l8cbYWcVEVFqpaU3fbZuzHa1sSr5Id4Zy6LNnuhQL2/jnQVGE3yBDyVmQy1VZNGmwExTpE2rb2RkHZI9xCqOYCKrcBstn/Mq4T0Hr55Qi3zbgiXLdJC/sgHHuPtJKQJnsCMw1gOm8GUciFX34fuQP/4lpzH6dsCZ20nEJMaqwthcby0KvpLPOXs2IDIe2o4R6TGQm775ALMvcvYGsbNmhtXfcxDM1ErkFiVrLNVb8t3RIlUAyRfjIJKLU2V0u4Q7VaAvHmJtmG7dyn54lAq2rZJSHYdkekLn6X5rtta+9Ap3Jww9qbqk9owNWbCGr16cefgvgfzxhqiClhxA2r00ei/g4GZ85+I6zCUeBmTciTE/g4f5VWSye0nRQSRRuP2aFpg2WBHBGh3Hj6YhjAZLqDG76O8CskuOL993jQOgmDSRay/T5zpA0Ifrzo00iEh3gl9T7FLRCVrXoHorb2qrgi8LS3oaa6Wk62+uX79+RaNWbiWNdB3KnBEioUUNeVpcOLIqn1efBz0qloFyXOWk49mbkABcNesiiUOCvehjWwIQDsiQ6mYxAHQ==
  template:
    metadata:
      name: mealie-user-password
      namespace: database
