---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-user-password
  namespace: database
spec:
  encryptedData:
    password: AgBG1xwRpmxdiN0ylC51MIzfN8C3X/SqEfTE4s56+J/16VywRNO83s6kUsBVAAONMdskeOSGsOEFoWpHvNQQvI4qBHQ+524jM/NAD2ycUC/CDl9GFxEMRhGifBvTk8LJlhOFM0J2I42UjnY+yBGD260Qb1T3Ew/YZYvacSUQ9McLd8jckkixsuJhJUFMkmLc04rlTgh8om93Kq0i3qUrp2UtZiBe7bXvYhqdnPuweA4Lb8fAHS6usH4+Ez+Y4K2G6lRHhP9wPs6mLjTqYA05mqZJdHZ+unQqoYirhTuMe5nQevdee2bC8MkHAgsevT2AYsIvOO42lQTrDgVpvqufqUwMb4SzEhH8svd7BOGvfMDl1UeaI3xMj3WFRXDgVXKG8LY9V3MkBYSg9D60qp5V9RMQtgBJlEQIx61TqafcDRj71lIs0v218ofCrrTPatoWHX9v3V2mLiqLs1zbUTT8f3vrrXOzXTHnKHVLKNUi9vyNSfI08a4G9CwPPFG8amTW8B5/twTFLxsKowafs5JI7hQk3/dUXp4n5uBRz5npRrRYdY3qEw2eX1lfiqQC176triY0r0K7hVP1tVYr0m4JqsVVJaemOANqMN1wkDoaAyjcmhRZY7L2CIXV0OvNf1607NALIMCY2VbYxGcWoJ7mu2tRscmnGAApjdga1NpKLqfJl1F8FJFpnON1GjTm+bQTwPrS5c1N2yskrFgrzeyxfdjW/Vv05J1sil4UDpV2nTFyNHTjwH4ZqbsBxFVkJg==
  template:
    metadata:
      name: mealie-user-password
      namespace: database
