---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-user-password
  namespace: database
spec:
  encryptedData:
    password: AgBfrnBN761OppOF5ve1yl1NBm7bhkGxEjPwlyBjIlTunYb3iJp/6ngjZp1m627FEEw+gnlmKpnFDEqhPGLQV0AI013XM4OgmLpplwGzEmcVBTuYZuldYhqfxrvkyI+eeEkUIVC+y1E9cC0H+JlfwovIP0E6EC4wjU6X1FS/Bp20UmOrHFWfmPemeRuCPPEE7ZBa8rNbaj6WgBJGmnTw6fuTQkD8xXOQXVknI985rNkE60g8z9vdKLp0V4dG9ZfwZIQRDBAkrjkDv97NE0Od6u5c7dBMiVzWrEe+34DWBpfZuGX59ixRl6JCflqHQj4Qyt4RTby2VSx7we7gewTykV5CDX7IQsLag+yTg3d0Pk3UW1Rua8ZD7rPjO/kBDZnpjMoGfoaQV6rixtrzHU61FwhYOHGLDei6KJsNGj4esPVN+Z226D86yDGF0m0y1mPh5HgPP5+yAVy1lHb3Ib9qygUc0bFLOXs0ZegBODms5JYgGGD/fiY1e6MAAif2mK6IiATIHU86cY34tTKDd7BnLcjpxAAiw7Ikb4fu04gM3zwlSeVbejx0BowxM13bFNgIDHqoHHJk1MImrQAH3tzArUIAK2vPSo61N/EbmbgwuZpHiDouwsvlHkBH5HtK6xgNd0IoMg0eO6GPtAqO3a7B45L3XHO5ID/DMD+pK3dktzgFy7i9A9kb05pmbh/5XbObwBMIxu6Gq/Nq/JhywA/DaIbrhE1dfpKR/Uvech6LK4k0yoiCOHHJrK993RWyBA==
    username: AgBpKCK35vU//gAVoTIjCTSPAqhBf/6Ifczzl2F10YXGh+c+iyZPhc22E5JTqimcsy6Pga6ZnIhEyFSSAybH24jCys9dJ0cKl0+HVcTCYkrobvHHwTP4YyPyg06DTHMYUrla+V8u6NEZrQp0KxyGbV32swFxhcSq7URUza0DPNv2HbY+8UQlILARqcyJrvT2WD/F+XH1LOarb9fO1RdI3vRVsJIgYSLrL8rPj7BTn/5R6uTymRmI88FQblaGjFHYLoWyY8yU3sqboinZT7H81irYkHpJRwmZznUu9l9aEwUQvCwd0BNmE+PVmGHf+/ICgtD6qcbxq2Qjkwi1fjlR4SpUFZyhJAun2/ZSnZLWywpHS9nwpzY+oS9/zPQThxbVgs8axHZlXnB+ylLZCOEv9Jkc7e1wFK3vvKN6ANbUAKlhVB4Plz7hJUJRU9S86iq1Hty3QqnBtKTNzp9cHK1lOsuADQ9n9QuPw9Ajzq0MQksee16q010F+oV3/FbGJw2FNn6fHL4e172OUUwZHuC2A/NAigU8IU5UDh8B5f1COrMi998Ao/11puP7kq5Gi2C23J9H5xGKRJhkHIXnbSgutuCvV+/9Sfa0hjEes9j8iByKJKnePLQG0/W8Kt27jmpJIbfpPp4rWLFvkc8uqnBnpGYVGIOJkJkQwye0BJWHddxMx3vGXhUKf1Dxcnf/tUAXoPntMCgP0oNjGKMQa5oavg==
  template:
    metadata:
      name: nextcloud-user-password
      namespace: database
