---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-user-password
  namespace: database
spec:
  encryptedData:
    password: AgC8+IUlnwYdm4j2ysN/ilspiQQrt9y3VarbxYWJ57gzFNCy7A6ix0s7UtX4GgY8Rz2v4ZwFtxubbpnEHwlcqGc7YBmEM/Q1jPyQJn5mZXRZqr4AvTCezYxk6mLVPnuQO/icz3kqqi7zLlMkxAgl6JJUoKGAu+iANL0Vtn6E6m8JgI4B3urCqXLLt8Q7rRXenZtlubpnV63fRzvjudYQb1sGHUYPzk35Ey/oxL5UCEzI1ClUnh38Uqn2c8OL5kCTTiiFTqXEstVrp8FpnzQrOzBelp+UHdLQHUBy8E1FKyNVPBxfX+V7sTR/PqM2hsMegth8r4o3SLERQ8dMR+0dVPoDF+cOGXvMLk/Mr4FBheXcAybuAD5P283EZ3B4imp0FJCHaXI8NxbOP8yTA2dDGOe+ix+szQtNcn31MGR42ZvvPXuNCPLzzeCy6Fxqr67DVL1fKnFB+eOC6IRVaU4D6tXQHC3f5sEZKA/Cd8Ijgec1Uiq3qs9wv7diWh/X/DfTCtsfUqS80P5cJRR8j5zIAJvbprqQczwTx8MfyrXnajqS3Nax/1om/79XzvvLnCxJK5WqqQAa9PDLRSnWwVwQI8Kn88DB21Eadb0lfbQ43/y0GIGmkuvgvFYLvOlmBtZuj25ICIX39gu8iFTuVr5PhAkSuvtaE+72KK67lVP3Vn2gR8VIEyGwrZ+THPBkRFIGO8NspjKbpCuRa4oSFZyREircRZDGcD27P4wFDyIPBw/ZV1sDmkvy9PmzGlY7fg==
  template:
    metadata:
      name: nextcloud-user-password
      namespace: database
