---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-user-password
  namespace: database
spec:
  encryptedData:
    password: AgBkORyLA7qeP8GriP0Cji0bwEAwiZk5r8f/N8f6GIb8SgB+OKRVxddMTFefPKIEx3YPJd53wXXw8VvzCxuIDQhf4y4Ep8FRIZWaiy6q8CAy0caEbJ+jPm3R+77/LV6e3HcVmv5bKGrlym2J/LisJv+/2AhkvZ3X8CqjI9cYBxGPDrjIOLd9Zi6ETy8BIH9y2ExWB7QI4lwVdjI9yNZ3hLzfVKJ/lr+9PQtvvQTGUSKibbp4vZqBkJIwWeMNjunH7J93NTIZDo6NBgQ/OFyWe/mndn/0gLzynNloa9fg8mCtlDgkh6ebpVPjX94vHzkghFWqWYuZ8frL6weI6DiylvQRa6v4ErHe/jFYehFjdaTH6NNz1aLb1meYw2DBn9hpuzWMcHrke5y1d6G42RC9+XxU+pflO4RXfqrRqUxHVBXkSskrjEYQ+zTEKPagE0vZQvHEHu6+6eVeM+r6z0+jFCI9hH0R0m1dLfvCVRrToCCBlId2guzkTSRVKNTORwDr2B8qg9/ON8E2wYRN++EW0Mr03jOwfGWpr/+UZ+bZNFZ6PjIMNRg/23zRimSUAf/Tn6zVNtBZiABkKA7vZlANKPz3Ja1/dU0xvulxL/6vigprFS0dxqDhgYQuPaof+sg4VMBZ56OwGy+iuAIKZLcGeCuL8/1/YRA5+QNUJn5c/1M7YxlpFrgYqyWivpYdC90JlYUIzQH7FnjECzRCvW9AaXnL3Cnxi8DyIzgMJV31t2ZInLfXqqqjnc2k5jA9xQ==
  template:
    metadata:
      name: paperless-user-password
      namespace: database
