---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-user-password
  namespace: database
spec:
  encryptedData:
    password: AgAhltKqqx2AjqH9WqWmZElf8SAhA4dEAwNuGcmMxSM+eyazlVhnADqmgkoVgoK3DKp3VsBYHOsUbvQIT7kpxoOlAGzzhvRt9W5T1RNirtCZ6Dcm6K8/cFaL2E7+4mv+z1bYggd6eFsb0ix+wT4frdBuEN/WlYjdfyeFAHPbGWGSBxzMwwXpWFak7Phjzqlp+i4Ioymk0m1gOdSp8X8nLlLFP/0Et8WPz0Itvb7eycr66AK1TtOTa3jSMKw+BXUZnHGfomWnB3dhNAWqaGD1fBwo2Nt8MQSOdNHfY+whr/HuWQ2O43kOn3Wxks4YkKAFkXftS+lZzjqSO0kPA1RLlvMg5WkJvf/XxmI28sFH6A0bYluv9dQ6b1TnMwvpaM7Z340Bv+67VgXtUzg7r1rc/PyJQeaszsazau2193gJDi9RfyybnMK3piqtFHkWyNeP4os2ylUJ3tsPymZKhWL6PNgtsTeCvfpGjp0ZStW9yDZs8RAOSLN0/ZcqawqJIaqLP6EDcurJTjPLuzhVdgahaAsvLw8TTPgbjF7H2e71fTcBfxu+pvpq7aIa2rQr+bxxak0Qnoqd2MqtkrznXvfP4JIi1601/bFKqeMB5bpa55VdMhUjdMCh6AcnnB1m7dCVMEzqtpdBCTJf9qnwM7emaBgsoqqbeS7m5ltz5DT21uneWx2yeuA+gfQYJMALj7/joRmdUhj0qlv6no+pZu7690eP3y7kRawg/MMcoJtg4J77idFIdPQn2/TeqgH5vw==
    username: AgBDyJ8dSYk4TnWqlpF/tJL4wWT9RbXx+z3MdZyhPb2JL7u0PPwqcoN7SX7LiSAqpgMgQCOuG76ZuidZLz3NV3h0Z5AQ9t+kNorMP+xyAYSapgN+3yxRYjHTGkvM3hS3ZNJGEivRj9QO2mwPNbeP1KYaqB9RZcgZfWgW7FLAKVVnv7E7uIpUme8O1aqRPXc3NTeRwC9KXOGDi4J60iSlsbz4b/A7u56gq8KgNzZ15FhgSSL0uNu8APD014MYvlRXfHctql/FU+Mcw16w9eBZYTb3uVCuK0kpnQClRO8E+UKgwHs1sVGsVTOQjRkvTINwg8k1SEBgKDyB+XODcUr1qdIy90Pdt/WKFbBpUdIK8EZtZketbD9Yo0E84Gq9kwqur19HQCSuNGPCyApDm6bmz7REmRW4NGZ1bKGcAUORLLWX+xnnZAkMNcmizx+GRyApSA63KCUfBLQnlVal2qqTfX39+Inyatk6SxzR+SlmZW6b6XWqTiEc38f6hzuJRmBLVD288ieHY1v6gf2YS/Wr97YRCdHcu8BgsVJYsw21seXjkeAqEeUmEU+HG6vPTZO0+zLo3Iui3OMYEbF6b6WGkuFrPUfCSLbSCCUNE6uoolivS/p+qeVC8pA2qCY0SapkboIxK/mnkld9FtmmDB1ahkA64dffZvJVPdEhWDTNtGrU/o8VKKPviyH3xZJntID/EnLW2ls/wMLXzt+A9LYDqQ==
  template:
    metadata:
      name: paperless-user-password
      namespace: database
