---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowlarr-user-password
  namespace: database
spec:
  encryptedData:
    password: AgC6s4A/QY+J7HRIK9meKoTchhOY9ks2JT4kC/bOn8u/zcQtAJ9La/KVQ8k3uBmxYf8+6mdsNNRVn++sgmPQvRqHW+r+ntKAzuWLJVPZmlpfnupiNz0ksM1HDvuspoNaqihans6+YqhqutZxRVciw5+aUQpapO3l4x9qc3ZnVskS4EHBpjFpnkEG1ec9qsaYcKX6A9yYn8G3hWdGbRCQweW5jzjWWrrD+1KhPBGfpucU7aLnGOIYX6gMjWT2J7+9ZIlTU7MH7Rtpgapx1wgXI8xmaZYNQzbSxDpgcIeoxGWKOQoO1bZ1m6P1mo93yjLEvzAquefOznOQeF5HcTjCv0rYoN8PKWn4unjqyalLIISXOn2+BW0bs2C+ZQ1aGAlwbWSyOn3xQLkGUm8qhVw2Ny5l7fN4aV5m7VALbvcV6GKyQHXHgpOJxo/ER5UHfK9p6bRzoruOLR7AK2Kdp0d8REUwC8XMZLvW0Q+PeKX0YUSvYf2JjXf66TZJittsqJapSr7x0ZBwbzAC9q59h+B6b4/Dzw3SMpvFlZ65ZIkhDhUlBxux77gCJTrl8cwgrBLhqtjCMTdvjiM2EO3uuX1BMWQ47P7EF86s0bWCJi4W2ZzT8LEqMCDMVGLqSNnjW6fFmIm/RTWKQPHNmLoqd75gEujaMhYyoTK+pKetmA8Y+ltqN7XnsohvMNbd0SE1JV3ZZ8w5HMDrAVyTkDbVOvTOKcnadn3+poHb8Wd4bKvEvFm/I/1t1NoLeaB/3pvHGA==
  template:
    metadata:
      name: prowlarr-user-password
      namespace: database
