---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowlarr-user-password
  namespace: database
spec:
  encryptedData:
    password: AgAvN/sFPoqZJMYNxMcMlsCSRrzcE60R5Xel36TiXfxtIDZhTkzuetmvitRPAofG9oFwea4CTaJ6twbLNT6MRJIzKYN6eZQDJ1d+d8zJY6DSnUn5Al0bpkRmX+p3soyLWwSOJjyWnpU4hH/2eGxAN5Jri8jtUNwB2toIBgvrqvo69H/9BnlKEXq5Wmasim4byMW9D0b/2k3Tb3dolco68gSHvIPYQ4BF9TrwFp6fnXGjYa6KA+QjsO2Z9ar9cnCCJHVr+Eq0Y0dZjgQoEo+Tcn9SIaQ6+hhOXHj1jYHqI2dW/GsRGOJxlzQGfbVaT7MmSPgqLMAp8X9L1Z1gBQZLCQkNNhUBTgTeUP0uah+O91gbi+kub6g9qyGK5sDqgahgSsoii4KZmH29xnr7b981iGA8StmExyhvmNFYJ6xFWM4mRCfJOikNKNPy/xRdFhSgSnch0tjuRSJYxR7iAOvmjzhfQfndpgjnKtNZRt+SQoWNK7o9jfpXLEs6AIBgoZL5VDqmGmnGq4oALSTteI7PpB6sPTqk1DNC67zWIxCZioOc/vfEQkqx3ihdlSpNziEPGI4USd2ajnfvtb4ciVOZytYGOjr8ppWaG2lunJjcEBGW6kqYJoEHAkcVy9D/fK9hDgHmfDJWRQdTt7O6e4PoWl13eEVFB5l2x1BI8++6rXg/1SuF3jnIsCbKn8L9FQooGP8/Z+padjafW1EUQu6kjP5BTLHsE2Ynuj7olAQJqzrv8iqQMZG66uEiSU2lag==
    username: AgAZ/7WCeEPQbEJRw0ILphvbC6WL4O6LYLfex9M+JSKP8yn/qNFYw/otdQC1MIXogpYMh80QZzqnS0NOqgcj2nNFSVYyT5AwwQ0r6n92G21vNyRwU2d0ZBEpUny4MhBaEKzSdP+04GXpg/vERxjAFRczO29+qrIM+hxPLxGmjK2fAQVeC02M/EGaKl6C+t9/TBDMnKnzzOFAjEh0j89gcWuHATdAaf6HgKxT1eE22UoKijDs9aPWibfP4qGPqSMfPqyPF0arNgAGGjfW8zAkh2yDv9i9FC08XmkkaNowyPq0BCFFfomdu3JRj+WxWLBD21k3D12EJ6Ei0aahY4tmJBu+VwxdLT/BzkfGbl9mIG498Tjpg7eKeUu/wxM76mIbiDcQyVdaWiigr5my9OdgsjPGCKU7/CxQq38XbWZmmyACJdvAWEYmzWeJYyoLbzGTh1Erfl+rOO8FUEtBSD9zzK0s0Vk2vA69lzP9YoejP6EXdIj0rlO0dYs4jScSlTI9cq+RLrU+NG5A7JBCKpg3b5I1l7834jt174vA088aSgM7doOoH+NY54bzbir/FJrP1ChtzQBt4m4oqIVt2Wlir9/Yer0lCn6a37YBvxzhOvdwqnSa/LWm6iZVsw8DwblkPpP4yafxYvsCWdTJetr40/s6ySCkM1ngR8HGFLk6Mpdyc2LabJCdILRshUAh7PjTN6gbimPIHNVuT9qeIeXR
  template:
    metadata:
      name: prowlarr-user-password
      namespace: database
