---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr4k-user-password
  namespace: database
spec:
  encryptedData:
    password: AgBiyxVL1cXJeyE8a0mlZTDdVV57PzQKnQSkM+H7L0djrVdKyLacE4SuuYSDM0NY2KFmbn/chrLs7o4sGgzmyqE5JZ2KgQ/NYVNz64LRaNIM1cNuL77y/bucy+bax3pv1NdYz1xM/KHANaurjTb//GlGCHZJO3eENMXJ2TZRHzyzFzBo4JXTovTKfxQN4bXlWBvCu1j3K+f3Ms3TTDG8+mL9GFwEPhTG1Vue0xcU0mBmmRYXBweQkkQYeYKjuYOzdb93XkrGTdRpMfWxGmUJkN2I6b2+QVDH7fHN6Z5WVVwZ0RljXF5xpMXOqrGdRygAc7aZD1E7fj4iNFhx0hwjAhJFK3AX2LkY3vgeMTDZxx23bmyzETHFoIimNHt3Bm098a+sBVnRlYm53iHX0aHYyhoO44w9rViCrGyILXFuosnuZg2FImoe+D89SMDSUO1rRdiVHIviIAgbxKy9lUOE20EOdz7R9zxdJZXLHdUzB7KO+Ffpm1pN+JRPSkuLLFOE//ivdOls2EGqkhDYQ8Tupq+81UfrKCMTEoXaNDzhmY1GyIe5yKQdSxCfxmceOFmHtU4VQZAMH7GL8efqCwQmgCFGy2uat2TgSd1nXUA7rHMJvo9YNGLbyCGwsvCkkRld+X27nFe0JMjSYECh8TpwLYXY4lJXaA/Qb+zWvkVkYseU0UsSp86RnOUP37d9CGnzAQ9eDu5dF3IvTcnVtT6Yu40XHHnmmrCuJvhGqA8VJDCGi9fcAp7rQfIKA6KQKw==
  template:
    metadata:
      name: radarr4k-user-password
      namespace: database
