---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr4k-user-password
  namespace: database
spec:
  encryptedData:
    password: AgBmdIPUszHQYhHow1uky/KrbU+XUjee3o+2zoB7i6A/o7izAip19lKjHhr0isZCh5z6bgl5RYuXwgpyBqYuAl3cm1nq2pk1/RScsUeIZeKcvfflYmSpzU5BotPk41IduEyLR1vvtDfPnKFgleCCQnijp9fYYGG+h2LjFXQ7+B/NzhiQfiKAgUPX0dtkFaYKuNSYLbpxLkllgCsIE4AYfR85EDohxVlJ/DAkN2oDeRHMwJSa2Xd9wHqvP/IeuVmSxHqI2tUz7Hwn9lN5FfqktWdnYBVCl98US07mJigNY0I/iLn0Ip35Z/2XKnYlkoTRzhLbhBXODUeVLf56SXmPSBEC53POgp3yWAHFW0FoPWn9Xl65TuEnr8KK7hZEkpH397j3ibrtKsWHUjFRYys9iT2qk2GG7FlexWqgOh/f1/Ge0jPaV+l5n2IRIw6v2Rb6GLan5e0a6dSQDACBtejvQdDsh+OBbLL6Zfx0CrIeJOh2n92MPAYLi/WsE96h7Zo/pSpjGDny14qaXQPycMC5Na7XxX3Uq6LwN7SuVETkfyZJ8imHsA7qG7pdIgyAccZQDh9UGwZeux0LbaBoUxwN4Zh7Typv38IbW0fpOaXdnWTWHmuso74R7k7uyqbgDMHdbBgx82epr+A4HUlFOR6a0DxzRffAuaLZOxSvua/yb94ZWlTIjqLD+KExQlX7pxpeQxALIP0tetcZtyZ9fXe49Iit6cC5z0OrOHBc7uQeYr8dWCu8k/rxbaY0LnaJ3w==
    username: AgBOglvbfypJ9UUHXddDtcfBDFI95xmIysr0VXMmgU1DDmYvbhwfXkjD1ZU1jnm86PVzstqVH5xztrrIMOIe2/RXJK4uLizgVoBWgZxOLoB+/3xf27IytgaekTFEIEFRF17PLP9g7MAzviB1VIpkaUXZFaMkH1aIZLSaDleZzFdtr8yhbdSDQuxuuyeA8D4MavapRxwlS19bcfmWRAyYmq35j/Tz8Sb1UnoOd2COVUl19I4f/tqcs+theeus7k2Ned1yr8KBN7Lz7gKUO0uYqk5QHPFBaEtTccGujN0nb5yki+UCiAPpec/MuhTHIGzXkZYna0vDyEQ8h5jz2qH7/iONspmxNd0WTbbwqy/zKq6voogkcZ8Zfr61Z6Qjim9A9sBaC8TOd+qU2nvraLpO7Qk6w+Dst2dn6WcDbzJcReGzjIOxHjxJt6PBbcTjNCsk4gteVK9vhbRhANunAIvhpL6cvxvJndD8tjkEagIYRfptBwjDgA+de7O1r9HCMd9CIGFfwlb0uKgimwX/iZqIoMLThC6dCEcfsz3xJawBGm5laRSb8tnl7EII9Sbb3Fr56GvamazkC4ffisQwUZUfeZqJ1HbQkHF7XItv19uHTptkS4fwQQjS3CKyWRW1vJwDXJde6jNWPU7+47IWAyBA5Fyym+gcpxP5r58QwmmPvifcKjjO/pJZjHX6LD28ZzIPN0xYykZlaIm0zboZUNCb
  template:
    metadata:
      name: radarr4k-user-password
      namespace: database
