---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-user-password
  namespace: database
spec:
  encryptedData:
    password: AgCdy+E9YbGAmshcOrr0w7fjOHxsMBaMjLspRpfFDS8sv8Vwg1QiPtdUE/9E/FpoUkgBe0kiB6VDEQahAKSRySOFo+vYJkhqfVM3pIQBhKR47oYdBtT7B9HiMel8UbWJ24xbrsdAuXlauMNrRWpWkgztQQvradFg7XUA//wU24EgR50nPtTcRiYolWjae6AvPZHTUo+O+D5evzmw7qrV5ysFDZ9HdwBUHR5nEyPyasyZzvpwJWcIqqoDTLbQ8+grKrpPdcie9mc+gj+wys+5chG8h8M02YHsnTTmntn1rRiKn9ESZ1lMvdwVgk0bConAxA6Avra0iQFTNXpp9kWdBXXJRs8sF1lmE48iIytclLwBR3vQdhJUz/K8PQtPY21isIRBl4atVfmlQuPW2rQ4VYELh+3m7uvcq0Ie6Fkrjuq4jnwMtzV64CtdTkx96NQxY5cr6ahYPBXPFQF4MjaEPo8yfzbgSfpF95rHVrT1RTO+uE0t2fw9b3nHEr03qpzuVQMHnlzJHlFssTB3LNaKMdpwHNVJ0kNUcNFDUSJgdWqjAHwpwrdUqgY4I7KeqODZnZIRUI9wD/36BkDO9DMHsB1djc3RH+IVaqCNQRAassBjhoVdRrbHV1xzs982H+OllkRBcEffNE7ytPGjvuXpxk0sz+WiFboUYrTvief6P/qjI2t97Kh9hyh7ABwNe8pMRFv4DNBymaqi2LeFBfM5MKQf2c6n7kTns2Ob5U/qRRUcWr7Hv6d/DcKEGpctFg==
  template:
    metadata:
      name: radarr-user-password
      namespace: database
