---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-user-password
  namespace: database
spec:
  encryptedData:
    password: AgANbfWh7Y54bt04ID2AH1H5woejdACB/ZatiR1Tj7XN3sQ1lMJZ7669AeikeTnZyUbPzwa+ks7Jdy6uu2lhZif+lyNMfDcTGH8G9faFnQsxXfjGioK1cezdKnixz8JDtdGS62aIFRRXvt+wF4fN6QRvIkDYW4X3fC8IyBx4XgoJDTY6g0nmHme5u80mPdFNbunu0tp15Q2M1ia4RXRjuICidhhkx8gMZBEDLeOX+/p28NlNfTfWFT/FsafaWWmvVFaj3Tl615/s562WarqF2Af53AUpiYrau8JhcM3QuJhHX9KAjrbHHFkGTU0HUN09ALHSmhLhfgRKIlx6f4LBcw1tCzXv9+21AFQX0fVMXY8VArI7HyMbjdeyC3L8tMipzgtp1vyb527Jwny5z4TcJ72joOvr8IvBzqx4jRLOCmcPc+b56O6zcP3onhddLEAywCP2VMOlPx7Zl4nZL61KQg8ujS7SCbjH/GZmUmQMwgw/+JqBqmQTEiLR9q/CHPbefLHKF22kj/S4TbYL54Jb7zE19w7Z1vSoRUfKB5/IFrqf+4oMpVvWCtsJHhcyN4A7qm2lVOwgOUW48RZfo9xGpxdvQFfYJhT753XkmWvluzj06oKq2rRcKRwohON8ucMsxHC1tdsV8zqdySElkDBcXRDHvyJaY/Y2lepfzJuPKfD9JSYnvK1GTKxyenuCSEtChGJgnspKp7a4lus2kSb/kPjz3n7Y0qm19Mmmevjuoc33x+Gvv27Mw55t1JkhgQ==
    username: AgA5dNatgZ1NJTNWNjU5yq4eDS2k4uHp4TxlJLTaAs/ZW148t17AOf8raepT8FvhB3Pz6aTl8VP3dxwbTSQRSLkxjgga+IKR2HmCJXPDTW58qTaIrus9fBsdNYX8wXxwF/xbQvKUIWRHB4hvt7eN171+vu6nw/zYu1OEGpvjsfyWffH6GtsVG0eNBWBsr2SNYFSxqT+G4NFOUpI2Q45TOM+nU1itufw4BUPG/QA+4715SV3Lghytz+A/+xweANLfnmxGom+j3XVsWGEeZYwNSjHGVryJbHVQ+JF3WIChDXq1UrJxkrb3bgRAzkC/2wVclM5NwjX1vXIAZUQGRGwbmVFnYtWKHWKXHH+Mifcv2vRrljWyOFSzAdR8F7Ld07Yo7ZydpcxZy3Hq1TH9qy0vOOETNUcWm+QTPKb2ANzBgvf1t597E5WZGtVJReyFGwMQyz1DwjReJgvdWL0m+uijNBiP35ro6Hln2STVFrBncKsfXufPv/zcYimJ1zU8GtSWzYh87qQQF7fk1Ze5Zl4fBeG4kjAqskzcuKtygozvmcE3uT5BTVcd2KrqwgcrBMC1XYxTd/ix3Hd0wPkI1sxUHG5mYFqTRDep8+a3r2kLjwDj8ZHlsEBF2ObPPpG1glg+4biGrZNkG4jtYrzIQzOQ2I7bdKKnCTyYKlnshUCzcR3vbORfk/V5d9sV6guQyGyTZprxZaXAy2qJFjl5Bw==
  template:
    metadata:
      name: radarr-user-password
      namespace: database
