---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sextant-user-password
  namespace: database
spec:
  encryptedData:
    password: AgBs8BOxry9B4i9LdcyKomHpiwanOreu2P938qRGMEurIj79URGwl0XbFjvTD85SH4DwylctqZ/F631DpygaEHcG+fCdzNHGwjtoTfJcqutWmVLswcuml3Nx6fft8RuVeo3dw7rrDu5xbUxEMdrM1TgUzGYcDaw7Hu7pdSc7lqsJEuHyJM0ZUu37PldgwtG/SvBgZCBLTOk+GjZvL0tNWJl/TE5wKFTqMG6B+zQly0JXwEFzQKXvX5fL7QcdMEa0MfBqf/Rl9NaZ31En555ezKF2vVmoAfsRIbbjlPbtPFXHRrja7kb0SKGXA1bu92zB8UEfDmr0kZy/COXGHatY+DYxwnT/SfowZAa5sl8RnZBj6aBjK0U1YeUq3Gz9btq32KjJ0wMSQicYe01q+cyTU5azGbzS5DcMYvfgAteKhE0d3bQJKq6ZiVz7A9pk9ke+BEVNOJar+7YG5TjUqe/bL0bR6iUqI/OjBaq3nvXmFb9Oz27Y1/zuFjihyHa8ovHM1ms1Ugx3YNerpWKgvWF/BwWxr2OfdkJh7YRifGB4YCvenp2pj+szaKQBAEr0z8yR88LeM/6VgfNuRmJj4t1zFOWrf+jL73oaxagKRTVLIoU0SQug43hE2EI+I2iQxkpCKumKsOaDwM6WsND/+pCvv+K+iPxK01I9Xf342Ihgk0qxHkssIycSxuFmiEvU07rw1sGolTwOhWQlNQ2HIkLbOYgj1BQlOGEQ5amVz/wxVugqNN4QJPMiXmyV+FZs
    username: AgB/g67pUSsOIO2Of+TQLi34+jmyOEKNfRqrybFN0UQxWyGpPKFHeemrHw1LrGJ7ixehWwy9puZR23a0DIb4eq77oticxnxbPgo6bjQy+xAKALJQHfbTXh9+q7sWAOJPzRqFt17ioTOuuItIZmFio+otv6vXwkniS4DFVO5LEf9uETvoY9NM0LirkICPFIuuHxutbEHLnsKvBcaH0P7AQKD0B5OHYz1Af3udEeCD/u+Ie6r5xE7wPljwuBXa9bJOEB4qP0qgRm0WzYP3eZN+QkaeLwpCw4337O2QcOFFbmM/2dSHMRnUsHuEgD0Ot/I1K68mPd+oEDVwz+t21Ck9ngzWUNYoFsBfzUS9W/oV0Yb+KKxb6Fm8sTc9ZoD3UmLdgGxJ8pkgBMuxx9+Ls4h4zRM4OOpsT9T1efJUgzp0VkAwNHhneoPVGRMO7psYKhN7+DfifSswpAORr0HeX8K4uFtmBpLmdD55wz7T/KSfKQl+EfILKNFVwKftdd+tyJUMMPFbsdYBqSusb7gzv4E9QAV5K7E+aEUxmBzwMREzRp0atIHcndX9Jw9nHrlpY9eETRZt/MO/LQMhZgNfWI4Vw2yDKpU3FAF2g7te2Q1D8nI+F7A42yyC66lG49CDSpWqR7p09tLXt+LYc8BosBY/FEuC+k4jBMJokyQOTnLVVUMd+gZdPlwGTiTJnwO4TqMvyHNFfjTt8u6ggKnsjOg=
  template:
    metadata:
      name: sextant-user-password
      namespace: database
