---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr4k-user-password
  namespace: database
spec:
  encryptedData:
    password: AgBr8vnPl9zS+NzC4c7DZLZwWbm3Cc58+Ocjma7KPaQbgmUu/sNYXr3XM6gjdutPtZgnRam5okaoVwwf0oV65oaYoB7e3c+37i28aLXrS7O/ceE83MxOfcyelQ8k4BujF/4XET/ojGVwqVZCS5mxjOhom0eg+WWbZDjNf9c/qXCDWgDZ19WOy5O+FMa3BeZARjqOyanqn/Lm0ULYEtJ4Oj2RMKmOhglYrk6k0pjrCYRebDhtqkcv0a64fe0G7g1c18qxExHVyVJs+wCWcslXafinJmkvZ/JbxuDmCPTbk6zinh76gf1MrSzFb3Db9VJEVCeRzRdwKsivxdXgg6aBFkORfutjWuS7GADwGTjTBFpMlstt+IG7BkwuZ3ErvrURNb7LreaqPlPs/F5o+kFJef2H3ejyBwAUCBS3DsvpmgjFJee+pnJiKM08K9AoC9QPHRG01qEtafutf+8CpDrcYkbw7W4s6Cil1CMSBvBE0+aHhH5c0ISBkC4mWuIwwyU6WgF9h5/9KnIXi6qSd+64aKWgYDEZ2kk47BWqdJ+y1DjHxdXO3xNVKv+6tO1XV4ZJhR2PpyXcuFUCeTW1v583urjUP9fWGg/NJhcXRDYFfyqeSHn7CRf/TKlNs6lhJsFp86cNolfeNaFo8IhK2rtk8r/bEBrpMmFPs0lMWHEr+ZWR3oLVT+GZVV0BRTe87c5+Tj0ojQ7tZ6QMYYILHpKxGuuDgpWyzmcqxXFcAfvJZp4I8+TK+9N56O+p75lYGw==
  template:
    metadata:
      name: sonarr4k-user-password
      namespace: database
