---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr4k-user-password
  namespace: database
spec:
  encryptedData:
    password: AgBbRw818V506nhfDm5ipyXsp/MH7Wr/gMwxGKPqkjxY1dbDLCZKsgBIzsjnY60OjtHh+HpxcRbNb1a12F8ePe+ZcrojmTaI9pWRkgObn1vZeMEgfCACLC4RoQoQb7y0Jmxp5AplLoxulhvzxHsar6hoKsmbm8tb2bkmJyp7aLwLoj7DbGw8x0lAw1ni9MIWrvlsWD+Ampwrmge28UxdECIqb+zTRzAoAfF8RZPBW9/7EfWFpK6QMnse4KgTjR4MPctMM59t0Kl47CZFo+22fTt6hc/Kl2Y01rLi7qYrQSdLXeCQHUqt+2Le4/G02AqZP8esDdznNa5AmFo3/ORWjKQJn6TG8K2xlbJglGGUS3hoYD53XLUlJwex/VWiZyLTX1PICGFDMxPHW6IgQcEY+A9fOh1aw6BpKQonBcLr7m29gzIIErYiqEUuOhItzLTMryGwgj8U3O7UavWgOSMhDisa+N5dIIDBPb6SzQv1BkuEubqgrSDrGXLxbJ3IKyi07sdG+gkh5WZu6OWfoeUiANI9d2/Rs4zCZz3tqP3mlgdftpAHfigPl3Jfn+J29JgPubwcGpjltmpQDOUOLoYnpxAMzwDLaxxyNQVW/sKUovnFA/MAM/v0+J4pJgjqxgcoMBqohLU2hyqeH1ZdGgGnv1p161iuiGh52c6ZBUNrCgffV1WK/jBcJUzwSZl6NQ9xzH+crHTwTsbPuO3bCJ3ahX0cPFp+jj47u4aTI0IQ/bCNhxLAhyiIe+XkMiW+BQ==
    username: AgBVRivpgJuw+zaxMlrjja4zgplsgpOGzULPw8XZcabD8ay6+RaGJydDi65as93gTtIrffd8LPuGnieDOYpv8SW3mE0bToEMs+niH4+J+RsdsPvhqetMIzQ8Ts9bDUj7kPNUhlCpGhhj5Ed3RWZjbToEGdXzL6mrefezw9pHzUooSN0JNCBDHC0WOqoXNY4z2vWpMDBcpkpX7jRyp4LOBl3inmz61HvGnnp36r67C9ZcnS+5ajmwz/gd7bhlEm7jIEi/mjO/a9afZEmlGZf0ucDl9uquG7rMz72C0td81Dr61RNb677WrBwGE9HLfXFPtxoXwJ7m88b+Pw0vK3Dpmic33g9DokqjCXoYKmkXN2YtIUjrYERyy5A3rdysq/osxg/ZXpqeNqby9oNQ7wk92ltKxLdmXm23FJcKMuHOln+baaB0Pfiqdy1kq1USuRQ6Q8xa7qL2SNWx3dWwHOeQX8MqhEGPXvD3hthTG1xJuxYD31OPF1NIW8S5p1GWF1o/pVI379lodRiFnrr2997+1lyz/I/XfTfg2U6zB/KLHDOFP41ot3VVeNoVPOiW+7NEmWOGUuSiapySqypA5Lr9SVAWOIDCKcHb+MLen8xM37vdKjcJv2fxniPFFNjRCn17P+AYR6/b9ZgUvkw2EkCwqjvCdWDa3ZWa17SQWD6ZGAyuOlrZSETjbYuObePb+Pj68IYSfyi112nxUG3hSxrB
  template:
    metadata:
      name: sonarr4k-user-password
      namespace: database
