---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-user-password
  namespace: database
spec:
  encryptedData:
    password: AgCMLZvH9PBu1WFle7Of08rG7YmmYn2kxuYJrUf6nGEflThChUQf7h9s71NgViNfHiwCSBVrKmRwggs661poCxud3q4xMy5CehW5aR8tPyiqhMab9CEX9Rgr5dvghlhOhSXYtJ/J8VKBK2tNln0Q25bdvS5sYqRXaAqnFReIpI9VATfFWaKFL+Rz1AoZPi8WL9QcXXJNaqkj+8hjrIeONiAGkKK65AWCEbdi1VzZVyt4PJaS4Y923PGJdJkjyGpQMZqJ2xOmzpEiX0N71tB31aeCpKKla0khqLwZManUkkIFxlqivD0x1KXBn9RuFujY4bEaPGDV07GB4gZ681W7m84YhOp6dzJDSflhRG+XLhJA4UsiIJfNnqtYeQ0ZOpyF1tCKrvfOPymOfx5X7ZS1IqmmymGKu7+fuW0M8rCggYSPcNNEA+UBUBXvQfI314ZRXyxN8A83ry6kRq6MDWGxa5tcxerVyJ2gxh/nJhWqSDxUD7uXTaAu5D4Tb+9xLEbdi7EcbDuybnnL8dhyGV5yqFNoG8HjIhAGl+LuIaUCvA0yILmNQ/LG43RzudBaYdLxbXaxQ+9r/+QIRpaq3V7DuQCPkiLxh9fScYCyN6/FlgzRnGi5ez9D42s2Mz5GfTfSG+PiMsfPY33nQ3KRlnGCuGFMRrjfnLzOOt3fbuwmFZQPZoIP2Ul9YrHxICaIhe8Xn8oVfNLJqW5cP+Ja3wqyveyyv8Ul19PF9ObEFWCtq+75VOCD9EfngYhlIZVWGw==
    username: AgBl389OdM4WSO212f0TjTj3Z6tDuZ0tg9rFvtuCTSPQZKBxeG8ImdUnn9kH2KaL+VH64ljeO8i0M7Uc1DDA9Nvl3nMrWxg2IFzikd1Qc+ldAbCa7o3ZDDG5sJ4T0CkA42DpmuOe0EkKvg+0DScaPON3a3cBwihy/N0dCbp23H60uh73XqKls7dfH2iJJ5brDjKHPInJk9JdcQPHE4zMIQ9pMY1FZyQqcMb8+NWgGzMo82hZKTHS2AJp5a2K5LmD1MJiPOA9x3rVxblXFE61V2K9aZQjiC7zmXW2VAQYAagOno8uunRxqTxUqGqcStX0slZ+w/zQde7Ufc3K1osxyUXIhRuIR0ssBcdB39RIUPAcMOAp9DU2HGc3C0VC0H2EQk2CtLdugt6lkX3/P+/gPz+qi5+jfOzJge4kJtLY7kcT8QokMHiW+b6yGAvueZBwhQJECcEMN9mO5PxY8UwF5o+irYGsfFFsL/M+TeWju1Jsb6//r6YCwdii6zrLnhHIDp8t2bfDli8qdekWmIYWzeHIxbWrR3C941GEfdfZLhPfB6u6YI7MZqK+ZlyVo7QQa62/ABp9WkBwZsa6oOV34iuReFkjkUP6WaWKC36jv7kNipQoIMR7p7nF647h0E7aOYyubjkuaywPvOrDy1Skx6XbWQTSK2kupzXAQj8+9IesIjhP2cLtH102hne9kfFr/9shq7EJa7id6ylSag==
  template:
    metadata:
      name: sonarr-user-password
      namespace: database
