---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-user-password
  namespace: database
spec:
  encryptedData:
    password: AgAL7xyn6I+H4YPpY2PZgl3fiTb6Jp5pOXymRg70UwLvHx7JApo1R4H+3EHVvSJHkHsKBRXhtk2jxrfXi0zQ3p3EKAA709T1eg5dChdcRqXpr2MerrAA7uwk5DjQC7NzIMUBjgBYzZLxLf7iJ5ZQ296ZNjyvXKc4ri9p/3Ed3iu6+TbMFvxsEj8lDI7FDTcaqvW2RYjovOFupIIQhdpN/yoTYh5Y9H+tRCirI/VzKy+owXSpL7/zoLdDg/5WA+jiC0uoH97Xlp2ywJwQUUHgxieyc/5bvP8lfj5UMz3HW5KiaKXlZFuohlTmXi97KKGpsZVvRGAuIW/n+UHWNGabLi0U0z0Wnwre2zP73aXP/VTwyd37e3gDsN2wTV0sDx4HiosCBsGTZ0HRIB/Wb/cmqDtYdZhpr83v/8CQTx7REbnEaSFjhnxoOq76U1VsQ11bJYhyOFHjpnny0JzMdBkkiWXtImkW4uJOU+tBtm+OMgMNXdZekLmmisd01UPymY9R87BEz3VLPYlNkunGYihr0EZ0aEZRAOW2KKp9iTB2PpNDDP2/b7kMh4Wf6twzVNol03huW3R028JA+Uj+RB+sYBUyvcpsMoGSUhB1dwKwrFLMV1FK030oMM6gO6YT5lwcxZS9CnYuB6sVH0XKC/mFBOISV8yEqew2R8bgYxNR9l7P0UXnM7u1fT8R28nGbw9O7cT7r7+RtgIS/pyG9SJITolirsnnj6+TPGpzJHehTEyGqwkRZYPbn3YK+ND8Iw==
  template:
    metadata:
      name: sonarr-user-password
      namespace: database
