---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stirling-user-password
  namespace: database
spec:
  encryptedData:
    password: AgCpmvMX4gNLd7aA79JVAtzt6D3TD3WgLkDIYXtTh7LvYuyXJIQ99GFESutyD3Ck1OuQgQiMYKZKEVqoSWgdwIDxifU2pnuPuFBMqQ5CPU4BN+YgZg3oT0XRNfiIDqopQPEM3PqOk+5NPHuUnbyxLqjDedM5hyiZr0aTMydLTF+p9miqzGCdy+oNKei4PlQisgl5cQlECWrczJrQ+ZrKq8/c3t7lBLLwjG2urHt0hLCNJ1K9Qwbj4JYVmVsu+3lfbB5oXUcBgwI3t4n97oW89ZMJgCHUdtkpT+/MVyJDI5BjIM3qxUqIOfGF0xa79wnkWfsa3egfaAcnjBloztvLNGD45GpF9rM6e0HXHeHsS47rDICjeaJAFcpTI3t2ZxKZTKE9JwQb5QL2LhZIW4PANE8Qu9wbsAPj4aU4RvIbA6xwLobKQAgvtsPHba/GMf43dVaX2wxDbuP5BP4yDuMeY1eaUvSZ4wYoZcA4iV/X8+IY+WkXPeruQ8ivvM7dY28/yQSAm3N/syNwU+PMAq+1Bc5Bl56Jn94QANeb4E053XZaUn5yjT+PyWBuPzdq6iSsPLbKWwMvoioDa0Sn2WSS8oTr6pdfs/JXNOjFDOd89IBIw9ls5KQdJBY+WoZWa61GTWEuh/qKCWC47PBWlVhkIil3wgJlAk63b7YNSmPdMsyUMxiKHDgZPiRL65NMdjG/w/cMwu4+upwv+vNWUePiiIF4DdRJH8hMCfHrH498UsIVrO0vGJJOmBXNVpfw6A==
    username: AgBj84YNJQY7FU3PS0J9gImL9xcC4nHpNjeeUrsXVVbelIr6X7CwkWfq43foEsg5OCzlpqy+l+X4ErpTPgx1K0tfcoI6YBnXn7kr47kfgFa4REMnsSXN9JufcPOUQO+qp/pHL40SvFq2T8JGike5nq+F2Nw+RC3wjil5154O9G6L6/+S49tF1zbf8Bm4wwLhKceCuroWDd0XBTXAYD+OWzUgYffv/ZkHDduH3hpQcaNbmqKq98uz/63LjTQa7FJFzfgZfCzYZlYgCeEg4Zk6l/qJeSOztVSCitq++xZ9KI614Bd0gpOLUnjq86MtmZaVdRasvHcDUn6EwT0PBB5bwfBDGFSuWKvY7S9gxeppNBJ07Dn5S/xALzbHeqJ2iZVoU2YizZOd3L6mCNoMP1ppXzujbWzQzbRo7ZSPyhMYcGxqle7QhLeXgEAfCWh67JiOYGu4l/roaENXdVfIWjVSDCvWjkNSMbDlk08IeX0xSrbnApsf4v7h89NlKwVSa0vEH/AKOD7gTqRGQlUErKRgFdS1V13DINL4cJ0et6EGtTmadVD55QLIZ/WThK0fTnc090WkX4x2pnGp2+8WG7DeUnSBCejp9Qf9YuAagPcWecfTrQheU6ndeoKr0GbX+/d9KUx0hB0IJBEsgXe4cHiN/u48SZOTB7DPvyDOvZw4u8VT7mJ3GYyPHTyUzRS3nFqzqq0HUY8dnGX22lhQcRKk
  template:
    metadata:
      name: stirling-user-password
      namespace: database
