---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stirling-user-password
  namespace: database
spec:
  encryptedData:
    password: AgA2LJZfDFCTyFbL4+8AeRn/Izebohes8Xsy7bjYk/Mvew+UgPxD6SZl7kcVklpc1c0vNTpvSgkv0l4OKwL4gb2d1iSZ6w5A0J3ktDk/1EFjjkl5jg94Lsm/BZ/egrXyWBjuNAaoGgGUN2LurxEz5Zm381wUv1FJwwXkNH9MEhCJ7/4CfX1v6i1gUDQYdNhccDH7ZpJ4FYJwF50gscKRUvQtk5+VUdMwsOyecGeAl4xrEUUD7KV1nvvodcwbCqGCRcl4LtkV5gcd7Xn/eoc3P2x1WXQZRdJVKeRLII4OXjPK+LeynCCf1kC72EmflJsG8CtzhazErHZcl61rU6JX6fIauJQWJM2LOIzpiQYZbyqz4iKpwkfybp68lumP5FqAgNaBp1sbIKS+OCsvhZXFRcSy9N+52Lcb2/ZjEnNraTqMkPWGUgDFuQq9qM5VkGsvr2kT91jnZ7IhXn9QRERoV0y7CZh4PoLaIoAR0ggxveHW9YbaFH674Zs82FyMXycbdqZdjcLlWRipsS6z9aKQUHjxeD/svWIC0N4N62hyEKIl8CmSpEiWJmPhUf6jgoXTZsgtCC6h6um5/JDD0s4J2Nw+h8VWpLY8tTSYRpxua4GF+gPSdT6Thue+M/z1Eu16FArUse4J7SCADpaxYMx7cxcu9P+q2HTlu38nm3pwEQgvI+xDDNaU82oXd2gST+Tt2CkX36VD3SkKrcMxkDnflppX65arxDsonWfRSj12DzTTCOk25AzhCAp8ci8CKA==
  template:
    metadata:
      name: stirling-user-password
      namespace: database
