---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-user-password
  namespace: database
spec:
  encryptedData:
    password: AgBcHoz033tiXbAHatZJaRMyAhoDTph4mnOf/kjjLjhFXlGebJPCYycRtYL5srP3LqX2+w9WUsCohxcz/1DwtahlnKRSVt2taf+92hTHhQVBI/GZhjUcJYq7xzb67V2IYu4uDCh+bOa92Ns+E7FLVb24F7VCrwNJbXeocBq8V8CTZhCvh+s5ezmgf74s3wN6YeiH9AVmoxk/yUNzBEv+w8du//hEWxuxlVRVWhjF4x0Jhxa5MHygNdyO00AAYj7kn9gAY/MgEf33otLCPb42QGh8ZSqGAkZKMUvLuuhndtBIDVyUbyEhJwdhXXxdEs18j/0a0GYZbx5cO4YnqN4Y39INYmCcZ4dwwvgDkbL2n+FpQrvUpUIgTi+5DpvArgikd0Ll8oOpSfs5F+d/ufcePtFXPFDC7E5NbFSLNGEXilia0oiyptGBBOKTZnT/f1WfhzuYaQ+6FcyIK86RMDgWkqcoXXgTItlwes1aEYlZN7DHUk8wUFmMDMXu3NOx+P3jxp6hKcRf1sgDXetuxjavRd00iKLWr7PIbbviVW35aTb7uMu2rZeP6LYLky8sJrSzo6Fqi5x4qNgLWwYctnxr/yZwEAmMusjHeX+a2kWpyIYitq0C8ZPWwS+gGxmKk0oyznxDfVwEcV3tGvHdrKAmRCeZFKJdFFgXApfUQ5v+ZrsaOixbWk+LgWw9Y4qopurUrZIrordJ5JTfg6aTDTNmvU54dIzJfx/qmUM=
    username: AgAOLtWA6xcZNBvtgx1URPFpGEB3oa2e8VZdRnaWRh6YQNqH/Vnd4YAzJSDchUnXagUnG83i3l67QlJJ8Mb0XnPMw0mMoibiUoL2qohJjL2JqtwF8GgQLknARDmgjcoPhzqczjxO8+PloghA0a1zFG60Kv16+yBN1FN6fKNgFU9H9sCKmmZwUyMQx+TTVyJS048W8T7FOXxJiB8zjfAuihOPIYkf/jZ0FbR2dTbb5o9HGE4Sl0GJQEYeFA2Iz1YMtorKKfmuBDg786nN6q/fgXc0msjYoSh5acdxKvNssj2Tiz2mEdN1VUq4fexY7Jorq+5ylY4c2VC64D2j84YNSVftj0GtW6kDWpEDKryYqMfJWy8OtLNIxlJ2Jhms5JJgGBeQ8p6ccB688tNyGRVXb+4kad99oi8bVQk6lh4rIgvGRdA3htHf9cu8mRLKNtlA3wFCEryN/6OqrnLH9euMoJ/njc5NDi9RjgNFcyOQwzEjzZRtBFzTp3i3sdazit26xmMP/QAIm4C/XaYk+JotTVXHFvjO74HfOOVd/7Tu5F4jmPN/tZ86EBftIs/5GxJk/y401P1r9PQo2E18oNsuKv+SUdjn5GKuwHqDM4xeq4x1pYIUjnGyQyvhwvD8xC9kS8Rht6m9BFyrFtlLYcSWiSXMf0wcLDLxE/VIRVim7dBlc7tDmJITaEGxcuAuU67USFQuOiEhRvumH1vUuJVu2Oyf
  template:
    metadata:
      name: vaultwarden-user-password
      namespace: database
    type: Opaque
