---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-user-password
  namespace: database
spec:
  encryptedData:
    password: AgBUiUV79LXKN4NkkhE3r1rtHBeQN14JkII2GIY7vnhJCTT25Qg09ya9fg3BxQRHq0dha1Y/3b50wlXe3Cr8nIaE//VdzrkIURQBbyeayJyOMGXlnJtTdOa+g3iO7AfA4MzijmNgJpKfl6nKY2K8kAHBYN03i9SZOgbugZEDQxv6K7QICSs3EjRQAoxKkmvLkpRx5ic/0kaciqH2pURh+GOXO5VS8Ku7Ex4gpYeQexVs8dZZ9glHNH7tL3WB91Iszlu7sBGt+IuWFNLXJI1vL1HA9Gb9Oj+VU2lI3OSk7TcGPAmaBpd3l7tvI2LOdB5jyyxpRNMk8YIpxK13NCjsVrZzuzLWXUct/hXn0A+5Q0eFCjTTo96gAlX4aUPqhWwW1thNB4kkH/yGiICQGPAVBsjwEy7RgUot7tMTC6C7nkPohxET2y95Ny63Xn7nMuJEwdBVQFeJqecOKKqVjjCyjWzuQkWTbw/Q9p+wtGOTeKN4Xp3DZF48ok1poufTO7z+y68e+Xh9JUNCX8E4FNK+dMrAtXGV3GTxzUpaTtA184DaTrVnohOzWW7jIRnWYxZZOdYwh5faT+RPhbsmB7Mm85MXqta0r+7skw3Rs2KtBRd3iDLQmePaUsac5goyf7nQV3jvhwuviykfZHNXZnWjdaSp+XbUGP2kDn7RBwUg755jJ7OpX68/n1OJygItNYyXgv+dObil3n4g0TCaO2HrcWpdUCdHpDvBTD4kiBpmRKc7bMy80Q2QOjTjGSz+rA==
    username: AgAtHrBAjAov/gU/zzdegFo7m7njEw+srU1fk+K/ByAONt4LhCoQd210s2GeM2jE3MkKeAyPWpM+M7S0hbYZHMzLFL/t6LxDcA1wK2GWBquVvGUWANVZxjeoRXZZ5+s5Tw9nAr1fvDiiSoLbkC+dRR942Ucl4O7NHaGrFv8NWxhS30dhxXI2cQVnf56fXUvdrmSRAuwLjhaQHshuvXS5KGcw20QmU0ant3xIaYhLhX5nup4KAQZmH7swWkoCKqO0+G3xWvEIyyPz4w70BUngF2pENmmD1vlmAh4pA1MlivZ9qQt39+E6T6tcDU3NZZXIDU6JLpaleeI+14lcoVDDC4zhUvRQuKgP3yGnnBZr7TeJS/oY72tWvuCXyKEQ9KbFkU+DW3aR72+mY0g8ZEYFCdqjmW4tXulp+9QC/EK3v4roe/4IY9rfIeOvt33Ffo6rx8pjvNSZBdgUyMeaq9VfcrLcwf+yXVHyGTsg8L82+JuaB+2HA0JIGUeVK6os3/jMj/YW5mrVVB776CzXm/hLn0NAnMjsmZqxCAjs2kJq6tH+GYdFs7pxGknA04rh8FfvMo0RJQ3m7mFSvniIac+KKckQJKSljc7mkeyzQC+yn60E/v3YOeEYrsjJoy3XArQQn5ZA3n7lPnD0BlaW00T9r9rwsqhF/oVKcN/7gyEBjRwAnFqmGOPt1CwkeH5zOSHlaeWvvCL2/9OGN+HH0TsSbdmN
  template:
    metadata:
      name: vaultwarden-user-password
      namespace: database
