---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-user-password
  namespace: database
spec:
  encryptedData:
    password: AgAXlE6ktPCNpRp4cTRwKrhSQYM/U/3uLXW9CHNj6SIz0DMA+ml+I3ozT47m9/tJOsSdYs1KCNJ5udzIfk2ZkbnI+lrGtzCI+O7Ky5SgLjJ98oz2PmnivMq71WHn2qeHVScJrcWaxeqQo32VA0R69sQ3WBE3xXFIalSi/+u1JUPm4PTr+/mnjlC5i0r2mw51vEtaPTVO3DIghy2oioLQCvsgS+QYafgt1Xy4PBMGsWGJRvCRf0QA5t8ggPQDx9VYqSdHAV/nlXbrdKdqElhhNeZswCy03cGQCC9IQ/EUWcXQctdh7xnnXSqrGRvLLaprHQJerARJJwn+De859mAqR+kITH9UFE4s0YV+XAJjwrSYqGpg57dphpChZnnpZjWfjFMcD0q2M1EZaHoNyJMcCqvT8ArBklxpWPXYo0X9dTIUifYzqHiuuH0jT/4Cd/790+qsl4f2C5vBEb/oxNCTIfshgk9cs83b+t9nLJl5qkmIJAIJvU8tW0ziSkJ5R2yPNACGMSWWk39sZauOLHeJncBixm+oinmGhuXtmqTe/2vCuEpSxpUQVwtLAGWWoH/y/B19tTIUG6hqea94wcZgqGXyF0Z6Yoo7ap47m0JkKtMoNP9VAyKp7WjVjy3jYpJqnux4dcpWab92AGBZyOA6jgVPcMc1FTj2xhS1rIK6+GTKl/2b8EqLjMg1Nt1toXFFwjXr0Z8vMJvqZhLkhefYRBOwvf9rew3F7bE=
    username: AgCuqvd4phC7UE7W3RvVAmsXn3j/KHObdsvM82MlDJwIn6vHTMQSqqbFcxVx3yWsj+srj8pk4EAMrZi0+GipFetkFrV/lWT95tkp+ZTxcfM4wm+M8RJMWO6W2X8ZXI1f7ldhoOh/WYJdUkUNY7iCDF557RB5ZnSyggFNwe0974g6/up6ScMKY6C8eKKxAEt0P8AVP2013S16CaN+mYXfMuoCqEtkE0Drci2jMjnXgrm0eZNBggObEKa28l2ix9bx0Tv1YVD9tUKhiNVUB+E8C6dZkZKrbWWCddwXvzBR01um5GvFaBCfoD0UtVrICpT02MUfRMtCG5YZcXOUn0XphIE6Ln229u6SLiLKjomxgJIGS46ejlQPc70a6eHrLLlt2AWkB7wO2cU5ULaX51x0z6zmHPkmNvVA1r4lx8TUVcEewjKzBndk1TtqzoGH6aMPyLozYW3Qodxrey+ZB0AQru5KgKA2xqqe1v/yRnKP3ODkvamKC8zhPW8QHQSWjMF4izA1r7sulZa4KSAgBmLO40Ts/EoTQopG55AMEVPYEUpHGxmzlktCwDg7zUnUdu0A1toAfOKXKIpXTP5kKIiQpVFYcL+b6/KGHnLcUkRNUbxEPeAQaSHESGNdbgF4St3zqYNM8N7G16hWYY1PHWlozWbB3dFjmQXnnCYSso8iBxjnka7lcyeL6acvmpI1u7Nuv2gLVBBdtq2Co60m5iCuGq26
  template:
    metadata:
      name: vaultwarden-user-password
      namespace: database
