---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCRa6S1UWkSK41mMq4XKXLs8g5eD8g/m1NWJi+/H3SflMuG3fatqxzBMMPWslEtPwxt+Cu5nHduT423cFGTa4H4r+3h/hxlEn+h/N96UJVJf16QJlqhMDZhKnYA/3wOCnruHbU+LQnYFFOnWki8QPwSamwHxvo0eGCjityve4BdWQ/V8FxZBLvLXflsFXA+2NzfrEvDMDltEgIJS7eV/vryC97HgjQf5AbX46gvtnAX+06nEDvJQfRLec+/ZhX6DDVxKhHvAB6G8ZJNDLS24i0lkTc3wJxIkd6nzBg/SEAyB5arYfIby19N3AAAFdcBoRy4ftp8WpMt50X+nvGL/0UKbKnL8YVrnzAn2CBwWhuuHRI5iF3ZcZ1QKg3GiswuYStzDkekmtNTl6hBooJ6d40uzXGaN0ZkPe+sy8+RKkhazMzBFa7G455g6kuoVoyaAJ6juW9AUrrOzwSXuyPcrtnJtltdBhCt9QJInhSydyjlrVkWbuJoe4xboADHM801RNpGSUtOvia9A0WcNpAQAIeWMlDzO8YFVymR02/3QqvKybrV4Q5h0+2RVEY/AZmvJ1VfJ4lBxJZ+K0dXM/rTb4PSk27/bhy8bI04WQEE5oyBpV86ZNMSO0pCouI4ExF2NZO7HGuUHLjmljJWPQV7fZ7G8m6QHRdC7bBsRB1EnYksAsrhdp4jJGMeauxNm6Cp4fwx4g+ibAD295WFdcQLRD9y37Kv/yJKSDLJRFOT9bFNCr4d4T6Lk77oKSuk1R5uydircb0f9GeK1WAAzed2mU2enFMsrDmURc9N3llah/XkIj77S/Le40SjJYUeY9BCoPFiWKhEIIkq
  template:
    metadata:
      name: velero-credentials
      namespace: velero
