---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBNH3Y4GVAFiAmuu91y0WPf1FpRDEC/BFhrv4jwR4Hv9jaQ6FvLqAOVyBuQa7jrbFq5Fu5vdi8FqXftX2w9fZJw7UNiB+DKB32QnPCVQHfvMMccklfPhU3BIES8LZHOhIrRzwEdWHJN2KgrfDgC/mTKIE6a/UOeB2Wz0+ZiBkZY1hv/FqwTEBIejb0YQnuREqY9LBppzqL8QBhnznj1jD8j24xOTmMrHzA3iiITvj0Y0uQ3os8vMC5i42ETAcgbtMhdgdXc2YZLzd+y0DpNjvMw7f93L1CQd9U5oJOdkmvF0+Do0i6y9WAUAk5Ap+jhlSeQdzG7lahMZL8mf1082jzCkbHDjKvM8XttfuQk3/aZ0k0ED5sxFMa0EjU/7zpKoJbUlCiGhF8E8wzJeUVydazJ1y5jvjUkblELUdCleRpHxQt7xCHrKsz6Xke17lEWqa/qENYMdHAu5sp0O+zHt3VqZ4sSddVqHjQpAY76ZpHu9A+ORnHxTtnfAQyj0c18YLCILcTSQNb7L0BLQiW43IeSEUqBJnKYTuKgHlnhwd015mWzZdA9h8M2JBwpw3DREHNpJCWDONOmAsTsiQKXnec11wdFAQ2+xjsruS3CjL7UHjl897MpQX6iWtzayyc8fzgy7NcrW/CnfWRqBLb6moh+l9sWGBx/C6vrmbkfAYo7wmCEWtuz3xT93/F3nFFbgNzGkg+cXiRLs3ZfkUyuM4pBUDycKuYCEf7pRnEB9N4E+q8J4X5MUlMQ+wTJGGe3v72xZ21dN0bv2lW2U4MjNNFxz8GkNavGqkmH9h6hXg70X9bnzqRX7W2GqkjM6ik7O9JwgEKXF+TfWEH+RBqD/3LiqLeJQ05r7/XmwUVwTgUDinn0bG1tPPzV8wSSGx7U
  template:
    metadata:
      name: velero-credentials
      namespace: velero
