apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: searxng
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
      enableServiceLinks: false
      containers:
        - name: searxng
          image: searxng/searxng:latest@sha256:6ba4dc74513d1e3da2bde4a6c419a8c4a0ec3475ada97d9637d8f5a75ec8b595
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: settings-cm
              mountPath: /etc/searxng/settings.yml
              subPath: settings.yml
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: settings-cm
          configMap:
            name: searxng-settings
