apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: searxng
  namespace: searxng
  annotations:
    argocd.argoproj.io/sync-wave: 3
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      middlewares:
        - name: nc-maintenance-maintenance-errors
          namespace: nc-maintenance
      match: Host(`search.k8s.hu.ls`) && ClientIP(`192.168.1.235`)
      priority: 20
      services:
        - name: searxng
          port: 8080
    - kind: Rule
      middlewares:
        - name: nc-maintenance-maintenance-errors
          namespace: nc-maintenance
        - name: authentik
          namespace: authentik
      match: Host(`search.k8s.hu.ls`)
      priority: 10
      services:
        - name: searxng
          port: 8080
  tls:
    secretName: wildcard-k8s-hu-ls-tls