---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDesbV/SjOQmfgru1ez3LU0ncrDkt9845FbFvRzXw8/pAxkHMsyiIdQ+uwdTGF/QdDg3W9IPhYKXGNrrQQDkQKVRnbrrLIPoAVCT/TA1fwWNCNEsa7i6XWbqPeFo4EUkm1vlfPHDDgY9tG1sVzU+yNsxEpjQ/a99I/Y4haDpFOAMwYYzV1nSy0KPlRQ7iIIU+9HG9tuP8dmPmI4HMmSrXKfnYu4tSOUIy8eCTKfVeE17SvgB1If1eiuKwuT2zG8l2jYA2/emebb1Fvn+8pc9h+5nkWcEcWFXftf8RxBay3biQbNcZtzny9rHTX4EzDDegzzfN1AivQDCdBWauY6xKlcb+AOIgzwWFeILPMYu4pQVPV8QcilRKmQZypK83sz1a1NpHs6OGDvbisZGaUxh2FE1aZJa2KFeqc4E8kpdUZiHK0lpoBB0wCVHGb4j0PYNdLeOeI9smzvNQev2lbUTl5zorDUW+xzzJh9U3R7+S2l+I48Gl1pDZngq27FoWfzV8YJTwweW6D5ENA6zvHvF7Zj59/mcZqxHQ31kJvQoKP5ZBDhJCZSDpLDWSbNT7p1HnDleqmiX5OYhbLxFfUBUx/NtauPh+xvLv1KyglPDD1nmLcZh60P0P9tQE1yfnAnenhA0pjiCv/X3eVrMPGOgSPsc0+yE5rnru9dukplgwat8hv1KV8a+WiC++kEkP8YhqmYB25a9fif7Ll6BES9
    admin-user: AgAl8hCnpsVf1XTvuWNM2Qo1CMvQiXAFW7Drgdcng+KlSvOTQS3qY5v+bAopO3sr4wq+JEtMxfmy9P4eNPdl0gtK4Vkoj53/WwmYmDJ9R7cdI5Ldqbzfk+XJ4ThMhnE2Ypg2FImXlNcB5sUZXbY3hf8c2+N7i1FGPR8yid7kg8lj4vjmMsR03CEXzZ5StjjZe5brUBAoksNL+JvMIvPnmwIv/RLyExpwA9XRpop2NgczNV7NGgk/55wrmofcy5l3uLFHorS1cmaVHefSEEEpi4vBqvgq5hD8wky5SDXjGg/T9UQw12zRnzlIuK9qR56xCMff5ZshP5szjYXDlyuR4GU1GS0+3uusbjNg/xdgnptv+s78buLzuJqaxnyu0R+ORnKSrTG1f+jC4qsWb92f/a+TSlrJUegdTHeCOYXUsuApznejEFJvTOJAAeuxmejqip9ieZm14etI6WYuOzy9SamHkm306OEhFmx08DlGoJX43J+6G8H6cZhp1EuKNiViwUxG3eFPPkDcvLyvRE0c49uC7LqA9AnQJfHQqgbbCUmQU3PAMiUjkxafcs3MRJ+OvT0z3Fwh093LUyUvtegi0xiK22jHz/yuIyF+DTC5qWUozoUSRzmP9oo0VCvH4uZlIwy/XpnJwNTfF6NZwZpWSJOoMBsIlqTHBYWalyn9oMxDdTo2rLrhDv3U7KvHO+/KWsApjaUiVw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
