---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-db
  namespace: monitoring
spec:
  encryptedData:
    password: AgA1TuvnvS0y/Phg0S5mfJMb7ubTHYN+g4A+vTszYxUFGXRWkDxHe0KyQZUI7HVbVLW0V00K4i4BBu35MbNn+GgNjbyn0YjygrijgIP2+qZ+0sB9xLUpCMykFZiIlq3mnXeNyExoMv1pfwwo2SQmtVOU0PpHu4NrjoaWvRv7YAEIsrdP/B+paaS++4oVtaDfSwjmww4muwMy7lh3oORM6oz9LkmAQwUdydja2G11Hi1S3rgDr27w+KytG0QFjQ16uurzXUz113ekNCajbbagpdHrvmFxC4d8YcKZHvtOrYQdcGqm0cLJXSuTGGNZ61SW8xo2CvSuHD/XKQpyYDN4avXFbnK8jQ/dLROpNF/yeFm6EYTsHYwqBJPeEZem/mpwva6ijeqIFO/ch0WgADHChPvUQFXjJ49peeV48Zf7h0Ntjn9BaP7jI7lZRtqdrk1JIXtc7pnLsOIslUxI1EkgJtUj43g1/oWvyXP4N6ixiIk81JxfIDbM1Sm6gz2ZMbF41welyB4v9b9WmrOZvF71WMFVSW0BqSzRRNe8/ti9MDVsgOL+nIl0wuFLV5Yr518tIgxRCg/bmM8K6qANv/BGSxdk5t4G5kIUnWX1u2YsRyOegRVxlJtj6Afo1pVer0F0xoXDiYL0/5lhkTFv30x4t5iZPU6tDV11ZgjooZiomSALE8o93Bad3YvvRdkrR9KoYyjDsD54E0ba72w6uVoMeq0N3M8WierE0SPOIyt2V3wY21kENhhfRkJQFJ3cAQ==
  template:
    metadata:
      name: grafana-db
      namespace: monitoring
