apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    labels:
      app: ha-metrics
    name: ha-metrics
    namespace: monitoring
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    - IPv6
    ipFamilyPolicy: RequireDualStack
    ports:
    - name: metrics
      port: 8123
      protocol: TCP
      targetPort: 8123
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations: {}
    labels:
      app: ha-metrics
    name: ha-metrics
    namespace: monitoring
  subsets:
  - addresses:
    - ip: 192.168.1.230
    ports:
    - name: metrics
      port: 8123
      protocol: TCP
kind: List
metadata: {}
