apiVersion: v1
data:
  bearerToken: Kioq
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"bearerToken":"Kioq"},"kind":"Secret","metadata":{"annotations":{},"name":"ha-prometheus-token","namespace":"monitoring"}}
  creationTimestamp: "2026-05-20T17:11:17Z"
  name: ha-prometheus-token
  namespace: monitoring
  resourceVersion: "8101118"
  uid: 54f1d38f-6e1c-476b-8375-f51394b51af0
type: Opaque
