apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations: {}
  labels:
    release: kube-prometheus-stack
  name: frigate
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    path: /api/metrics
    port: http
  namespaceSelector:
    matchNames:
    - frigate
  selector:
    matchLabels:
      app: frigate
