apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"release":"kube-prometheus-stack"},"name":"home-assistant","namespace":"monitoring"},"spec":{"endpoints":[{"bearerTokenSecret":{"key":"bearerToken","name":"ha-prometheus-token"},"interval":"60s","path":"/api/prometheus","port":"metrics"}],"selector":{"matchLabels":{"app":"ha-metrics"}}}}
  creationTimestamp: "2026-05-20T17:11:36Z"
  generation: 1
  labels:
    release: kube-prometheus-stack
  name: home-assistant
  namespace: monitoring
  resourceVersion: "8101193"
  uid: e739fe36-41bf-40ed-8f2f-2cbc579529d6
spec:
  endpoints:
  - bearerTokenSecret:
      key: bearerToken
      name: ha-prometheus-token
    interval: 60s
    path: /api/prometheus
    port: metrics
  selector:
    matchLabels:
      app: ha-metrics
