apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations: {}
  labels:
    release: kube-prometheus-stack
  name: cert-manager
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: tcp-prometheus-servicemonitor
  namespaceSelector:
    matchNames:
    - cert-manager
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
