apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations: {}
  labels:
    release: kube-prometheus-stack
  name: exportarr
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - media
  selector:
    matchLabels:
      app.kubernetes.io/name: exportarr
