---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocis-ldap-bind
  namespace: ocis
spec:
  encryptedData:
    reva-ldap-bind-password: AgCgOsRKexHp236+XK59tkKne6PW5YyT5UPtrTCjLRjHy9iDtcWxFSlkkWEbVL28LVGsngJZrygMVoeHj+KkiV+vq1HpDrh3yEdrAkWYPuZKSuCyh0DSsIWiEJsmve07p62ENGJttiG4qHckGLMS3NqDj2l3xgvE5T7tEnfjAKOkx6NHPQr28VZiXfZbpqrontQQkTf0OnjQNsUTg7RXNm9K/wqJIwAMAPDFxHC+aCaJnnNQTXSEQlaUnHUCVZ/P0Mbj8YRrff4bIabq5LoqJ2VwIYWlzd6FC8XhX1jm2ruA63afuhysMr71OvMGO2fAa8foYgHEdD+1AxMEym1XyX20adH6T+B//c7OZCKk5ydV9ejEbNIeOJ2Xf/Pt0DkoToPmQJniqWa0oCykCaVs2NcV/ROpTLYV70RbYxr0ZGbJqmyZLSdOshGFq8lr+qogzQG6sQ1W0JM9nHQxnSU0i7OuIZpphCEigdCs9hT4jmMAMeta/7xuGMd4GsGsgSU6YYkOWUU3XF4dRGlLWb8vn1m0cLKfglT0obveXSGp9idfmdzNaZGyROj24ZFRbgPBJfqDZw+XCZtcJXm7UPSxxHsykjNqXB5lfEIP/EaecK4psO7lXc4ZTZnmFqOqP7PmEUX/BMJrmMZNuYuXCDASehk0yjGhSv/b6PJQuojpA4ZhbWS51rYbc/mNzNkhOO7eqbb0NOZC9/aJq1r5sQtGjOP4haP/ejQAQ/O/gIxiDB7fzA4bbq+jIxbYUKMJ
  template:
    metadata:
      name: ocis-ldap-bind
      namespace: ocis
    type: Opaque
