---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ocis-ldap-bind
  namespace: ocis
spec:
  encryptedData:
    reva-ldap-bind-password: AgBCCMke4O4UepS4ggF4QMb6f18DhBtjohnuoMxEjA0CK1zTmcTVjQsgqGU9P5kBGIanI39+GRJqWq3NvTluBs9UcOGrax4r8/Ywbs9Bw91TS4gowror/xTrG6qb2E5pY02wuHEZpoTMPIHEZoMX0yVPodLKHtbnYpRRVOr/SDy8Tj6FW/mRtYXzTqrw515K3w22Sf7jxuHfIKyPmXIJERAsSRz57d/+vfqVnN1T0IIipI3ExJeTneC5Apr0Sj7lvBj0C5SM8mhnzOq9OqCovuHHiX54DoxxphQViTR1gF9tae6ItsjLB73cUBVmOZFbsMoMpJWMwfRrOtx5N8FSU6c0qV4yxHG6DAnrzG3lh6jrAgZXjy4azPKbmVv6SMnlyBrkNEvc4U0Eno13ODGU35gYjSweOOrrYpb0m8R3sAZknFlj/+wVleox0vRf4/9iIR96Ptg0MIMP/6ZWZwhTqOLnBbZe2tPeWOu752B2iMHTIrH0easvtVzxBDt6v1SfP4SeWH7riA62UtVUCuYZJHiwoeyA2cilhcJ7TIXQDAOq3L6xAPhIEUL4Ymvklig5PmWbHTvsccx54r4ay1Ipl0fWLxBtlBtPDI65w5ctDxULj3P2k1iXOkmPvE/k1C2E9Gvf0inMIX5dC52bVLX6pMgHu8NErGI7EwM0pRWvfB2jjcHI5wc+FWEpi3LM1oCmJTxiBdq1eBtwsiGHGyg3vfwUh7rOu8chz+mrDqJvKCOcTFIhs3ENxY+4kq4UiSfMDzE=
  template:
    metadata:
      name: ocis-ldap-bind
      namespace: ocis
