apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-shelfmark-books
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-shelfmark-books
  mountOptions:
    - nfsvers=4.1
    - hard
    - intr
    - rsize=1048576
    - wsize=1048576
  nfs:
    server: 192.168.1.192
    path: /mnt/HDD_ZFS/nas_backup/data/books