apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data
  namespace: frigate
  annotations:
    argocd.argoproj.io/sync-options: SkipHealthCheck=true
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
