apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: sextant-user
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  cluster:
    name: postgres-shared
  name: sextant_user
  ensure: present
  login: true
  inherit: true
  connectionLimit: -1
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: sextant-user-password
