apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-k8s-hu-ls
  namespace: wireguard
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretName: wildcard-k8s-hu-ls-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.k8s.hu.ls"
    - "k8s.hu.ls"
