apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wyoming
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ApexAlpha/k8s-cluster
    targetRevision: main
    path: homelab/wyoming
  destination:
    server: https://kubernetes.default.svc
    namespace: wyoming
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
