apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-data
  namespace: wyoming
  annotations:
    argocd.argoproj.io/sync-options: SkipHealthCheck=true
    argocd.argoproj.io/sync-wave: "25"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piper-data
  namespace: wyoming
  annotations:
    argocd.argoproj.io/sync-options: SkipHealthCheck=true
    argocd.argoproj.io/sync-wave: "25"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
