apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ApexAlpha/k8s-cluster.git
    targetRevision: main
    path: homelab/seaweedfs/config
  destination:
    server: https://kubernetes.default.svc
    namespace: seaweedfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
