---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bazarr-db-credentials
  namespace: media
spec:
  encryptedData:
    password: AgBAtQHorQHkGWe4PNlJRHEsVwSNyulpCLZbjEQOE8Y7o0HyVrfC1aCBCZ5+93LdIUV4gZOwFeHVXg/sYZCPZS4Fb6vW8hqQ3bYStp4HJqj72wxWABgxC1lqM3RcuOjAKZOQ81+TDRGIwMJMSqFkGhtRTBx1Bu7EmW+FbL7SOtjaLldWXcUGfoKrAWmZKMT1e7bAfL1XnajSm7ctimSM+/Be4oxG3pyTMVNoVJ4Z5th6oa0dWfSiITrCHn0/Rc4SeTf1vNKvdxIPzNqcHmPnTLmsN7UFZoQtwkW5jhWPbieK27PEi7IkkVwc8lzskkjXL2RUkfzLoxCPrZZ9pRPcf4mgu/4xxLqPHr1ePt2wo6cOBXgByo60p9dsjUidPz8ctrTUsXVl7PdN3TXtMItYRe2kowzKwmEsvykIwZtrqv3H8WVSOCRy/Dtv8aeeo5nk0YzQ6VwwPn8Xfpg+7hy/n1v9m56/YHP9bzIeS2w9lKAsYOEwdUq0Hn1/7uC6C3YhzSvPFrd0zjGnpWbA99cVshFSZ/2qrUwxf60c/LQDxJJMgk5KdqwP41YIUmDpGYx10fQvWqu2WRiiVE43uwdP9SI581jz6upLE1Fh1WEnJ0sKhbY4e6q5znnN0FhSh3A6i6LzKiW4qSnszAy42pyItmYvDEl1jeBsE+g9hcSnHauI504q2uzGe1I3r09vvruaHtrlgGr11IFcXvqABJZgG2BJCW7PN+7SCfVFjO6JU4k8spW/yJpb4zP++04ctA==
  template:
    metadata:
      name: bazarr-db-credentials
      namespace: media
