---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bazarr-db-credentials
  namespace: media
spec:
  encryptedData:
    password: AgA6feMe0zvpaJFaNBYR34LcTR8fdZYPuJ5dtyvsqhtiNJ+ToNAEKmbS0FmjQEyBaheRdtRbNFSES+ysKaAwJb6KEmADTs5DF4+0dIiuR+bSbWw/3gO8WLOuTE81HWyagtf04Zanm3MRZINdgQj1rqRDGCaIb3rmEv7fj4tdW3glx8MZFceFRSwL1GawLuvVW/TdYGZT3LlyPkt2MNqx1O0trzDDARCMOksfGoSY1c+0Tq5dZ0cqJSr/CaTEV8+A3sDtzSHN48ZzcueE8E1IRx4sW/Phb8EO9+67Ly98OO4DPV8EccXgg36i3grBlH9kGgAQVFIhCITZw/Mklo/cuJc73OTKO4+4h+bSbo35kU3Gmiv1/+ZJYCppM2SAWF5mLom95zkRbdizxksC4v2m4hvxN9RUVqZprdSmghht+pP/JkoV2bZJnh0AnaKEtckGc5CNIccNqHlYKD4kv0UYSE7Mwr85HO1Em+E4oELcr8Z/pTgOrZjpN3UdwpPpZs23PLzIo8hwuCAFJolyI5Pb69YzFKOPslTGcFgkYtpjfhoPdIlRG8TupMqenVizjyqelfINRvLfisixH3YRYr5W50pnkgK6v4FUm2q7rKRxiE2CEpPINaeiH4YG8G1jw8ZQiFnRIAlVy352sCR7ysuc+KGuTr/qa5TeBDVuASIQK+nxl0o6EiRtQWOZ2tTKh1mJkU9BbDSqwfRb/eNwgLAwr4i7IUquaQWxj+rQUmhLD1kS3VNLmFvKv4LU3cPGh7EMrfq3ZhlIm6Dpna/NTHWsMT/I
  template:
    metadata:
      name: bazarr-db-credentials
      namespace: media
