apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nfs.yaml
  - transmission.yaml
  - qbittorrent.yaml
  - prowlarr.yaml
  - sonarr.yaml
  - sonarr-4k.yaml
  - radarr.yaml
  - radarr-4k.yaml
  - bazarr.yaml
  - bazarr-db-credentials-sealed.yaml
  - prowlarr-db-credentials-sealed.yaml
  - radarr-4k-db-credentials-sealed.yaml
  - radarr-db-credentials-sealed.yaml
  - sonarr-4k-db-credentials-sealed.yaml
  - sonarr-db-credentials-sealed.yaml
