---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowlarr-db-credentials
  namespace: media
spec:
  encryptedData:
    password: AgABUtBmzwDtYQr57U7JyuCPjCBFFcsbCufbzqhY020wy14TVjxWJBbhX/UPBMgPakDTlrWb9KwKOZ+05wNl+WNIRpQRwsDkbdWyF6KzNPBKTGMnaGNIJm4lb2deadc8STRWGuTfEoY88kiuA0mbzeVJa62m76lgA4h2xBXf2WjtCERugSHYn3Krf9ECJnGnP+v5l4RszxVTfBsW686guE/eTxPiMxm1oI/RnI2svjVUmN4E8MoPY2gjz2LwNibtW9xhvplZnoFYGpw5eiI4xxlq8qOd3H64IgSYBqbSxtobjwSgDd3pGoyZP2wEfabUdVen2xL1l/zXwk7K5b9kDN1rz1sEsZlPxQU8p1Tvfatm8HFWfnkgxk35vz+QXOcyRJMfVsgvVPqn+cUng+vEizBccL7vb6czdYE1M2vs2PnT4rS7oGlujpw+WwsTBdPImX51OXlOP0vu7g0tSw/cCNMgCvDqwr+Fhya9Qzi9Gi4+qxwH27QHgeKrr3dnGZ8im8Rtuaapo6Ez6inr/J12473BheLlYGZbs9PTQtNIHDA+8b6yYVj/zJrPBAygsJGt2uwk2hohNUqDSyVcj0N7Rs8KA4xm+/qyVUgme6T0QCgzxwHUnm0Ua2CGUVU1a8OExznxneoZAlKy18/p4Pww1kQBzaHoFFKIRYda+d2kgMNNH/V3ktpHkWVDWOez41kUqVKXA21q5eEFyMIWc7dNz3Gi0w+Hi1Hm9BM2ZPJmFt667vEzvkGkn9t3OtybYA==
  template:
    metadata:
      name: prowlarr-db-credentials
      namespace: media
