---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowlarr-db-credentials
  namespace: media
spec:
  encryptedData:
    password: AgBs0A3VIoXaYSZnwmDCbQz6HlW18c2qE5UfFCbExwzh3ksE3+Vh1/lu0p5qckT0rEECW0NRNw+CdpjIvtjZcPsq1ck58H7tE8swFyLXWB2cx+AQZ5T7zlRqUlua4q5JuQU1DV93Y5uRh0ijvmZHwt1w5DrsZ7Gqa9b2+dMBWyDlDw4v7GgGrn53u/s2hZSd4StsgLcKIlRUrYN93HGiQJxzBGuhls1eQsEeDp4zC9CYZGXBtr0TO7XZ2kcqVRPArJYJiH0+F3C7FNUJykYievk0xqQvg+ic2PT/FESbN5zNeq+0URIVLKL9V+1BpxcmXFihrmTLyPu4mwbq6tJ+Zapbu8scFZCOpJZUOiKFhU/N3s8gH9d/81d0LDL0aMw+nASF6KVrAxsfctuMs4lNq2fPWBxODvIptZnjShomLIOu0MTAf76WvRLmQjpSTQNYmUmzPLuG3sCpMKhPNYHQf1mYGcAmAwqgNDmXPwdJd3682I8q4RP8tyJ4i0l/FNrjIFhwFgp1Nq8JOdeoPlwpp/48KysPAxiTDh1kuhzXybV6y1WMj/kR5i797futsIE2Ja4kxp2je3bFIMHcyVDsbkU41tXkJIqXDrsVofUq5PuzZnRwlGh9AArwpM99kZbvZifTCUsHlqVsvUOyOXd8CXFRBz3UPaZMq6o7B9HHqlzxta3vlH9C9Do4hnNjxge5S5J2yXganOdlPlkw/XK5SBC7+wRQzYNQUj0QyNHawuOoHx48fBtLsmuXz3X0TQT+YjvtwgJE3KeSZyyaTPGkfLqF
  template:
    metadata:
      name: prowlarr-db-credentials
      namespace: media
