---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-db-credentials
  namespace: media
spec:
  encryptedData:
    password: AgBCMUxstJ7Op52hgMonD0u6E1LojdK2fI66aGfDHwL8nmr6LFjEP/MA9Y8IqKaBaPieZ+g3s89bZ3z6ip3/ZR8Z6mL81ZdPQqHNKxtHPy/GvIT5f8XyHHecSD01OF7lSLnqaBw31BCJgrcBZMZepb8k3h3cvGZqz29l0RvAqWcuAX7u6bYQqKEsATbiUMck5Y/zrwdLdvNcYpDwJntHHG4a/ZKeQygsyLjehB1Yld5hRCet6PQan+KTj9VzZfzAvUQTrc34oVwDPABOqOxMe8mbwqACIK4bw5xpwQ4g7T5DSVHKSqzbXooVchq4FPpC8NltkctBf7ccYrFFBgjBtOeG8/55rCMdJgQieieBbGj06rjmyiVlM0EFX70E+qqQuKw6FDsb7LEmmItyFSjRedjgt/rEfNqfwYD99GOMg1ZSSRAZxJzN+D9GgggdvnCxjJwbah0haYKBgxG1b3HYAU24xNjykeOo+lm0y9htuD6y+nZEbY74Wc5F7SuK30ETJSq2Q/NGF24ywEm/RYdoTGcSUxqgPMeRE1TC+LKD5Kwo7EOe+9aobpyhSQ6vOLXuUIM4n/Y5d0LzbvPMitJq8iKnTrpccJGEJEXQ0KP16KxCuDmydUTnXywdibJ1t+koEonnbuF8TgKados73SFsKDRZQVLeBEbHOgyB+KbTdjV3+dCpKojAZfHteb4Dfbl6f9rFaPke9CUyQUhEC/LeaBa9VA38gPxPjCanRxIqUvOp4OmVnxtDBsCfAM17iA==
  template:
    metadata:
      name: radarr-db-credentials
      namespace: media
