---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-4k-db-credentials
  namespace: media
spec:
  encryptedData:
    password: AgC58hcl+fKN8HsavZbsSZzEr7/M5t56IBK9jWfYB/8kzIdoViyidGHWru/j89n+53iTw12PFo2O1pRc0TVIYcLlyJ5V6u16g5ZRkRx7bpmxutF2Dngn4Oc9jSvgMuPp3Jmh6OHvEPvu8nx0/U3X0WOFcRBn/OFZRLHahWO4Eq2w9SfrB8tfDmcfocz29aETcQphW2sI64L98IHczlIZDtQT2T3rJrpDStvOr1EgSeiBMlXAgHfnqGynMrdtcVi4KwomvJwWaD/msvJ7euIdtTXhsEnsL/+/hguFUMmO0NpoUmUhe3I2jygRc7pleIveP/XCJxbdI8i/s+32FK+o+Jho2Kg9Z+JQ9vutQyk1C+6MM3Ld0ttbpVpG/PavtdGe5DSI/7NUsFd3KehjIcQvahkyy5X7b4JfZK7feie3e/mb1+zDBHEbD6UWqstM6r4Ex+sWXXg+6yzSlCjXrhuGbZ3GREFqYHfltPyUXmEMzHaSB+KjaeO3Q6e6kl7tg9d0E2KH1mXNUZvHoQv6rFxv5+1bmkgOFZUjMtb2K6lIAPog3A4mC5Kpwye7E3vN07uprE3qhiVe0CIQ1nF9mvR+ApLMpEYMXfV9xAiObzuUVXdRbxzyMiCn8CRgvkuGpW0pGgNL2/l5LTJvq5PTTT6RlIG3XvFBjraF+9jUS38UNBwu8fuqqnnbYwKYvbcD9emF/JwRA89tdbtMvgf/ZUYVAzsUFxQuMrJ9ioTCqUYmtDsEpVeYBYzj7buHAtWWbAXYfQLUtgQS2FIo3owblnnS3Ynd
  template:
    metadata:
      name: radarr-4k-db-credentials
      namespace: media
