---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-4k-db-credentials
  namespace: media
spec:
  encryptedData:
    password: AgAP5Nx9RJH1j+3SNNT6gUopv/7rN/lxyW1S56BIYjAeAkt40rJooctomKl05oSGZjLZCUvZfSLnzgXPTR96LRX7gpoVwndcF+2NXaLciXnWO7S8AxUB5YBGXoZzSmlDaxydpz80tTb6JrbXfqkZhJZqSfIekL8WuZ6qd/pxlphB6BKIaNR0AKvVtxadEVT/071U6zr+Z6jMcR2eBgG/ZXovgxoPYkILz030Dy6xtFW+SDhE4zg0Rqg8Ol7aaGB0VyDEKJVRIyhu52UnAwLpNlE3mqmsoyLtqVBvbQVVpqVWIMnjWPmqEu3WCs4LLucnfZ3hV7rBMfZzqKMPVdMOCanUOCabLT9VyEnZIuu3KQaYwa0s2tjpqF+mi9Ks1RV860chuF75FOH21XVI/Aar5G1BeFoCVbFcsmdg0NFWBNKN/yXdfh0vdaiW7BKc0aJcLBk/BdkqF18PHC/z+46EAihaCNMA06a2eVOD7fy26fPFIUpScdHad97fwe6h2gBwS55AW+rGWQrrvTRcXPHCtGUnZcdRvS7CmsiTMmjksWm86ROH1O1dhIRGfFdYzLOquXelwDgzxesljz1nwT7aS6DDO7i5iQJF9ITC6Iu6oKzoQ5+lfLM6EPq9IZpvDX1Vd12a+gSVeIO+J70i4ak6WHjdVkEdGxc5W5iMT4qngcbQwrrrNLUZ8GBdIcxqUsbIhRPeRdZvR2ssvECjPigRvbEl49WlCInUJGw/7TwiabVXO8t8BYCgdS1h7lFjmg==
  template:
    metadata:
      name: radarr-4k-db-credentials
      namespace: media
