---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-db-credentials
  namespace: media
spec:
  encryptedData:
    password: AgBukAkP0C2LJWO9R9TuG+LcMk/fSwLCZloRoM/kKQvlWeC+b0HxI/sqFxEvG9O9pHYWdETsjkQ0gnSoKnf5uR0SslhE6kp+fI1VOtKvDyCHxiBqTmgWgdWwLDBFIEPTEtsNvu0jPnrxdt7h+lQchWNSZrbQRDGDv4t2UryE0czxmk7Cbp/jflL2kjIOzXpIWsGGuSBred4erjCKyIDadSe/rDpzpxtrBz+yrJOzNZe8Eu0KvRXlfvlvJI9RKFynt7aNSFb4YApUsl6HJQi4bS8wFeQTOnYc0ncPRr8a8y4VYvuM9cBg5BvwDsw/IOoUP+lMUcdX2/Vr7AHQJCSYSb2O59Ymwr23x8hZijAc9Ejyj4Gjx+8cBKxSYUsoyV7Rm9W9PcRiLDgNywBHvSwyKmNAn3O5ymsN6BiZ8ACjb5XDUsE9ABqTxtPYIYLDc66k60J/MIPrxKuWToM0pXEHs+Ctx8r+qW8gxH5m2x5/bjZJd1K34uhTXBgbedycKzdu0ZJm1am99gZe5M/vLTsMnOn8wfgTNjg+l0npQrh0jr58tpTnZUIj4WJWtUO4H++iEyzWOJJIkAfB9CF9BuXA86c7rdrdRiuLi+h6YV0AsCJoFCN9bmCXgNAhfk5+PlGDrQL1ClvjlYbGXnmxGsw+wh5tj5FzmKZH8ZoPCmsWeBzQfJeRCoocDmXA4k5c3lSMZYNAqLgLlhhHDtrHqBapKSO1oGF/Yhy7QjsbmbPSJwejI9NUELbEYNaGEbWJ1vE4+k/lqADTBvYyty2uevmdpJth
  template:
    metadata:
      name: radarr-db-credentials
      namespace: media
