---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-4k-db-credentials
  namespace: media
spec:
  encryptedData:
    password: AgCbRUWNVoQF/ogvFVGc9Lj07ZmTj0s/RGDIdryhGOtOOsi8I5xqzi/rFRJRFw9OnDcYhqOCmIOT5Q44AgbD9TXYPy1PcYxXNpUsGpXpg6XyqTGlHyrFsb0f0GCxtPxuj3beqrADZ+5I952dD1thIkT1rU/96gfkdWah3p2Oa7KUcvOtoPfURStpLcPEjaE1MxwPyoccmg0TwddWbHoliN4JZMlbiY+PMJlESVwCEgw/A3HCCsf3rohUHDkJuDPSVXKrjSefUxGcld5iXYoAXVwVmP5B5pLo2WrwghWdsYumXrErYSRBUR29YfzrVPWOcwKOThIy75oXZWdTFei3YIx2pPktn3A4XcSWm8ayk20fq1RqkH0BTFGB+EyCpTozMjagCyLTxlHGrqFDYLoo4EnRnS82qmGpw69+vSd1T+lfOohvWfshcIzL3/+82C6CPGk4JICBJamBbYEZ4/DLXrW7sdWCTGUbOIBcvNkSK9MzRvVf5pEwPz1E5zn9osTiJLoosxnr5l0V5rctKOFvRQhyavRN2/UnNqVOGO3cmXWzNgKTOKEci73NFtRFAOkVzh4MnODPLdwGfjQ7iu1MB7ujvXcBW38nU48l2cUXV2MNALpkrN0OifF3roulwRExYTGHC59vbL6C2uV2elyUa32QAuxGAbO0bebbhH1LHEbQw4FWJJXZvEXInEmJndEdN0fnVvr05SbyRBQvpD4G3o6HyiygJzfdK1QZg434ZpFlIEbo9tkEOXFVXGqhXA==
  template:
    metadata:
      name: sonarr-4k-db-credentials
      namespace: media
