---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-db-credentials
  namespace: media
spec:
  encryptedData:
    password: AgBvJnuUtVtosUSmtC2iFhaYJf4b5sqOkSsjJwcOLQpzyf73xp66T5x/HtWw61PzctUpPuGK8SRG4JmPclHwp2Dw4fUqbtq1BCX0r8lAUZyHQOEQBwOHlMmQVPwpldHPOya3HeTo2oYropb1EeSOiXsNiMGq0bh/xf4WMtrP3OngGcE7AedSwxLyczcdNyou+WGBMlMQzncpzuJsp+i62/+RMoWxPUVsCbCa3DOBFyxImZcpoU54PJgaBpe+z6f3BodKfwhR7IK2x+FRyxWMHW0Qig5S+O6A/Ljmu3RadPqwPxx2io9gl9GSVQL4OWY/uUlpEZ1X49665pH/nAFlShA4dApXQR0uuBzGsGJu6uluRCBuMYUTW54TmePGiPim5f8xFXZicb3U+lVaYIjzz82P6LJIg+I4EXz8bBE9WAcBriPybEo8nTKTzXG04RfC0ozHCDW6uS3Kt9H/KPLI8Wfqiq5jeDRxtOIUo5PllvAJjAQXpwpGmKWTWDEFnDSHAFf2sVHBkj9XU+TmwzSoe7xvD6HKoNAq5TwzCJQm789R5En4RdBGf/0Cc1Llz+fbfQubcSErkkPBTtJvS+4ryRzYMr8p+fz/ZJ5IxeiF72qXAIuuunIoiPyAjlvh8Wk1asje37utZ8FK7+bzU3RLideBUcloiUbn29sxYV1d4Sy145bKPi+2xHBeFBCKEv0UnbEjhvLSWJjAW+SLylyh7MglSfCimTldtR/efQam4UhMLphRZkt9pDFPren0tBIKuADigWNCvZCTofa1/+3u1Iwk
  template:
    metadata:
      name: sonarr-db-credentials
      namespace: media
