---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-db-credentials
  namespace: media
spec:
  encryptedData:
    password: AgAwNhzylnt3mxHavmVDafsU1cmWXUU0OpmDMzAsCuyVBksfxT55CU9HClAKBuJTHPMuRn3qBRJKg3aQBxuyTQ2ukThFAX7XFkw1y9lPEXL/ChymxOlIUhUkuvG0JY9yB2wj5xmsKuYn6Q2NszyFdT+j4ulTsdBjmfHuaohdGKrj3QDhbMJGIUZGc/60j453ldrWpAN9MqKhpFCLW2TG2uruhGvyXyxeovFvfaXfHO2YIO5F8iThl5ScPpbn7AoUGiPKeEKxkFSuMKDaS/id+8Etd6CPKZNIXE23hJDPTMLcgZIgDU/MdC1Hc21cFAwomxPk9mAh2QsJTD1OELagFxzqJCpJckzxt4nZWGd2vWAuxBeTUc+4Prwg6isGv1VVvt5XD7ct0lNlouUbFEggHBYhE3Ag49hOZZXVqB/l3xBb/bRH+pC20nNjnpxr/6Rr5ibW04tzZG1+AL1ItRf1zaVllUuPOzwmH8Qz3wX7HCC8+nEfSduEicpDvr7MxzqYVIfzBsAc2CfT6/BTxmfQ30JwAPA0/vbibfo6BOBSn0hllhrqi3KnsqUdfL/qKGbc1sDE/EVeIDrL2yyGGX7prFlp5N65D4R7DDmORwTi9akHlg9AQR7XRKdY0vvt0oe/aBaYJOlEHO8gUVmkeSH0H//KrPYWsiEVpA4ULOJ7Hh/x73ahPxKbAW/vRLdK/woyxVwB+TBmuu8Kq73nmFr25idiSCMlhEyadpsVTslDvPO2ew+3/th5dRFGbFRUQw==
  template:
    metadata:
      name: sonarr-db-credentials
      namespace: media
