---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-4k-db-credentials
  namespace: media
spec:
  encryptedData:
    password: AgAsvojIB2ChhqAgs0J5OpVa29Dhx1YSHD2LDc/Dec/s+mH8LHLri5LZJXsUaYSQU1h9iW3EKcvGVVMhIqejy5Qk0cF4v1sNju5NMdNAa7sHeKaE5ShCBUU5+G3MaeLuKL99PcnD0N6ECe7kRBfOMHNEei+HcVa1aUpRrJOgt9v34Y+QL0RFyrplhN6gV7DAjgVLT1spc72OYJO7UO+r3M0VwpsLp8J/IpQMMG7on10884VtyWa18x5REc+fBlTzRPkGmm7SWvqK7dpD/RK62ucRFEuj3+wAFas1wtcgr39oaZTqCHmbpe1s6aeOdVimdm/m2IzGzNclpDG8Xv3pK4aGsQ+GVtm91zPOKQpCj6ILO85Z3UxH0Nz4L5i1+fEZm4mzupM4evCTpszMxA7U+khxxCakzsIcb2Gv/P5hH3LHPNy7YM9OMCu7G1yHNssXmVXnbIVDwx5IPufVViDsPvn7/s5PbRQ1ZhaNzNVsI73lEuFdOB5O8ZUUyM3hen5McAAfPsLP10704uBtbb2JDpSWx/RQXOUS27Ost/5gAyQgZ0I68I7WvgWrQP5f7G42jAOhd8W9sGQLkHaZR2BuWjvPM9741S1OTpqi2vNlayucMl/AVrcWQYrRCy6pzeYoVNMXeSl3qFtnUet2133kfFHVA+g7T7+hApwUGt/LRwkExvF6WdGEA2Dj+uSydl6JTM1YhUOicLSyLBjDM41nlUYwVbdv09hkx0RDxtAHVYSTWLLMYbo0I9UMS8Q+HOyOD8pWv23JDZrfsUEu65CRTzZ5
  template:
    metadata:
      name: sonarr-4k-db-credentials
      namespace: media
