apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia-redis
  namespace: authelia
  labels:
    app: authelia-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia-redis
  template:
    metadata:
      labels:
        app: authelia-redis
    spec:
      containers:
        - name: redis
          image: redis:8-alpine@sha256:81b6f81d6a6c5b9019231a2e8eb10085e3a139a34f833dcc965a8a959b040b72
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: auth-redis
  namespace: authelia
spec:
  selector:
    app: authelia-redis
  ports:
    - port: 6379
      targetPort: 6379
