apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Wave 0: Namespace
  - namespace.yaml
  # Wave 1: Certificate Issuer
  - cluster-issuer.yaml
  # Wave 2: Certificate
  - certificate.yaml
  # Wave 3: Gateway
  - gateway.yaml
  # Wave 4: Vaultwarden
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  # Wave 5: Routes
  - httproute.yaml
