---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-db
  namespace: vaultwarden
spec:
  encryptedData:
    DATABASE_URL: AgBmgl3cbM5S19m14WsO4uck5Fo2KctknghxTE85odqNN0+IuQXRES6C2L58+pRACx3x2GfSRvWSg7gJGscFmPKS7Rl+kh+hbUUfufPCIAMzo63Je5QWJncsYGWchZZplsBqehU+U7PLluDclbr33zutkiG/8A5eKbmD/lUgohmnG8dzQMX9/QDCzlCjSOfvkbAqQSavwLobPM6tfkBPX0IZ/Q19rHez6eNrJGxHxZ5EKWOFu4stkcruqrEgQ58zeiuxk53LQ9XSM3g/vbTUoFdwD/jEz1iHWI2HB9WctwFFPBOfHWuljLcKpYIUlIHY6NU1LmrC1Jc+lX0cQL2lg8Qup2/fn6Nsk2NPpcAgfq3ewFoWWFlQLziDAhw6y8HUST28N+N97BuIj9g/y3IRjyPhxIjbF5+cuyO0hVnUfT+gb/9PqgTOCg3RvMs9PTvuzqXVc9sBph0kyKZsGhdKf5jIBLW0tqVSv+TVPEpzM2Gfw1GEk0XbWikjP/qc25Rrj7T3kze9uq2y81XOR9b5mA6yZVDtBdrPK5mIRzkfkZC8wyxMzSrP/Xv98NgvR/BCNEQ3xEzhLgjdkA1gaAj0OvjqqHcfUI/ms9czLe4hlDhiNCxekiP3QTecdrYwXfz7jQBKzUtUyWfnNvLbHaP6u5PdUmpfPw/n4X+GKNW+HdJzHBEkB7u+O0EuV59WH8/nf4/PNth7Ou5nEwKYQ3rBDwVvWkDba9lK5iyftlfVDOZdY148tUE1q7TCZE1SO4H+CfRnpojRgWLxvvAfXnMlwuQUWlI2JaGvmghnSZs5MdnJzPEvLd8j07bqWuvf8qWD/NQC5ex+yyZ//S9Tk/0IIRIPRoY3P5ATep08ojI+CgWDlIc=
  template:
    metadata:
      name: vaultwarden-db
      namespace: vaultwarden
