---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-db
  namespace: vaultwarden
spec:
  encryptedData:
    DATABASE_URL: AgBHLrsCtDQLBUWl45YMbPKmYoYS7+8dWaRFELwdGGASLq0KIJUyGGYNkJBBv4QJDojQ/L5zroywgwciOvCgk+cHMP+Ye2KClVBhdnIpt14Yq/OWNTA/+YsSbvs9ryKVOhJVPdkbhL7XzFgUZzJoa2TXN4L5/iuYboUadWALZUfGLFJ7ynudfS7pl4KkPeumM3B8R+YLRkLe1QGeCNMdDJ4Mf/8BZGRmTLDOJa0bFImaHeMTTI7JWyqGZpvYX9eA4wMDnJADRvuF8JAWYgQxYeDwp5NY8bPcGbUpekGLy43n9Ed24LiHI1cCKQa0V6tXeAmZAep2HXwUNk4n0cHX3329sC5t0Xje92+Kj8NX7nxq0GTjb4+i6T/C1IMzApDcc4L1T8I0GZvHL5jRsnT7Dt0zgpMsd4Vsu94wSXtrZvr0h4pkmnh+hOBKMZqNGjQdHrOqto3RwNCFbEj1Vd4zKgIo39T8TI3VyOExeenYG5H99V0DT8F8vezgoOCo6/GQbxE09+hJj8XEzZwwgme2IFSlmKAyyQPpA4EB2zdPVK6U5VSD1mdtD473NtlZCVzaXtSI2ezsQGzdwUai9mqo4cf2BTDS/5smBivMl+L/O2cEusQ6G4JNOYuiO7yczfYraweOB/5YYvQQYx1xpf+lH9ANQ8wThaL0Bdd2RlTJmG8feFIfvzft2UZU1oTt3oI0RM3oCAiVe6KCB5SthQEy+tMtX5hiYDuqRsLYJBQ0QBE28uBBczn/TJi618yauiYFpsZs7B+AEXCNEVdntemYQlvZt6+TF7iyHOy0W2goPgz/s9gfpgjrVA26zbZdvfQnEqMBDQFDBxnzltvd
  template:
    metadata:
      name: vaultwarden-db
      namespace: vaultwarden
