apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird
  namespace: argocd
spec:
  project: default
  source:
    chart: netbird
    repoURL: https://github.com/netbirdio/kubernetes-operator
    targetRevision: 0.1.4
    helm:
      releaseName: netbird
  destination:
    server: "https://kubernetes.default.svc"
    namespace: netbird