ingress:
  enabled: true
  router:
    enabled: true
  kubernetesAPI:
    enabled: true

operator:
  replicaCount: 3

netbirdAPI:
  keyFromSecret:
    name: "netbird-mgmt-api-key"
    key: "NB_API_KEY"