apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird
  namespace: argocd
spec:
  project: default
  source:
    chart: kubernetes-operator
    repoURL: https://netbirdio.github.io/helms
    targetRevision: 0.1.13
  destination:
    server: "https://kubernetes.default.svc"
    namespace: netbird