apiVersion: v1
kind: Secret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
type: Opaque
stringData:
  # The 'stringData' field allows you to provide the secret value in plain text.
  # Kubernetes will automatically base64-encode it when the secret is created.
  # PASTE THE ACTUAL KEY FROM YOUR '~/nb-pat.secret' FILE HERE.
  NB_API_KEY: "25D1B3C4-1DDB-44D4-972D-E8BB5BD4C1FA"