apiVersion: v1
kind: Secret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
type: Opaque
stringData:
  # The 'stringData' field allows you to provide the secret value in plain text.
  # Kubernetes will automatically base64-encode it when the secret is created.
  # PASTE THE ACTUAL KEY FROM YOUR '~/nb-pat.secret' FILE HERE.
  NB_API_KEY: "350588CE-8864-4DCB-B1C2-7DB2CBE2AFF3
"