apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage
  namespace: garage
  annotations:
    argocd.argoproj.io/sync-wave: "14"
  labels:
    app: garage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes-excludes: meta,data
      labels:
        app: garage
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-nuc
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
      containers:
        - name: garage
          image: dxflrs/garage:v2.3.0@sha256:866bd13ed2038ba7e7190e840482bc27234c4afaf77be8cfa439ae088c1e4690
          ports:
            - name: s3
              containerPort: 3900
            - name: rpc
              containerPort: 3901
            - name: web
              containerPort: 3902
            - name: admin
              containerPort: 3903
          env:
            - name: GARAGE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: garage-rpc-secret
                  key: rpc-secret
            - name: GARAGE_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: garage-rpc-secret
                  key: rpc-secret
          volumeMounts:
            - name: config
              mountPath: /etc/garage.toml
              subPath: garage.toml
            - name: meta
              mountPath: /var/lib/garage/meta
            - name: data
              mountPath: /var/lib/garage/data
              subPath: data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
          livenessProbe:
            tcpSocket:
              port: s3
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: s3
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: garage-config
        - name: meta
          persistentVolumeClaim:
            claimName: garage-meta-local
        - name: data
          persistentVolumeClaim:
            claimName: garage-data
