apiVersion: v1
kind: PersistentVolume
metadata:
  name: garage-meta-nvme
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /mnt/nvme/garage-meta
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-nuc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-meta-local
  namespace: garage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
