apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-garage
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-garage
  mountOptions:
    - nfsvers=4.1
    - hard
    - intr
    - rsize=1048576
    - wsize=1048576
    - noatime
    - actimeo=60
  nfs:
    server: 192.168.1.192
    path: /mnt/HDD_ZFS/nas_backup/backup/
