apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data
  namespace: garage
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-garage
  resources:
    requests:
      storage: 4Ti
