---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: garage-rpc-secret
  namespace: garage
spec:
  encryptedData:
    rpc-secret: AgBAE7tgb+9gf9UqIgWImRuLPjSq6H/4J65Jr3ZBm0/5AX0z+REtmCQ84anfUDm3CaedTTAxyOT2p5C0AH0qRao49lM+oeRduV7VjbCEeL6I9I1UqUoyzqNGKVO49y+9G+NBHKERncM0ubGtU9bW9pnpQQcZs6bIjZP8yszETVVXgIZZgLAoBTESytqeZZjF7AqdhfuLlEF1xgM3VbO7BRuYM5N6IpQaXL/8ljXf86lQAOg/2NTBGH4lC324iDqmbb19ovEafsaGVw+vt6Wt0hZi8AXY3veEGezKAXNR1aeB90L3Pvbh3zg1itO0+G/MapAIYTxNlwh0LrGISfPTqdaTFPXna8jT1fM8mR8fbYr6oYLg1sRustpzwywYZP01n2Vq/JE1SvD/qkuif8VEdER8nbrgA5zIc8CRF6v0Lb6wPWDsQB7aF90cpC4aYRhLtx9GDi7Hb6+N0OE3QgvTdUb/6ZGFsUL4Ak42XceBH0w1WiBmCAChxP0wobGZQKX5/QnOwCwq8hVoWcSmU8IcaZGgfadae/g/nbWQ/qTUEXhfA3f1DC7xkampnsok7LToCEDr7HernE2we/mxI8tfrtwopuysXMHGfeL9wmZZ9CUmWEwsQdycPPPtOwhsesjCHinrHXpteHTthuF3kHHOypL1zFkD3JdMd/cpq2W7vcUM3Px4QiQJebA1p0e5VB9o7qSBjV+SL+CuFprhtgK6q3+AaHKiIaqzn26xC2PX67XIHnb0OeanI1g9IKs+ifzB0hIlABt/SC0Y+KE34bDztUUv
  template:
    metadata:
      name: garage-rpc-secret
      namespace: garage
