apiVersion: v1
kind: Service
metadata:
  name: garage-s3
  namespace: garage
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  selector:
    app: garage
  ports:
    - name: s3-api
      port: 3900
      targetPort: s3
---
apiVersion: v1
kind: Service
metadata:
  name: garage-admin
  namespace: garage
  labels:
    app.kubernetes.io/name: garage-admin
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  selector:
    app: garage
  ports:
    - name: admin
      port: 3903
      targetPort: admin
