apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: garage
  namespace: garage
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: garage-admin
  endpoints:
    - port: admin
      path: /metrics
      interval: 30s
