apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: stirling
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  cluster:
    name: postgres-shared
  name: stirling
  owner: stirling_user
  databaseReclaimPolicy: retain
