apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf-data-local
  namespace: stirling-pdf
  annotations:
    argocd.argoproj.io/sync-options: SkipHealthCheck=true
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
