---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stirling-db-credentials
  namespace: stirling-pdf
spec:
  encryptedData:
    password: AgCUclYbyUPygqYyFI57a/IUO3GzSw1QBZee8RLp+o3l+ftvHCmmGUp5019mjQERPAfeeLyxF96LKvoBfYi4eqFVpVrTCS5tjd2MFoM8zknc5tigRCAoRsV0/TI06AUPO4WyNhk904ydY/yX6VsZQh62gRsh3W4EvEm0RhJfyII0NCm7x1Tv7nXd1bXmrXTcnSpv3RBIhIvkMjxSCw1iHb5SYBROdcwJ0BSuvDQgNu6ui8f3y3RwxJP4sxsSYDPf9BTTOzK9VYfZi6YS365WAcaPLdQh2UIYdDkntQzVqpztEZqvkywyxIGTDrEAK26KYQAmUckKCSBubB0Yt498hOPBQOdqyojZHBYzXtCXp8ArH96OHMCGC+tdcpmP59rHsPGKgIIyZ2SjO18yizLx1Z1nfFy/C5z9E3UxRtvXdCh92jQFdGJEAY49hDnMLnNmpj9Co8pQ6LgG0yYO9xa0ugintZ34nNaduvnRFcueWHHlCpymcUd2cI5Fj+eFB0pA50AWvkB2nzPYjkupi9qKlFs6oLRaUoS3cQBkyy2/MchAVnsZDQgfTx4FFv64RNTwiWTEwpBYWs32dNYUgLst0ZtchtPhBSYe9KW3fB+rQ3lRI3mrwE9j7y0a16sNWAmC4DluOkrARZaY9GLjspGb2GflaLpxz2fsyMrgRF5Ku8BCWD238UXqTDIesXOlw14GLaiN4lL0D/uXxibALtqgdnUxu5vQ8kuujrgTSC+JQnXQtm6tfY+MTogy6oeOhw==
  template:
    metadata:
      name: stirling-db-credentials
      namespace: stirling-pdf
