---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stirling-db-credentials
  namespace: stirling-pdf
spec:
  encryptedData:
    password: AgCMDckfAzsBekb+dYS9UfMvvhQM4cNcGYLjDavzQdf9shFTq1I6kX84PEmw3Al+5BcB7kn/0QFQmXl2EqDumsBZv1NCxY4679YUrMhIXXxCkAX4yYHUdyKZvwaw9oMCRhzHxwXX4G3HeNawQ1s4976etl8e1Xfz+kliuVRudYxw4LhWZGUVHj3+HBhhAhHNM9tk/ykJNCympZkmwxNHAxtIIJw5a7rzKWnaTc8IKInDFkq+nsAPVbro2VpQ2NMhiql8A8GHBROrH2/fhZpvbQAkcO9VHfAksO1hHCuCy4rFHsTyuQBUyjcPwNBZgKWOmPeQhIj5NR2qKNYgpkHzgRKWndtU0N0RPEHMv3K9oLnB9qPsc3MJI+QfTL5cmVT7nVGxS9sjCqeaQ6oHGDjK4iBrOn13P6oP7cnDdBSlbBWemWFZro6TcMymxz47xvAdZIb0D2txfVk5sfXk+IDRmmdHhp6ysEEjSjU2cMoQIRM3hLiCtX0+YrbTkhGndVyMacVg30Oxq2YA01vmgDGg7ykNXBmqaa6WHiM+QXCP8yukzPaYbDraDlmwkwhLZDJ2/vu6V9mH/4ellXvKMdhhfDTxgbyl4GCTlIFskrUzCIB0SLTbUAe6fco3N9iTkMD2Zkf4+TI+CYqLDhoX5f2Y8TXZ0G/b73egXGBBF9D7h8EwyOds6ceN5zzvvV/rnwx6F0nZs9pvpyuJ4tNB0eSnI/bADnjUApIFYMG1Z4iktJ4gJTkr4eep7MQ4LoeGX3AiwvNA/z1UWm2DbpVZpon1shu2
  template:
    metadata:
      name: stirling-db-credentials
      namespace: stirling-pdf
