---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-db
  namespace: mealie
spec:
  encryptedData:
    password: AgA4XlBQqzyJhpM6a76stXFuCEiMOKNdTc4DVJjhvGzSAYbNi5nSYBU5JpCUHpdlpL8dyLm30JdC0Rd7QYvdf9mWHz0z0RIc/GzCnEXct5OJvlK6zd6kZY9+uRL4Yt5i/pAh9h2AIrDj4N1Z0p4QHjypoFqvYJxAv10CkwxoEdb1B+O/RQXQ6Q7mubgv4YDdt5eBogVb3UTW8tqn7yu9KoLgfGsyR1fI+gjOiKFZdDC1v5FPsBhOkUM55jaqc/+YtYpkcz93NhbMX+rwxuXEL6i2PBe77UDxqtyhGzDgLwrgxOU9d9zSJ/g+lfLajpsahmI0B7aTnQPidw7fhsJftYgOxQx4HQr5hUKZUqapekiiaOD1cPpMAewYZb8LLgLC4zjozujmd8BQyAve5sEAsppE7vivE/10SPLohia43JHsYqDYVd1K+2Wvy4qgc4iVmAE1elxovbn32IiRsrLsuUVhW4b3oNNLmxWipTMfGs4QgWfJR27Uj2k9axEajHXblJjm1HKGfP+Hs5diWVZO/BHu1GUmySknFvsVL+CLGCdQRhHrszW7ch7aK6uSmL2rdmQakdNfBRtVqtz1IoLsWiNVS+7X+HvzYn4lq2fgLbXzjgydn38VP8IBbLKobaxg64H+n0tGgx3BGXM+SsGedJmDApVGIFTYv4PlvzuGzLKq0rw7MOC9FqT/Ijm/2FReUr4iwixZMwlgQ+PTad/PlJXRaM4pq+DfSbW8s7j2PAMhng==
  template:
    metadata:
      name: mealie-db
      namespace: mealie
