---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-db
  namespace: mealie
spec:
  encryptedData:
    password: AgAgJ+vHAfgcUBXArfFZtdDAsFD4M/iwYzFW091KD1RqdW4SwW+JxkJQ4mNE17aZsNr7rplFlf8ks45RJwJO9SJs0+PmnfDcuuq6MIzTk9IRQ8/jQ4xZP9W0oYQ4yrRxcOW3UjaZCXisMVSneNjqRuXNZg5QwUHy+VaWGb1DuboVv/kqjOfPl2c/MP/YIfgJh1jpFsmYFxIaQ6bKTnH0jE+FWiw2UOrdnvSx04N/HMB65k06/6fPt0OYzVxrDPCe10+Hcc7ShQZhq25Y9IZOIIT0AUf+rLA/iLUAbPtJjgsLve2t843Gd8gr6qywYhlF1rRTLRtYtDXsfTiG5Hfmv87745v+Fe2jIpRgyXWEyhocPRdlYRCSyCnSMZQwQ9amzNLJwEdfJWrWzBBn/Xt0zj8CQYB74fzFHZYx/GnCIQxI4LJhf6HyGVG2aczonquu8KplXxFCdaMDnxbkhjUfMRiKtxch/Hpyn1Xrv8w9Dq8L1mGdbgQgFhj8z8Lqy0bJaq954fN8boEnQ4CH7SulCmW3YwEURg7P4SeG+HkVAI7LzFaWvG+pHHnFGFxX4parkkxyKIknOd6MpHsx4lLYjWoO7HYvEPz84vbYqXezs8hvDNxVsluixK3Gdfn/XGA1OQmrTN08XuEHGq7Zz0/NczNXUwl/36VIpEj55ztMidVEZbDUpypNn/qllz+8vyQUUIgenzHiCtYFiFo1nX1APJ1IfS8YZIgT0bqh81vt5O7e4xdklL/fsumfASVATg==
  template:
    metadata:
      name: mealie-db
      namespace: mealie
