apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data-local
  namespace: mealie
  annotations:
    argocd.argoproj.io/sync-options: SkipHealthCheck=true
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
