apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealed/neuvector-controller-secret-sealed.yaml
  - sealed/neuvector-manager-secret-sealed.yaml
  - application.yaml
