---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-credentials
  namespace: nextcloud
spec:
  encryptedData:
    password: AgBiC7EgSTXv3eBWDAF7JkQZJVUBw/xmI8JzxLbeBT3tZrhmuxlsN+R5X2HcDy86MsBWcPN0kNqZXbEPoWzjD0ZeOjp63NppF05P4GZAnd+YZsOA5dX4MgMj6CZF91CcV0t2J4nz8n1XPbo2QjzIOgGckUyrzH/ylN1m2rXdNV0GtruGZ3Ltvyq9o11uAlhvxZxV5iEiO5e/Eiv2ePDh9GlCv7yluDwITtLaI6N8Htwk1BEZwzY1kUwF6o5W5UYd8/qYF8bPOLjUj4f+/7jn/guXpUNxSk9BFNKQCb9hfbluZRR85VB8rA8wK82l6A+2XkLlR4rtbRLDkc9v5Mad0c4Rygyg1raiFmqeVxOjjoahPTOs9/dTp8fjLwvAa/et9JXlSMejykgufHGpTmdH5NrKqzCGnBRdymz9ssLquWEZGfdTryiYhJJCkjH32zFhMxX2WhM4mOr9FIfvBKniecQnmN4x5FhJA8m9YbNhrLOvy4NV1ic+khQT8vETIzkToEk2fz6zG52vxwIeC24Qho6ar2AGOjInxcB3NYYE7jWgOvDhB6ZYU12cbUuZ7HvTVkq83try11Qw/jhOsA2LVqve2bOQCsiZCKP3IFY8Fuu4sAkYgg33YCbKlSXP6B8dVR44clxdPw6cncMMKxhZG+OK+biGPvkjpr2vGGPpcOSccrMZZx4ku0P2srLRKDQOtBC5i274LMoQ7Bi1fVmX
    username: AgCjhb0C1Y6Dw4fF7hwgavO21IkpC8Krrwqh5oqSFmuKogyZXag8H+x8MHarHsskO2J1FVxf4w9DaVslN75JdP4JyxRUAACtQfcqeEPLOdGLmwDvQ8esSo/+PvjLO5bzJLKq2zZnnS4YxVjjGtjj294nhKeMjdo1hcubvyJel4Tv06xaMnScvlrY+ld1Ki7T8xc2eQm41hTYClO6KDGSQY0wZDtwk1h/YoTOPznaiz1Bx4qd6iL/m6y2KkVcY64Jwi4lwy4nciBuF8SqL0i6S8NbkU1Uu2j6dYrxQikqUoQk8AGD+evDaI5vRJu8pxQZmKxV7ZOeegCZ7aT5HR23C86Dw2gSM9N5Sfl9te5559F7hCAyYl9nbDVDiny2bK2iIvc255kdvoMFLrneqhB5XP+cMNAXmcFnAeeUjtY6WBFnSkrO4F7ijuEXXVL74z+x+tXzXGymBE8oGeJnTxDwdfBbHE4lZvqyZ8vgI/BoHVElb1x3N9M+kw53Ju2qsV0SLQOARDSy5JirTDtvRL+E+HGafV1yOX/QVgCzyEHnC5dD/OTzRQYmJoXWeYwoQRnwVxNNAmYpk2EiVS0tp7KfSKQCw/bq0tO1Khgp4URnJxD5Ea0LBORMvyq0XPOdZmx0RlMLHQb58uyCHUsE77SgAirtgami8UeHK2okdJphv1chGx03Yr1P+Qtc8v+a50kqLJxe5nVZGw==
  template:
    metadata:
      name: nextcloud-credentials
      namespace: nextcloud
