---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-db-credentials
  namespace: nextcloud
spec:
  encryptedData:
    db-username: AgCRK+p+6OtwpWAF12oSNBPMVW+VtEFz2+NyZv8CmKwTO+/JDNe15nvhk8mv/w4f9Lus2WnRuFw4ICgCO174/cch4eZ1QksneKo0utX1f41iRAFIwMRT04PTNPWR6YVlc44fbJ6173SYpENt8UIlJiJ2w32MNyCqqer1i6bdq2KlIPCerfUeyKr4tRrscOGKHgm5fegw8g+dWLGmSkP4O3xhvSHAY3F+HwYk2iA3f8dtG3L74U3DcbHklcMyy3sNOHcfkB1DAA/1nOmxWEdtwWa2X49buj5Ye0GdcvL1zRenlLpCZJ0pVGIEXbHnfrRHxxB9zQWP7WmI5EVGEn5NKlaqVH1pIcIn8XhcO/iv65pNO+3anzyqAyRlTWimAGLwnHGMV0vtSYmcAkonvr25KqLSvMNcMMiNwMfSTevamDD7bKYPPSMktFxavG91H2XWK6BWmx8GMDWP+7wCzXgIEcy3OQmw6pfuHw2q3+oajuhhCk3u9kq1fkp9fKeCqg2tvKVyBFRs4ks7n9ScsTByiA73eBiIMmgUNlLmDxQiexuIos0Oz5AEihUbtU75yajC3RuHWgMrwOpORLNLUict/N7okSswTABJUHMHGk2UHrYO/snRN815Z8sD4n4yc3zWTjii1YqyyZac4VvLCQNqQ88fVEOcKAXXyWqG1VXo7SyF5UtGlr7j+7FZ0JYb3tqVs0hoAr1bhjnG+1/rOLr28w==
    password: AgAuYS/6qOR5bYu869vtv4lwlrOKB2Lxl+xwlJ9Y71iupL0HUbpIJtV4X25LbnmuvzgNzYp8nFCVgSWjt5x4evqueqxCYpKVz8h7w+oWGf7M4LUoKz5kGI8d6ryrJBaop/JFyCzfHfak/32InwbktJ9lb0RUxa0ZxJNEOwiq4iu8YzdvtHPRKbujPBu0dAEI2zA6IZ5Q83TZjbbH3SfaF/22bZRux5u9Q5KnbWDE+ipS1C8mxdPWwdE6C6VtPWoEfsEQ4XJk1esmfoo6bCNlgB2De5Uq/982yt5PAcDcKuk5seCJL18VOTWmcnaDVMKToUqKVp3ckislXjJH2fA/IMl/SD0UgglnQ/hfdb2RACREcvm9wYhCIFWDZLfP7l3a3/gW+85Bl1OKA9x1J/ZYytc38IhMqfqPXqBuM+L25XPgEDwcrHPhaI6rWMqy2U+MxpWYxa9LKt6jlY1/AEHqKG3zyqsoyPQC/orQ/ubcQVw4hDDBzS/UulcJHBD+8EaC7aEl/x928UMMEZnQKI4ScadXjCHgi9J4M+2gg4E1x4w0hzo3NLE8s3Iyz2WtsUDV1nusqCgnr+/SDEqOkDXx2MulCh/k8bmmd5z1gUr6vXMpqw18SYQmuFaZeSVnijfDY0RwUZGalIk5txxF9MK4cJ029icaff5UAPI3tTAhXNhwV20KMjKIWqVANgSv566jp/9MZ/v9beESbb6pGAbv6AqPTu0+DspsyK0IRKQYz1sD/KvCe1ro2CdNwuvqZA==
  template:
    metadata:
      name: nextcloud-db-credentials
      namespace: nextcloud
