---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-db-credentials
  namespace: nextcloud
spec:
  encryptedData:
    db-username: AgDRxL5rXbInPKqYC/nbzakV6vOdG/V/q97Wr6WC6R7fcNf5K5hyXS4AbtG8PYo0WLuSrt6EYsIu9rcj1SjJ+pC7SEaoYHILTe8D3UlJC4f2tJfDvMjrwPRAs+smxy2514/oKW5RNcYWGCTNKiMh1unDMf9MvjkiPPN477rBIKmRvthhhaWYKEYIQmM6amxRlHvwX0NtaQkwaM+j66DzNIH36PK1kUJ6pY1J7czOMTCb0NPhsZtDpQKBqiqVye797V5R45cqGa4kc0MKna7oHmzY8B5hfnraIsvEUN7NcdM3EWilkR5R7BzGjRXs1WRQ90h8tiHE1K/aF3+tXrjY9QiuY9f+sgw67Qsw84fjKiTT4QfObfsqi25GkXHG4P/5u4OY7cvuAVcJMhh8lyFjKf1fCygnTHQhPj3Jri2U7sozn30R6LCUC4GPyDgJ4sEN8xwSNsPlNAI3dXZLfWXgY7PdujMaK6QYK58o+X7zgvVHQXF5nfjvpnrpt2+mFCBVfsJCpSCcqK6xaXFkUoIC/MBeTtO25sSGTN4GZ3Xtr9SD15hJEJoXqHiGAfPJ1v/rOR6IMpCQmUTtXbyKgIt0di6wPerUm99COh4vpIQuDsDcNIUqiplKojt/2TY+okIhlLLQFNT8jpNsHCk6JoigQpZGE5mxYh0mn0HwEOiPZ5A/ro/gkWV+MeGdGRKemxzar0MaWHg=
    password: AgDOv9iTpA8LjvLb8zFGqFxMemZtbOM72ybD8WZel1NYBacMXB/jbCk0V0nvSo2ilxDIXNJlCiwkb/7OsRLTchk6I+fuKYi3z1vZRAk/qpB/LXwMjciyaVyTbZcRLX9ZUMJIONsc0KzeJE4YPvVlO2A68bduBGAQqvbkKC1pOvTDqx8HorVceFauev/xYaAh6H7K1iufIujInjNIYGx0zX0El0XK/bEUEnE8/qcFUbszjxoWj6Ui81HOSr3cpHmgxtPaihxs9bd0ZcO7RyL3sfkHpTf8m7fiEppymFumHqQSPM0qsrOwAtcEeKX8ZMrNJ0/SNKYV5vE9F3d6P3vfuWB/8nX1xnaCchsHTLlfTKkBA0GM6nC2tLdeekNgF6kE9t6jRASVhVlG5mQbhWY18kcKjrFpI3K3r2tb/GVngw33KW8CxhlAexDvB8Q02N0brNnZyFHf1ADG+liVwrY5OasCcrm05OcjCbN9btBWSR0i4LqX9YKXkLq+cKOAABN414coueAxPckybEMwgmFOxzHgE2V0deNTW8tzDIgxA1kBSH4yFwwDRUHDujTAMax84SGAFOpxAGCi4VGqo5bT2pP11H5mh/njZcCBECDes1JJOOATeg3X41qJLY+0tJDeAiKXTlodwT6uFwO9lsjd629xmMD404TxAg1ERV8GE9qz5KUYSX6dg3MMOsRZ21E24QnGiitmHp+4OfRDzoVBj83imXIu61ydQwyORWW2rt/kUD5Cyc2DnQTCWZ7Si+85GRXmrfC6kt4e/DNVK7okMnG2
  template:
    metadata:
      name: nextcloud-db-credentials
      namespace: nextcloud
