---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pangolin-user-password
  namespace: database
spec:
  encryptedData:
    password: AgCao3e536oAVg/4vwkX5krRHvLk92IzHWj4dwKt8hrsCaD3oK1L6B0LKU9TGZLr0piAzVIGgrH/ax3qTXnLL8Zjb1Uf7gLRFzu34ko6SBqzVtnqVyAHgJ8k2/6soSLk3nGO09lKr9Vicaxuczs40Xg0HBWPAIDGIEFF1vAfJkT0jcgJfqL/wJcrgZY34/6gEftfGcS7a7SoR769/rFgUOlixhruCX59dRc7Gzel0kCvQiWBbQNajaHzbgLJKS8upCjbmEM68dtXLQZgXsUbeV1pDIR3aiFdC+UYldf/GvKbkw9vzjWmrapmpe56ux5ghjlr+0MmTV917Kf+o0SEDuxj5rNM3/fyS3vsL/sQrWQVoZNJau9Kd1CnobZawHq5ifCkKn81Pd5Lxa0Wjt6pZmtygz3cs4AuWQa1vPkxohiN/zw6BBcUR0tTFR+lm5toTghbAMy4Hn2h0wOoIki4zhvPgrj4YE8LwIyFvr5OqIIi+E1fJHHxg8KvQFKoYHcoPIEGlq2wkjB/BWmp1VAFZVADyXvGM66mb8V43CtUWn2D43W3KMf1CVAm64CDX/fpKRaQqkgsp5wkkletPgrkSLzJUtKQdFifZ8LvL7FE49UrKexMDcZtWfRykmvJOLyFYdK1ZvHs737li8G0E4AUQriUIrOegb+hHUdE2M2SWrmmAxpNL4OT5zgSDBJ3tI8i+F1amFxRdTH5I4isitOl1p5cCbCKfIedmeoaLZGW/p8OBQdxV94Po8gmWv7m
    username: AgAmYYpmV1h/Jwhu9a51PHL4N8jaDA/4XujMmxLrMqjoiuOeoxKOQfchomgZM5R/wjwIB4CXouvajElXKx1bXbtpV2CttyHSaDga3VkIktuH99H3BS/ESYS8Ta9rjmYTDtpzuck4sDAlyMOhZhEEiJn6vhoOhWqzqUjVujVDiKjMvIOkVMqmpw6rNagPBgksr71ltbjfrLWJ9pmKPCmaFFmwtHyH8e0c6vgPmDcQ3d0TWK28HEwZHoWLsgNbG/S5rWson6ZLb43NEhh/ge05mOD0ofQaApk+M7rN8J/bAYP95Cqn8WoOUqgxq8//3i4r9kFZllQMg/gUTDv8EzGPOcxjxj5PCe90U8z19KojB8ce1SmxftT0wQxyjlXnAvjXiF9UjqBg96CDr6EwZVWTDl2crlwglNy3E+TjZo9AZv3tyebHcq3d+7r1JNNtwpogtsLOLB6DVP/YhidOyspDiq1+X3gFaHJGXiMdwcdz3WPjYfHvm8aOL/++TmM980afYlAtvQzQ0EhLTFUtIdV5DOmbCDJ0cIqquOU1zyEaNzy2kfxYbRNKZBwEJL2cxgo7P/Tjacpqv5QfezAKKqAvLyjxSyoglYl8ybc2B99F7zySYNLFLdNyEJXEnK15r9Q7PD7N1wJZfZOs97jLZfhfWt1QgSEsmNjOM5u0pu0k16HUxai98vsNUBxMfYkGflgoRBG0+C0ZoNUydAyte5DU
  template:
    metadata:
      name: pangolin-user-password
      namespace: database
    type: Opaque
