---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pangolin-db-connection
  namespace: pangolin
spec:
  encryptedData:
    connectionString: AgA35Y61u7HF7hNyK90a7DBp9RoabnRBOfAHWXtyH/3Mzb1QNQfx+0uETyiFh1VqUZtgqpmJhkuozvPDMAks3/mao9QI9vhPIogEeixsdZQ54YiymxGSj0azykEiJd0gJFJO+Cc5y7Dg1zSkmzHzkoTHO7JfI2KDUIBtNEy9wWU2F1Gl5xWstYBJZrS2/bYkKhlfVfdAENVxHyEVMFXqvG/9OsuX2bilkCa9H2dgmuf0xQaGOHOTfKhHNIDQxtZPUkIwMRT5pGJX401CWZjlElCFKLC4mw8M1HhKJzrNRO/ReKSo1yWmedWlUwVu90h/E2tMgs7Q3eRFhheOCQ/dM1pG9yOH7eInwo1wEAtZbJ16FsFVMJ/RMxvXs3S1SttGpXorDUTjRhGCXnjadKUq95jXRwLnDG7vkWZT8Q47w/rxd8ZUaYYK9wx/0wquPMixTqedLxr5SoT1PNpjW3bngrs3iO2J9fP/S/lVEmx76Rg2rixLMxqdIE7NUQBqowq0dJn/6eewjP0FfrGhmuDa0yKzL1gf4ZLLvIWgsSDx0WJSfq9A6xnKCU6C6mEplDD/5zxDuR1/0AH9ddsVopJ5Ew6UOn9HvzgwN5kzS7mIHZ3Dolb/ffc4Y9njqckonf9jJzEZhGik81UzwulSLILUCtLC14X/jg8fLgSxVJNupzIjwXCTPOIugjwPRi3oP1m8EqnjzGNK8M3DMFNjQacytHZryvHYtfOdvq1eWPgIAi3lT0HF/tBUN88xC7INLH+z5JmVth4zNYVi3H3r6Lx6JUi0RVM4JJy7AVgjlulhxMm7CBqnt5LoscPLK/AvlX/zgsMM+f7xPYrjyOlq1kQOHM0ivd7O+4WpqRgW0I9Pg5/rlBjmojjW15+Y6QiheneqTj7TURJJ9Po=
  template:
    metadata:
      name: pangolin-db-connection
      namespace: pangolin
    type: Opaque
