---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pangolin-app-secret
  namespace: pangolin
spec:
  encryptedData:
    SERVER_SECRET: AgB5NYEElZcrhk32KznyfYl3xLsKIB98ck1dhaa1fULLQLVSdf4OMzkbbTD9vNvqmomyyPI2VIGMXS/qeOGV3O5qiBiQGEdok0i7R9LIy+MJVktDV3l2qN/lSQuSp86fN86njkltRTwUopHZnic7hLkR/LFemhfqHg5DtJTvIMNfTFVeXhMeldZHYngBWQ+N9Q+BNzxKBIJ6CTU48hp2PIsPbSIbrb1RmW/HureV9s9WrXIipUbqapSKBOTxzGEpiq2ikM0Zp0wGBWSRMCCO8GHCkSTKON/q7TNXITDK2mdBmD+rYQ9mtg4FId3YTo/CqWjO+TYJb6yg29MFRdnXH/+Jr0E3KAcxVlZXt99zDi3gZoI1//ByvKwaPV18QuTn70xAQ+RpHMo/sJmoZ3Ta+yiur5KUmsEjr8rTKWbSpl8ZUax8RUYGbVrijKrZRjtRURpNVAmmTIjA4bjmpHXq9mPKjUmE3X7htqVrVN0OkDauFqxtF60+ZaTKXcv4c91Im0FhRSRd9K50UXrVeNHWUvUZ/yqMc0Sa4cVlicEbFDX01MRYXbtPNE1pRoXwULjwemhpQUep2D5pcxQuztMgAkigJ652HRYIA1dru2SRoZmvkOJ14op3PhzCi1WeCNCGyPQcDfMLtflmWDT2fV4UeQNoJ5773IJkrTdT8FSuCEB1GdKA6xNdgjfRKP0fKwooT6QWAyel3Pd+TxDe9pUjgf30i1dtRHUt/GFyfJIuyTSCxYmM97lvE2CtF1fOvzc5LldAb2mv4bncB37tf0IcsQUB
  template:
    metadata:
      name: pangolin-app-secret
      namespace: pangolin
    type: Opaque
