---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pangolin-user-password
  namespace: database
spec:
  encryptedData:
    password: AgCE0tfRyzkHsdpGoddhU4dvzA/jqJYbKOaN54YqdFpdenI9kxyon2Ap/3Whnywm9JMkpGM/bENsLTUMVVLVxmGdVn5jV+qs9RNy3qXxaFXTjXMTCPKR4WhNqXGnwO+6sX/tzm9sWYLvB27LiG39o5NkWBVHL2Ege1EaWx03WfiJVElNMLTa5m9ZTpRCYKHu9uu+MAb2MKrscIM/60iazNUlMop+4g/XmMTSkqS+ZeprboJ5C+B9jo3zCDgTTuBjE3AAGIb+FQ0R7ZYG5vsU9GREmKSWruJchemaehdVR1otkhvBIrCAAOF+DvQOm2v+v1Jj4AiRlriPgYno7totHS+CdOTjwXuAP4dchIAWUfIDu7Sa9lg8sY3KMu5xamNp83w7595XSFjsLg2ows5Vnuie6KzFnQbANcyxUfEedV6XH6EjYsUWj+DvSiSLJFUp00Gbx8EgxjEKoKqD27wYhjbYFeuJTrqJp6MjQon5eYAJEeoRfiLNRYoXZsC3EWNRJrFlnAOALec5Q9bVJcoNXB7qFC+dFhhcSDjY+VzpXi1FvzGrKQBTPT6+Ya8SO4kpAEgkw3f16wAWyveEkg8A6HeBGkLlCMwSnZeetg4EHnwKP9ToOba9k4fCyjir927Mm0ypSoa/hi1NZmmjU6mN3m12m580WD9nqr6KugkiF90v/taWOaNWCZ6DmjxsHZ1sks/8sO81Nja/WcYVzeuatO8iITBy5Q9ZnXi4ZnNsLHlhlPUuj/LNyDFsEKwr
  template:
    metadata:
      name: pangolin-user-password
      namespace: database
    type: Opaque
