apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: hister
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  cluster:
    name: postgres-shared
  name: hister
  owner: hister_user
  databaseReclaimPolicy: retain
