---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hister-user-password
  namespace: database
spec:
  encryptedData:
    password: AgA1hYeduv0ueKuNtr/uzRhAMYv9DMW3tfEpQ9jJSc9LxAUQUDIC5FItP7LwLOl3rpbZ9NCvMD6GAX3QChIVBLOVwVCZdMeFpE23KOtc1YY1hj6Zyz72l9eUUZguNitJ1tur9enXvst1PeW/dVceCxr3g4sBGFIANdu0JKcde5yc4QgVhrflWC6DXkynSdNUij93BltWvgAlNHAiHXDB5meAPY3j0MPLruiyw8bXMC4xcVZNh/PJq27+6aEvI1STGCeGyFtI0imJm6WNjIWnm7Cwq2MB31Zq/yxlVufI7PnjpbaYfn9N0UWY+CRZVyfIfnvYMSj2/SEb3kezW75VAp/VBtOxlpLe3h471iIfmqUJNqzwk84cFWc7ACduhfI/nOIeXYYvW5910cj4hpJvHNQO0gY9Xih4FR8/KWB7F2frqGBfn7FNO+ua18KMCtGMEF5A8VLkbyDlR3+8eUspjcH+FVhKpHIqcBpjcIMQwJe8Wrzifb+VSm50GvtHrm+dQdWAz8TmKhfdFRCE4HjKnX2ViJIf3gX//9Osy6RQwtvkd5FxbuqM6bPjf7ZahnXykqwFpWUgdOYZe1SrKGKihId1ykX4RzLNdbs3aIKXAgblpRVHSqN+penZ4DnwrIgYjOFBGmfNn7fxbS/7AXE3mXh+EAW3JzBxIUGPYABp4OLqcgJjzoanHBSiSSgLmH+kIh2XElLu5ZlOo5pbennkGqNl8hChCmS9O0ojw6i6RdjFgQ==
    username: AgBw90GGFmZSbN4Ym2Emi7021EZgu0SK3pxePRQ3TIELwTyeWUhGVts9CGFHkvZhI+e2HzKGuao98wLhpUC5e/kw5tQy+70RD6GWmZVc9UobHiV172xYwtI6j1+2s5XAikkN/B3PB5fGCLr8dImXxm4IkFxPq1tiZaszHcM3Yx9N6PlcpZFV7usSH+eQa1toKaWkl7f+m1x6r52bmkbgLoUucddmHgn3G///sOnTQ+4adp5TeBV5om6Jy7rkWmno+b87g6+hbLlDBlv3zyiFT4UDfxSGr5KI591MYc+yU8GGRi0OsUIaZM91xnwMjBed4RsVNXDYbNwgWJMU5FViNyojurNnbBX3/VdMXsXRqJteLStFfc6dIG2bsmBPTgf06cihtD6pAzVfPiO3eMFU/zrMbYqENPv5mWo+tFHSidGEd8fsWPbZSoowoZsnRqK86lxrKNPMlGOidtd5lHbnQL9lob58Zly80WkEHfViR8IfATF4PBTscLQlNmg6NfqIiI4r6GZeVri7iGwgQ+jgkf4cYqLlv0dlSw33Es2PJAxyD+mE8I2TxuP7Q+uRAr75YjT/l5FK/g8p0UzRLD4cT19plE/7dAJDEZjrXeizd6D3t3oS3nDjKpAmS+QNxSOrVL6kxe9MPxiBe/5IH/r/EEB5h3SwWH1qKoYV72v4AxMyWZTZqCtqP/1HEUHtSEx1WBE7EoWOKRl2dELzDw==
  template:
    metadata:
      name: hister-user-password
      namespace: database
    type: kubernetes.io/basic-auth
