apiVersion: v1
kind: Service
metadata:
  name: hister
  namespace: hister
  labels:
    app: hister
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: hister
