---
# Library: all uploaded photos, videos, thumbnails, and encoded videos.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-local
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-options: SkipHealthCheck=true
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Gi
---
# ML model cache: CLIP, facial recognition models etc.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache-local
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-options: SkipHealthCheck=true
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
