apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: metabase
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  cluster:
    name: postgres-shared
  name: metabase
  owner: metabase_user
  ensure: present
  databaseReclaimPolicy: retain
