apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-duckdb
  namespace: metabase
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
