---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: metabase-db-credentials
  namespace: metabase
spec:
  encryptedData:
    password: AgA/5KYwW7AUnnHglKnpWyZ4mDloxahCzWpGRcHwBg59Y2k0peNtUHQITp25/WQFPSEToiH/cfKUy2tQvytOG1Cigc6mhcv0MNmar/31WZYzETJGnvDnug/lfW4O1VW9MGFeeIpkt2SgOLqNpH7oP5tSD3RFoQxW5mMYCc0fqI2OVtAmyEabvuzRKJd8F1gjxxkJXRnLIP/I9laoMAjP2bSl+EZjbKJ5s2/oMbyjDI6QwaXSBxxhbnrOZf+HEVPKvMTpMzRbyUUycENzxF9ls+S3aXfprWxLoOLudUXW5fPUkJAyX5MES9H0QXJobJjyA5PavLwabUTg37rVJLTB3NaDGMX1ReA/dtvInIjk1sU+i/k2Eq+ePerw0syyKaMlq2zESkeLMA0ox4ENtx2ouglvwlsczjvMFJDRmX95MdmvyfqAAmSheaAa4Nu5eEse/FPlURYj7+K2zD1g5KGuG5WsA6oUbZ+C7XEdPnVAbTSaFFaHpMfY9ooEmUB5Y2ZBToeU06NFWXZhgKNDMW6zB2DljEXeuUEQJ2LwXWEXRmkTUCSMSUAyeeF4m0bGMS/L6rZ3Qp++peFJ4O+FBZFYbLJliw8S3aNS0QM62F6YnL4o7Wy0jON+4sGuH/jIZSWw9xJKFUqfRE/Fn2BOBqep8EVwTuEM6/5/0u3Ij+/QHMjifK2qSa8X23OahkBjfZSszwJvOYXbbOHaCEIngUuT1Z0tQ3EMLHrFftUEiG3liqAiUAdlYV76P/4+3oVP
  template:
    metadata:
      name: metabase-db-credentials
      namespace: metabase
    type: Opaque
