---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: metabase-user-password
  namespace: database
spec:
  encryptedData:
    password: AgCk2QSp8+ihgAQCIGzVAY2kjhj1T2IfQsSTmvw1HhkYBmIC6P9TV4TU07hhdc/dAURVmyGo8ChM8Vh/v/3u55O+Y9vYg/1CyWjcptZOMg/t2Ytt4WPbJht7H5bhvNutR+PiSJW11pmX2Ndeg0YLBg0Bb/XLQ4GagVN4oQ/mx06XZ6fY3XAFawM/mxWqbc93+MCzzylBlo8KQRbxs29zj3TtKovy2+c3/3qzL9GPWhVc/N7fKXc+AT8Z+vdHlG6rkYi3SkXwdoU0MEx0piep/SiT6QG8lLUS89HvQV3Ermr2FwQrvH1rQeciT+GXT6mWR2SfRcSUixY7vv5D+cf1ie+B5542dtWYViyaYhpCZAincGzaBkbyQ8JXoj6A8+2L2pRAvvQNI3xVX4PRDRyEn14WBg0lZeRIz1Z8z2eASwyo7ib922N9/Baod3YeeVfHdItu3Cw/SP0xOkM2+aVQ4ymY7Chu/kSIRkWLWkUkRAp9FEi+iVfFxwTCwIkvXoqgShyxRbhTOHOJcBR/uG5/z2eS1Qubq6kW9nxyqZN6cKp/qLk7IObDBYSZiXpqYigiSeSls+dANrx59dVjpIJbS99dZrDuQe+xtCDh5YQbcFdQbvQuGQymHe9wRfK7WVvDgJIkAl37igO+v+B+Nmn7C0pZ/bq80PsWqoK+hjCcZcTtOa1yDKd17EqFI3MypscwI/wL55xS7c0FdBT93Vwl/5JC4kdzP5QyolmOECBmYCA05RuSVYYXh5GHfmGy
    username: AgCv8gqQtw+X23304pS8SZg2/c0iME/Yhl6EQmD2HhJFDcKQlCqUwVtKm5wXNYubl7h2ikyBXvhIkruXo0be/uQ8sYZLi5um6TdKn7ta7wMi3lfnGZl4PpPzpRc2p8gNw+/9xEL8tPZaAd6KY/aMx4mVPpCzQPTIMZ+25GJLQSQuEJ7fGIlP+f8QUNkSQfcfuhTUgaVTmt3X3te2mliExqQI/bzivCknjILZp5n5slQNx/96uK6D6NJdIFsFw+HOfqWYZFuheSPbKL9iUskZGKgcg7Lyk+tIOr1tXtCjA9ibxEH0w6RdNWOFD7oaVRG0RqAbcVtMWvgrYPczisWwoThSYwqAU/dfhyF5r7Ivi4jKy6dA+GumRiWWI14qyxhUqJhAWe6OcIMGBHL06sVCgJhfyomsui8sAc04hqgBi6OXSiMctpznbOsYd+h39qliLHJ7XoYhz0RPadyXaWzz9nks981Q1yYAzXQ/fZ+psrXFStjrMVM75NLI2C5eg6cpPYNZ9vvwLAy7YbCrpQCr2G03uSaAsKYbK9kQGmK5uI3MNqlFLJcZnXD32lBA7aqwiT1IK3/nSeXXAdDTBYlKCfT5Iz3SQr6+1qME9rMc7Ci0fSZsEFkqPwM4p+5A4cv6cKHUF8jjVPX/Ci1Eeje1vSs20dxJmvNkFGxjgt/WfFgM2VzTXlxhzVoBsWWSXG3U/XTSIWli8s/Gw/nuFRaz
  template:
    metadata:
      name: metabase-user-password
      namespace: database
    type: Opaque
