apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gcompris
  namespace: gcompris
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lezen.k8s.hu.ls`)
      kind: Rule
      services:
        - name: gcompris
          port: 6901
          scheme: https
          serversTransport: gcompris-kasm-transport
  tls:
    secretName: wildcard-k8s-hu-ls-tls
