apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcompris-profile
  namespace: gcompris
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: seaweedfs
  resources:
    requests:
      storage: 2Gi
