apiVersion: v1
kind: Service
metadata:
  name: gcompris
  namespace: gcompris
  labels:
    app: gcompris
  annotations:
    netbird.io/expose: "true"
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: ClusterIP
  ports:
    - name: kasmvnc
      port: 6901
      targetPort: kasmvnc
      protocol: TCP
  selector:
    app: gcompris
