apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lan
spec:
  # Announce all LoadBalancer IPs on the LAN interface
  loadBalancerIPs: true
  interfaces:
    - ens18   # home VM
    - enp89s0 # NUC
  nodeSelector:
    matchLabels: {}  # All nodes
