---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-db-credentials
  namespace: paperless
spec:
  encryptedData:
    password: AgC2O3v15n8aln/6J3nKy1gG5dhMsjdbvMq0JRypMQcQuQMsBvGUlbRmId6i4DYXZ+4pZ4cTrssnGG/3zucZkVeZ5hXgJnDrbKh8FLF4g8Kqi5mtnsdQCQCJ1DEt9IO9osGZ+ND8XlvkrlUMqPtFkfhd03z2zFZhcQUiEbzD6DfuRVfQey7yieF5rJ5bZlO3Vt5pCW6UiVn6CFiFTS33U/xtUz8zUcasmj5QD9+c9j4j/WxBd13NCFAVLQkQT8gJGrhmQDQLW2o5WpybPEBFcYSg2qylMAoajiNLryWwC3VnUp3ADChDHFnmMi327QnC11v1KDiBHEnHvaBXSo5lkvjS4zPpdDjFRBBR+o2f1binIJR2514yIkMrdk2vBv/VAB6Z+OgXn2AwP2GA4WJgHyPQHjXROSdqKEmzpPLGt7A0gRF3PALeDfSe2ppBL31qjJzsJLQ2BgWJYGfVkg9Dc4ULCR9zTdSQ0tJsrHYUShudewm8OFjNt2OFM6GJx3rmG/ZSzFuEpGaXhsHVoZVJzcCX9JMlKbNaLQ3FGbtYB2OY3E8ms+AhimnmwvBWZxNGpy6qj0R9w090ZnmkmNOtfRMAgz+ak1OMYt2lrhrtpVOvXoiDYRwM/fZpsR06e0MeugmTiAu51nqvcicQQI+QLyiVJPfaY30mTm1hlq0jBjV+8TGdbNPG/sCzOacYfmBrg5WJ2Y8PfI2L8/Wd2Og1R/8vQEy/kmFpRJUqvyCft9F8qMwL/3dKCMGg20slaw==
  template:
    metadata:
      name: paperless-db-credentials
      namespace: paperless
