---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-secret
  namespace: paperless
spec:
  encryptedData:
    admin-password: AgAEzfdumU2ot/H3Ik9ouaZrgqt2NNRIDU48CF3MSwBYoDjHAQOKp/JiWu7Xnil440S7orahLpQJeCE0TKO4bD5DpUmrigZHcGYtvUeVIy52k895ZmiMpDg9F/OvF/GPdXq2KbyHzspxmMTrUp41ZKk417OBFZNqZWbdjAmSqyFyBpx2QkIv2H8hRm8sTU7vMsEd8oPBXd49cCWSveJJrkuVaREXReF7cdkZ/Dm9V2iKanIvmymJEEFTwcFs7Pl7nBTFXt9B/h4k2RsJgXffISlbz2ikKkPgRUq3po4ZH0L/KjeqZd9WiIQoeQ0pp+p0sl6oNL4XH3pto28Y6qIJkmJKPNGExzq89D+dKPGzL7ONAU+k3BgIoe4A1w0TKEo4dp/OIf2hBB5GqCe3R4NwOBAc3IRppN9X4BkXzzhjvSHEEQplUXmL4HhOrmSejNN9A7b6USMebNhVWrqB4Rw0L7vsFUWSwxAD/33eijF6d299zWxuWeP6k18C351VeSYrHJ1gqhhVGCjUDMpQH+GBkjffiNm0/15K8738rApUNdbwN0EW+Z67NuM0YYvArAyCEu9SPXRaGaE4L0bmiSJP49K4XitTn+HfvNyJKE9CBDYLC0WkzbuuzTimg2g+8io3MeiK3YaaDsh5QPJbk8jY+C1a+iEcCvddcPZFeUbwdDqx1IbStPmVgsZYwG7bfV3xaNj090lJXMDvm0oN98Su
    secret-key: AgBTuSJUgf/Jj4ncl15jdL0zpc32CfF9tn4YNtboybieB/rnTZfPR2HLxAZzwLNBdsIHGPhMREObINFDkP9yTwyankdwO+rXR6o5C1rKn72qbiHmhjxSjQjYgmHj4yJlbI8yyPE60IdatyBrKCYi1uybYCJceWDix23RpFjrhZSiu1SmCiuu4jtkIY0eimJKyLt0dJfah7M1TUjcb4pa3XQZEdgd34mNxqZBqVxhsZjuMixgl5BeOrEqRdIVJUsDPTQ+Krr1wcdtCxr+ApNmug4QEKO2UopsCLpY4paqv4FJPzBcGCERLkrwHsegHOlUZGyBgveg7w6wkP3wjtpbMTSJaGQ7SMWGobLCDPyL14pQ4SQ5AvSCeGahNAoOMyT6JyMxTNPBeLyjTE3NtkEssXihgl8RJ1H4f0t2Sg8knn8yeTLxqW/cQGx9QYdGit68uwjrpqNj/qm8mzrpDSSSBe8jKI4SJ9XR8+K1kMbqfPlA+/ggTNzUTp2Js2fwFFmTwHJEWT/74X+qDb7yCV6a/avShtugmz5PwQs47HVyDEf0d/tkmiwAgTJ05uwyi4d0x+nrrjAzvbbF6vrOeGvUSBJt4d1Shf9EzomyTyDVRCdrKHaencgyalRNPHkHhYAaGREdyG7IDlIQX6OOihoWxXaOaSRJQa4/XMTXYPaXiWJq3I5RYq7AxYMjZ/MxtSk+4eHkk2ZJYnZKNvk+olIVFl3CuvHTkbRaiqldojNh6uIvfRpp2bcBI4aSnSfD65F975CM2NQTUx4lA2nc0ZTrfYms
  template:
    metadata:
      name: paperless-secret
      namespace: paperless
