---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-db-credentials
  namespace: paperless
spec:
  encryptedData:
    password: AgCdqjBWnbOmEv0AETesGh+OVfMqgbQP9MaQJJ9d8ziwJVX89m+BGz9lMs1krP2nNN1le1faJwIFTa9FgWC/dGyYXf9BQJptnH10oHWhUd0rUabq5zQT4eeDSWCdlT6THGHEZHEfSUp6bshnJJVU5goZ/u2ir6Al3dPJAL0omg8u0O+h8c7t2DDMgXps9U8NMZ3iypRDt1RmFDGU4SivOUgMXTA/u6R7ImLf8eIg92bVsoEh1CIR9BQj5DCwmG9+QDvhm40jKypTMCrvNDMVs6EEeBmDvpdYhl/etCHHKwqC9IAQP0bITlHMcH32xpkVUnEptop0DqBojpweJdOoCfuaTuN/Zco6BlXM7DgpDY5cT6sE24jADAOBmgQIBg9CKwkthrUv8VNQ9CnC/7CBjPY/k/w/vwL5dQLXzsNg671vex3CG3t7Of3nZQ++NSXirAun85Xdlm7ikZq+2reUr0Mdxy64nr9C0dZOqk9fo2UvbjuoeB3s0ytLdLG0udV/ohIwQtxO62lEJrPjqZfh16w055IoJh1BSNdBscEWbGyH9yVUzdaqC3Fd4HTxf+yNSXEXcV1cUXEBNXmKmetcohsTm0HOHOs6hVtrp4T6oExZDl96uIDwSq1/o+acDpTfEbXlWi6oAf97nWY1ZzrrBLfXE6jTqTaoWC9sTODJJqNl/xs70yRKuP/F1LBeHPYHhl/opylyaCYRwy+2LVlaiB+ICHjucucMYPq8yasiGCHgdLr3N4JrCwcrvWNbow==
  template:
    metadata:
      name: paperless-db-credentials
      namespace: paperless
