apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-index
  namespace: paperless
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
