apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-storage
  namespace: paperless
  annotations:
    argocd.argoproj.io/sync-options: SkipHealthCheck=true
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: juicefs
  resources:
    requests:
      storage: 80Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-storage-local
  namespace: paperless
  annotations:
    argocd.argoproj.io/sync-options: SkipHealthCheck=true
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 80Gi
