apiVersion: v1
kind: Namespace
metadata:
  name: wazuh
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce-version: latest
