apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-backup
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ApexAlpha/k8s-cluster
    targetRevision: main
    path: homelab/cluster-backup
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-backup
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
