apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: cluster-backup
data:
  rclone.conf: |
    [garage]
    type = s3
    provider = Other
    endpoint = http://garage-s3.garage.svc.cluster.local:3900
    force_path_style = true
    no_check_bucket = true

    [nas]
    type = sftp
    host = 86.82.52.4
    port = 22022
    key_file = /secrets/ssh-private-key
    known_hosts_file = /secrets/known-hosts
    # OpenSSH 6.7 only supports ssh-rsa/ssh-dss host keys and legacy algorithms
    use_insecure_cipher = false
    pubkey_file = /secrets/ssh-private-key
    key_exchange = diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1
    ciphers = aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
    macs = hmac-sha2-256,hmac-sha1
