---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: cluster-backup
spec:
  encryptedData:
    rclone.conf: AgAAmoxImgpHU269Puq+W+tgJrluVh20FChiEnNj9FD+fweoNWhHBb5vUjNi/I7FQoFtcLbvPDy8S3sw1R/Xyo8XrI2ZjDTnp3/vCwgS5Re/uqx9J9na99/KOGtX95sQcZF6IV2kTTY/TPOIZBu540/n+pK3sYzK/KFEM6LaGvRvG+gDFVl19EplcUaUbXDra3XOOCYJS2W2l6RG93aWhZGDxXoG1NuM+kbjF2+QEKoxgcQfG+1PK1h/j6kDGM5qKMnyMhV9LbA2DJ6FJtTP+ftEpGPl5FPJBINz3sQSuC1F6lqdhkt6LcfETlQj6YWqGMnrkF7fjULQa4PVpTDG/aO9Uu3FnwpXiChBfUQjfuADe0Al+oh9zxYrB62aGCTDeUlRpFGpLl22wnyzscsV8hnUzk4nXNmy310f4lQTJPIZv3E/mcE6ZMGWr7yXLR58Hj47MnZ2O8Dg+/mRq4UF5/L/2yT7gIPMemrQXpwSk5LiRiyb/G7Ux/rWFFxcWx00G7QtQrIDd/ZbG9Z7XaJNDR9JKIFRr1Eb6ufKXxhNj2TrHh6So1jha/NM1eyydZnnDrkgGQ4+8hD6MPskZEE991FEqfbmQq2sNtmQ3nWFbteyut2fAtR+imumDsB5Knw6ShHFY092XOAmgLRr2l+zoIELdr9GefY2PzslVzudKgQYXVhJyEhdPOP62ZZsDJGROcgk9fQ70lP6HVhpwQVVHKjAGu8fnXxlzoVUDv0pN9W0SgdpjAboO4S4M6OHEnCoSAiGj1JKtNYgvQggv6e3NIobvZRcJMgSN9WRJ6GqkOUMyCdwD/eaaw5dffU1zI3sq4C8ohSOMxHtHu3uetBX4VHywxy0JI2dctL69NiSYWlGBl+SeEh+Ve01Vbr9dA6qXKUDm6W5MWm7AMdAambpJhM0W6rLgU6Afq5Yhyjqj85FbVLzcYusbRt4bEgZNXRXpKZtVuvfPtF2xbcZid1fW01qnjE6lPTeD8+kFDebH//4i3CzovoTaLtVkgPR6+ds6i5jDS1e//iJgdf08JudOzUWyoLVnvYZODahZDRNflqjQ53/Fg643l7jHgADc9Sl/rwVdIhufvnCkYA8nm5LbkgFQzH5glbm9T20amqYvxVzNxv9sUTczCQ3hPiNczlyf7+Ur+42qwiagE+cswfVY2CGMz5p0+lAoeaVhMvVBGYkI1UMe+0Tj68or4WTbmEgYBI7jKf3bYhMtoKiK89sN0y1bEpxn+/8DaBaI1VGFyMLv0XO/Q==
  template:
    metadata:
      name: rclone-config
      namespace: cluster-backup
