---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-api-secret
  namespace: hermes
spec:
  encryptedData:
    API_SERVER_KEY: AgAzXvdK7Ccyspas8clpB1vXXT6D0FAYGe3/FTvNvIDKp8O5taur5UQ051qHbfhQQVGVU9/U7ttnDCV5Ux08B/lBNHM8cfwwO4HknN8i1FGa1P6k+UeCeBO9N7LHt1fh2d0sKABlGFZsvcsAxjmzlHO6R/K2gLBQXwR8OC5I8nSJjlkRpQxjZcXe+3GF8jZCIf76pWj+cKMwIHXMQDjPRaFRFFEVo7r70MvWqG4rrCj2FOjr0WgV2Z99g4pgF36urmJXEA4UuAMP7jzWGs1GJIrbjRqZTpKg6e5pGm89/MNKBdt8wKVB/y4dJ3Qnsi+6Lst2bBGxGIKUcVw71KXgmQoAvlaLVv78yb7ZCPG6G8mjh+3QaIga/vsJAj4/n2QS0/GnpZYdGyDm5ZUT1T6kTlVPCE3Dc3zZnWxklMb8r4xr39fmnKNSPqQ3W8r+PAtcRIVYJFGdYoVkz6YzBwAmx1AA54V4iDu32hBSVntaLhgRFniyjRbVMZXOHtAER3H2wEpH5nfJtGbCTN6aPlw85mxy8Lfyyl0FCxDAt/jkAn8hiHJYH02thWxIlhclHRhN++fpKveAXjwzMh/MHefuWf754Mb/yKiNEVeF0sF7Sswow9O/zzWhePClGPjsrJfTyecz1feZ2biolXg7rf4FoMsiVu7MMaxQvRT6/T8ePRuO01LxGdVMnrR9+1dGr5rFzxYENjEheaIjWhlE5P9+5qEHjlIIDtsECV0NIwIHuZ4zEgjuszZ3xAxD5YYW6F4pfVpKKY1DCC50z9Bi1gqIXT4S
  template:
    metadata:
      name: hermes-api-secret
      namespace: hermes
