apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application.yaml
  - middleware.yaml
  - authentik-secret-sealed.yaml
  - ocis-ldap-outpost.yaml
  - ocis-ldap-outpost-secret-sealed.yaml
