---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: indexer-cred
  namespace: wazuh
spec:
  encryptedData:
    password: AgCgt/GZDWulfXWBswXRDo3zr1yvPjM2r7zntKDv2OnQDCx6Sp8Hxua3ShtT2zFB3mp+j1Yx/9qH5RbKNDo++x2fyYJN+UYasUmrH+kEGMKZVQqs5/mBRy1YUrM02KThu+Emnx9sn1yFAa/y/aNt3iMHX5Vg6bvCDfrPDofw5iVO+BLnMNL8AssH91zrYT6KCMyJ/KI/t/yhSvSQddmfcTyS3a1KLBFa1OmiGWrw1SRphNa3djMdMmCmYifATmqrHfGnw2eLNeMRZcemgtMpNkeb6qaUsh7waq5UeEM7pUajcfN+sDtty6JXm8SAv8fLuEudMgsWITYR0ca0m2cK7jdJnZJT/DnWfU3ZHIv307ZDWgoUZ3L/6j8EWNgVdxxd+47raTY5uVxytnSB3seoqVw+ZLl6f0aurLgXS9BY2eGKpoNz0OIOaPCSkTLVLGKKyvI3WGXp9d7vFvyYpCNXCJTEGYfSQimp9hHo2v87NN7kdLNC480ZmA5fsv8ZOxZbmzThf0fnTtwDK0r0q+0YcZcYKEetUujNEz1Vy2UYV9X7t/ZqaYQwtg+OceX/A/dGW5bO6+y+4fjjhbrNV0LCeQ2YfnCoIBeLSn33cpVUoW3kB7CrHhFKwAbbe7PsZZFfwaYNtwzfgM+CmEMMdDTfujPDU/DhQhGZburGxOpBicMcDq0PhflciXtxIxpjyA37/wpuK8YsYACkLJjH11t/Um6ShLH+BYc7Gs8LPwgZ
    username: AgDGd0wDLAAYH69aLBrVWyd8L6B4SvfqWUSe4PP33BFz6fJegMdx335xKFeBS/hkYEROmvmnI4lwYehArKYCyOiGZ2tF+W0iA3VO2GZmdfF+9kGGdYibkP2r3WeXQILRnnr/eIlPnA6NbGLMWlOyN/rV+LD9c5cG1BkX33SrnGWJe/dWRslOLMAqhzGEcU2KtcruKPHHAxd6RJtIKGLOZAk6wPR3+lYDr0X1whbSLCjawa5l65QRX6SU+A9LdrcJrd21/dqsGZw6EkX2GDJIOmqbad8aPsTrjwHP/zTUXEneULQabAwQAUsiykI/izh7IxMbE0WzKBKHA29aDeG1ELXq/fDyHaJxTK0vJ8kBn6raf2XwuIn/9DLwUiWV2t2XHOBav3GtSvR1gyqYLzCGzmap0ocuQQifuBT27keO8EZwoNWrT5zy7ac+VFYSTtnxxHbS8bvNUWU35noV8rZxoki54Ol9RdwSp1GkUFkxjh1oAFTv9Mlek5O2W5RaAkWUb0HR0NYIF/Y3VMmIKolOv0B3LcIDNE2O9jVIyxh4So+BuR51hpLPCpLZ6GGiIhyxGo/jEd95fpGovxtSAklFpKPhU3/qr0xNUNh8hJpkK0SEJqDw/iTwN8Ymxch3lXC+e+FHFDgliparyWZeF6b9gXL1OyVkxkpbfWFr16TUd+4lu3Ia9J86Xo1kp29bz0E9sMPAhe3LPA==
  template:
    metadata:
      name: indexer-cred
      namespace: wazuh
