---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-cluster-key
  namespace: wazuh
spec:
  encryptedData:
    key: AgBBHD/vujvdBbbB2/cY7p1moaQWinpjfRdOfgCoJVcN3yjfYyqkvcK1ymQ5yiVu//0HwaSYUFKi14h4/3KtLY18iVhJXlq2cwVu2qEca0Y4VNj+RacPB7FfPlVySQ0X+lp//FO6QcQu7O6JSrE+drIBlZDTR8MFPj8A8SAg0twcoZYgLDWLvRAex3zRmT+4riqQJPjjKliBl1l5t5KE2L3fam82GZkU7t3gvn2truqns57lMoh4DZI0aVzyYsLpLVKrhUyQKAqCNeoZ/gfqcRrrwZTB+d3DhM8J38KjVIu+e9LI7UQGGMMvD9PUjM21xJg+Bl6vXL0+RK8sklDBrGb8B23Dq1XXm9OlPraU5DtLCxvd7Kvxy3y3K6L9R7Al2+fY7Pst2+DLkOnbgsgbFeWiAoligTTLrtqy72gvNqjaWHsyQ3/rU9HsN1uGmqtdjG8gEPQEY2MMADH8FW4QyYslXIWJfAHPU/IAmuauoRXvUqvBWwD9eVI++XPaHuLTRTKDCrpXbMNj+6T00xwupWJNsSmq3cKWK1A1kRXs0wOJ0pmBPtkW3PZRR02edADPcx2cUy7IcpxrHcarMIu1MW75TaVjIMa3dW52O7B4aZgBEGYS54Xratgj05KJC2bR/Hzx0ooheq6saYCi4aYyCWMioPLG8ykbUDMtj2LAk6jASiTT6unvCpOIgfunE0OGt1ucN1SWAMpB3/kgM8M29md+27qx32Ga/zrCySQ4/UiFFQ==
  template:
    metadata:
      name: wazuh-cluster-key
      namespace: wazuh
