---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wazuh-api-cred
  namespace: wazuh
spec:
  encryptedData:
    password: AgCZmiBH0ZIWX2poqVdQVdpz3fuHQnyxtzO1/j688PCKTjw3pkKM9Ci9oDSRGwva1SZ7/HphGg5P7kRUcOwRtm/e6/iWytKx1vTyuuJ9BgiPlQbEBJrI0Kjix4DxZ67tB2cnSAeP7tgfqe4pR+LVrpPqorEhdeWB/Ea4yMhhxGQ85vZ90mPNOaqHA9xl5GRLQE0moQEdpnhEnNPrlhelAucWFyej/cXb3X6K5CTOdJbsLeolxFZAOkWX8/u68/tbDGMhqWAtFCvxpw/nQffQKxwN2rhnpvy53SD8b1Fbmcgza4oaroWxAk7IP1nosfQeeaTShgikbRp9dsyETGKsiOe6Aa2FLtHP1kZ1/RY42JeGX1QV1ueGIqwYfWaaGh9c9U7CgRSNCyEKAZMKA0qdfT5sYThiMYOkjMo6WffQ1MoDSpcPy+F5sZxdDVds+KWG4gZk2wVpzc/vJiGx58GeqdOiMA2kO5rn/nbDYXEfB2HmqfVNf7xrefBqtCcC2cxqLFoX6WUo2IdQ8pGt5F7BHRLrmQEEpOBNB/aRoYXaNrz1jrdAx/L+4j6dln/Ri+DQ3+vJgvmZNtMXJLO4RFaMeAQhaaN2y6OAayjMpLKIUn8FoddvAdSACUERZJZyWdYPQaLVZsJ1t3OczUSSylc3tQR4UdATtTHT8o5e1Tl9JS30ukdPGiOcVmaTXkbNVkTOnvEdzaQFC00U1dmKfQAmiQdkfAHz2DyF7MyBZUUN
    username: AgCYs98u/CBT2eeak8wgdIINxTsgZrMdt2zUAhbpcj0btbGGSrprjKjwyvJeJf0J8yhr0t1FEiS8AoBMtE7PBovJTCN93kyqDn6vLr3aaS9g/vKsWilvSL0nTrvMnDEYfarI9wZ49pXQG/P8suRf69nWDwjPyT8OxjruRnNdb2hZliyEE/kV2nWvVqkMYkZKaSnyTgi/RutBFs0U4zTP6YzwYwFDnWhyUU4o4BUmsqr2avR3aNrIzdaidQyv3GwV+k3uTqaVAL3Wsp/CRKCmFyLcwZ8nXmqqWVlYxd+sZ8oRQp06Sb8rljV/4twZPxUf7aM2cLRYn48qaaG1Yu4yrvwdKejWIqE+33K2auU4M/Pns3hBNVz3QkrCTAhMvumPxeWBEgPmjloICOC2fqHReQUFR5fbAbyFS1hgGvWfLxjTcgnxy/U8nSIVmTaK+4TLjeE309qtPaL8n7Tc7uWLXFdMm3cyVywd9cDJhS3b6NZxwUUW1nmGRuFiUAiuzJEUZGxXrhI8H+UF8QSbExUe1UuH2QjxHI08zAxHe/d2juz+d70UI7pVbPyQt+wSAAy3XAtXT6nL6NuTPz2yNHQA6EUx1h4IkziqaKdWgs2kgju2qOsXFDfziDTdmFYonld4b7M+KJ2qbbF/C/f63nqx6ypVUFsghYelG0Qdao1cbs4tW7j3r240X32oawnKWFQuWroJuro4QoajPTo=
  template:
    metadata:
      name: wazuh-api-cred
      namespace: wazuh
