apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  k8s-hu-ls.server: |
    k8s.hu.ls:53 {
        errors
        template IN A {
            answer "{{ .Name }} 60 IN CNAME traefik.kube-system.svc.cluster.local."
        }
    }
