apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  k8s-hu-ls.server: |
    k8s.hu.ls:53 {
        errors
        template IN A {
            answer "{{ .Name }} 60 IN A 192.168.1.245"
        }
    }
  hu-ls.server: |
    hu.ls:53 {
        forward . 1.1.1.1:53 8.8.8.8:53
    }
