apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-importer
  namespace: firefly
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: firefly-importer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly-importer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: firefly-importer
    spec:
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
      containers:
        - name: firefly-importer
          image: fireflyiii/data-importer:latest@sha256:1379248292e1a0820e73714f3676b6de3909178c3017fce7aec0a9d20ffb8dec
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: APP_ENV
              value: "production"
            - name: LOG_CHANNEL
              value: "stdout"
            - name: TRUSTED_PROXIES
              value: "**"
            # Internal URL to Firefly III (within cluster)
            - name: FIREFLY_III_URL
              value: "http://firefly.firefly.svc"
            # External URL used for OAuth redirects
            - name: VANITY_URL
              value: "https://firefly.k8s.hu.ls"
            - name: FIREFLY_III_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: firefly-importer
                  key: access_token

          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi

          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            failureThreshold: 3
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 10
