---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firefly-secret
  namespace: firefly
spec:
  encryptedData:
    app_key: AgA+RHz+g9dhyhzFly/DMZfgc3h174b1uQ0ibhlqfuzb7IFDYaRovFWLnnZs+A9XAScdBVVJz7MRSCQ0h3ktakcEYqQUVxPIZIcMN/nlXytUXr6jr3ogjlNgfpeFF2itIP4mtt/eHNjjWzSXCya+VqFYAxobY4hyD2OkY8DcNBmJLcMiO2FFmDMb8rDuM/eSLZ4Ar9PdsWVIee+rH5+WaD+d8iB977kfW62m6FCYKW92mu2YO/EhKw3In4NOPICPEv2nZ3zdrkKkBuJZV9nI1J6f06eMx6Lz2wSKXYClXLSrNp6Owk/o2QmftRIa+KU7MHwmQzOlY7hVH3dVUXe49337QGF1+aLl1BaoE3RBUAdvZU0FecBY+PR+4hE93MSZi1pRroEe1VopbZj5m2Iqk2SiVHZZ1c+9ykpEshHM/vmLS60FEzywlXfUYnKRPqmu7q9i15WTg/5qQjtRK5GAVRUezDvqfyYh1eRdzW/+B2ahQPVVQGPa2RdafzLJyasLJ7T3DMphfVTpTsPichTF34GOVYDR+iJsd6f3qrQLozhExJ+hKfFfHAfoF7oHOF6kTtmHPwTrJjBzdCKPqZaNIgo8Vo4Qw97fY4FMYHeHQCJWV5DO48stZgMfb8JItRwpYD9yL4Hb0GdAqNKShYwf+C16MXfBfqomTrvjdeI44lVTQhiTUywOtwfYscBPPhuv9n5RBJkur5QDxRP0XFelurIw/afNXPgNhCugMyq1QzwdoNvyURsM9CB6l+WSpBijjvEfF34=
  template:
    metadata:
      name: firefly-secret
      namespace: firefly
