---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firefly-db
  namespace: firefly
spec:
  encryptedData:
    password: AgCfd/leb46Rb6IOAWRBcDtUjUBXrMGYNz6l6FyhAqLGzMH97D5uda8saAHPOdUhmF1PKoW7qOmRgca1FRQXp5jG81qbGhYSlRP24l1VE/HHnj2LjGcv2RzePIAXgVEfdIzFmY6Yyll2ar7kT3LgseLpNCU8f7nZyiV9SjTaVQPCQ6ApzJ0higztjkOqFVM3mQ0Xg2enkXb0NTfybTHB/j/05QluIe6pkmrZhVHNBFq6ZT43FmCWEmGGh33nd9R7CcMrHfkGVNFtoldg1H11388xZa4r0tkSpKllKETUJHdwNgvt8zr4g/WyDPFRUat6n8sid99mmwQF+MzwR26TKUcgLWFZNF+G3Sv0s3mZeWWYWMQRk6iwC6uy8WQSfkQDdvLu+SzMFWtRVe3bht+wwahdBNd34cFvaYPJlsTsOFaPRpI84xFHCazAYcrloLJZEEEPMYsgA+PsB8Ca+MtWy0tfuqTCIuE3DqSospwIKBs5fSJ4IWzvDC0ln30nAZrKwQ/yA/fau7Vs85Y3fx7FYHUyYV48KDeI/3foRW0LQwxkT46x6zkSEX6icPq8X1nfFUllmvLrq3cpUfuMjUeFaMbOWF0vy1M415UD6qYjLlTNRJzIRn3c6E3Lf8MuBO9WzyAiwSYJPxXvQHS03MKBmmMwc3vrT0sv0CDZevpNeDatzKHVFH8jREggRF7q/1EikSWv+z25GjTBmNqTE0yc7NzQfdYpLyGZA6246exLFMrxhQuzQB5i1jGtWglMnw==
  template:
    metadata:
      name: firefly-db
      namespace: firefly
