---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firefly-db
  namespace: firefly
spec:
  encryptedData:
    password: AgChrvx2tfCQ5oJWN2bZ4UTPRgErVbNUGjsCU+8a5C5qcbYrt4bp05MOC5sDu1EevWpkcvzgjLV/QHkxVcmVV6VD0Ov5MGwUGaIlrB+IZBjVWaNkWDLE0b3vBgDJU2vRAJgFKZS6pDj0igAvXVxkWprg/2fbyrwYAYCA2OlbmTYWr9bso29ySr3x6OT7v1LOYjbGuX53H+QmkXmy/53W4nSskd9RCmVIRd2jjaE/hzcm46FViSYQIWA3IfiPZrukEjs1UiJ22/ekES5mHYVy9lBWsA44E31H/fClqSDs1I3QihWznrAxf7HXdUXbXAzliNdZshJmMuGaQ0Ag80VAHXLvgtj6CTzTFNRNwV0zGYt7w3UdLH1zj7jIaYmFezP9ikHFedBH67t53y963wGVtnkZkyASS94UN1NGokRSZWZb+9wXRzFUKWtW+G6u/hXK54ZgUMVIBJvgTfAS0SCPYjim7F4MZ1K/oetn2Hj4MN7ZvjesSg7MhBKYpT4nOu4xDTteIx/7tz5EJ+I6D1JzJ2Aawirltm6T4ZiWRUcRNZnp6pze4zcRg22uUg3yGpcelrLFk7yEP8sao/0q9ZDOtfORaxQPWXepo7uSbk8PtuLB8T3MRseyDs6hFHgFXTQciXGpAhaY1i2/FWC1g1o0B7V/v1N4jUlEv9F2Dnf1TYu6B55WpUjgEeCDIDTMhswMsX/2gJGmgA4KxKQP9l2ix00xom83nJdDp4b2r9LXePHsrtAj8Kj0C9IKXlCqHQ==
  template:
    metadata:
      name: firefly-db
      namespace: firefly
