---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firefly-db
  namespace: firefly
spec:
  encryptedData:
    password: AgCXwABWWt1mqDYcFnILz+IY7MqnrfB9NXvZeF2RTl2JUTjmrnALrsuVNn24JFarybO0gJx3nGCrMqCcQuI7ls6KCag3wVp0vAxZVIb1qulyifu+IwLULXnoVcHfQQ95IEAcy6FWMW4IN4hNiVFVUWvF/38nb0Nb+7JIAozKZO42XmgbacHZb5MzpqsbF3kt/z4uQ+t2rtdm7VjFBnFiRsZkrzQcqj3iI91vIPugu2IOQ5IwY72SnsOgjDEweLofxXppWgXSPow6Fr2L95+UX/28YIYM4UVZ8OwgbWn/2HfKCdCyiDQfpr1fQRbG4/fBhGXq2f1qNgw0Z8hv3UOSfuGeigiV3KIBafF/L+O4RtbHAMiDby2oXe4kK/TTim8I2wUR/YY8rDHCH0NXIQYi2z/kalJazL45ztdwkjbqWNsOa9FLQfUeSDpG4ppRvKW0uhjcvA19+gyny/iRFK/vFZXyxvxxLve5S44a344dL5EG0E+Py27LJ5DDks+cQeeKZH1gfM3K9Tbn+MF9XWE9R739J5qOAwQ5japmvwX/7Nr678TDlZfy4xXsixKk6TU8RKBxHWa774FLQC/wNyTteLclBvG6SH7TVvwBFjWWz5+m6VLfzytPhdrvHx5eVqi0wg9gWSBV6/WjK5zfYUcTFdAhntr24goYo05Vo84BQ8hbDV8du3hhFeSQbr+yIRSguz5yoTvNVJFQLj21rcy9Zwt9eSinmTDFuEg0kvfcq3fKJqSmwJ8xz2pcBtntNg==
  template:
    metadata:
      name: firefly-db
      namespace: firefly
