apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-uploads-local
  namespace: firefly
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipHealthCheck=true
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
