apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-shared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: 10
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ApexAlpha/k8s-cluster.git
    targetRevision: main
    path: homelab/cnpg/cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /status
        - /spec/imageName
        - /spec/enablePDB
        - /spec/enableSuperuserAccess
        - /spec/failoverDelay
        - /spec/logLevel
        - /spec/maxSyncReplicas
        - /spec/minSyncReplicas
        - /spec/postgresGID
        - /spec/postgresUID
        - /spec/primaryUpdateMethod
        - /spec/probes
        - /spec/replicationSlots
        - /spec/smartShutdownTimeout
        - /spec/switchoverDelay
        - /spec/backup/target
        - /spec/bootstrap/initdb/encoding
        - /spec/bootstrap/initdb/localeCType
        - /spec/bootstrap/initdb/localeCollate
        - /spec/monitoring/customQueriesConfigMap
        - /spec/monitoring/disableDefaultQueries
        - /spec/storage/resizeInUseVolumes
        - /spec/postgresql/syncReplicaElectionConstraint
        - /spec/postgresql/parameters/archive_mode
        - /spec/postgresql/parameters/archive_timeout
        - /spec/postgresql/parameters/dynamic_shared_memory_type
        - /spec/postgresql/parameters/full_page_writes
        - /spec/postgresql/parameters/log_destination
        - /spec/postgresql/parameters/log_directory
        - /spec/postgresql/parameters/log_filename
        - /spec/postgresql/parameters/log_rotation_age
        - /spec/postgresql/parameters/log_rotation_size
        - /spec/postgresql/parameters/log_truncate_on_rotation
        - /spec/postgresql/parameters/logging_collector
        - /spec/postgresql/parameters/max_parallel_workers
        - /spec/postgresql/parameters/max_worker_processes
        - /spec/postgresql/parameters/shared_memory_type
        - /spec/postgresql/parameters/shared_preload_libraries
        - /spec/postgresql/parameters/ssl_max_protocol_version
        - /spec/postgresql/parameters/ssl_min_protocol_version
        - /spec/postgresql/parameters/wal_keep_size
        - /spec/postgresql/parameters/wal_log_hints
        - /spec/postgresql/parameters/wal_receiver_timeout
        - /spec/postgresql/parameters/wal_sender_timeout
        - /spec/managed/roles/0/connectionLimit
        - /spec/managed/roles/0/ensure
        - /spec/managed/roles/0/inherit
        - /spec/managed/roles/1/connectionLimit
        - /spec/managed/roles/1/ensure
        - /spec/managed/roles/1/inherit
        - /spec/managed/roles/2/connectionLimit
        - /spec/managed/roles/2/ensure
        - /spec/managed/roles/2/inherit
        - /spec/managed/roles/3/connectionLimit
        - /spec/managed/roles/3/ensure
        - /spec/managed/roles/3/inherit
        - /spec/managed/roles/4/connectionLimit
        - /spec/managed/roles/4/ensure
        - /spec/managed/roles/4/inherit
        - /spec/managed/roles/5/connectionLimit
        - /spec/managed/roles/5/ensure
        - /spec/managed/roles/5/inherit
        - /spec/managed/roles/6/connectionLimit
        - /spec/managed/roles/6/ensure
        - /spec/managed/roles/6/inherit
        - /spec/managed/roles/7/connectionLimit
        - /spec/managed/roles/7/ensure
        - /spec/managed/roles/7/inherit
        - /spec/managed/roles/8/connectionLimit
        - /spec/managed/roles/8/ensure
        - /spec/managed/roles/8/inherit
        - /spec/managed/roles/9/connectionLimit
        - /spec/managed/roles/9/ensure
        - /spec/managed/roles/9/inherit
        - /spec/managed/roles/10/connectionLimit
        - /spec/managed/roles/10/ensure
        - /spec/managed/roles/10/inherit
        - /spec/managed/roles/11/connectionLimit
        - /spec/managed/roles/11/ensure
        - /spec/managed/roles/11/inherit
        - /spec/managed/roles/12/connectionLimit
        - /spec/managed/roles/12/ensure
        - /spec/managed/roles/12/inherit
        - /spec/managed/roles/13/connectionLimit
        - /spec/managed/roles/13/ensure
        - /spec/managed/roles/13/inherit
        - /spec/managed/roles/14/connectionLimit
        - /spec/managed/roles/14/ensure
        - /spec/managed/roles/14/inherit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - PruneLast=true
