apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-data
  namespace: audiobookshelf
  annotations:
    argocd.argoproj.io/sync-options: SkipHealthCheck=true
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: juicefs
  resources:
    requests:
      storage: 10Gi
