apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-k8s-hu-ls
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  secretName: wildcard-k8s-hu-ls-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.k8s.hu.ls"
    - "k8s.hu.ls"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ".*"
